[FEAT] 나의 라운드가 종료되었는지 조회 API
woowacourse-teams/2024-ddangkong pull request #102
Opened 2024-08-01 06:48 UTC by GIVEN53

## Issue Number
#93 

## As-Is

나의 라운드가 종료되었는지 확인하는 polling api 필요

## To-Be

- api 추가
- api 문서 추가
- 짜잘한 리팩토링

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
<img width="588" alt="스크린샷 2024-08-01 오후 3 46 52" src="https://github.com/user-attachments/assets/10cf3b30-f752-4774-ab91-80d63930172b">

## (Optional) Additional Description

2024-08-01 07:12 UTC, leegwichan requested changes
프린 고생 많았어 (나도 고생해야하는데...)
도메인 로직 관련 리뷰 남겼으니, 의견 or 반영 부탁해!

2024-08-01 07:12 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    }
의견) Controller 메서드 순서가 GET - CREATE - UPDATE - DELETE로 알고 있었는데, 아니었나요?

2024-08-01 07:12 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/room/dto/RoomJoinRequest.java
> +        String nickname
👍

2024-08-01 07:12 UTC, leegwichan commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    }
제안) `room.isAllRoundFinished()`일 때 `true`를 반환하는 로직까지 `room.isMyRoundFinished(myRound)`에 넣는 건 어떨까요?

```suggestion
    public RoundFinishedResponse getMyRoundFinished(Long roomId, int myRound) {
        Room room = roomRepository.getById(roomId);
        return RoundFinishedResponse.myRoundFinished(room, myRound);
    }
```

2024-08-01 07:12 UTC, leegwichan commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +    }
사소한 의견 )
```suggestion
        @Test
        void 모든_라운드가_종료됐으면_나의_라운드도_종료된다() {
            // given
            int currentRound = 5;
            int myRound = 5;
            Room room = roomRepository.save(
                    new Room(FIXED_TOTAL_ROUND, currentRound, FIXED_TIME_LIMIT, RoomStatus.FINISH)
            );

            // when
            RoundFinishedResponse roundFinishedResponse = roomService.getMyRoundFinished(room.getId(), myRound);

            // then
            assertThat(roundFinishedResponse.isFinished()).isTrue();
        }
    }
```

2024-08-01 08:16 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    }
7/12 백엔드 회의에서 논의한 메서드 순서는
1. 짧은 리소스부터 오름차순
2. 같은 리소스 내에서 GET, POST, PATCH, DELETE 순서

이렇게 논의된 걸로 알고 있습니다!
이후 이 부분에 대해서 추가로 회의했었을까요??

2024-08-01 08:19 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    }
프린, 커찬, 썬데이 페어 프로그래밍에서 나눈 api 스펙 반영
-> 해당 로직에 변경이 있으므로 로직 변경 후 재리뷰하는 것으로 결정

2024-08-01 10:14 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +    }
https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/aef523fc33aeac9e2dceb9a20727d9bdf4270c69 에서 반영했습니다!

2024-08-01 10:44 UTC, PgmJun reviewed
고생하셨습니다 프린!! 리뷰 남겨놓았으니 같이 해결해보아요! 수고많으셨어요~!

2024-08-01 10:44 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        private static final int FIXED_TIME_LIMIT = 30_000;
의견) 이 부분은 ms단위가 다시 s단위로 변경되면서 30으로 사용해야하는데,
merge되면 제가 이번 리팩토링 작업에서 함께 처리하겠습니다!
혹시 확인하기 편하도록 프린이 작성한 코드 중, ms단위로 작성해주신 부분은 TODO로 남겨놔주실 수 있을까요?

2024-08-01 10:44 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    public RoomInfoResponse getBalanceGameRoomInfo(@Positive @PathVariable Long roomId) {
부탁) 이 부분의 ResponseStatus가 빠져있는데 혹시 넣어주실 수 있나요? 제 부분인데 제가 실수했나봅니다 ㅎㅎ..

2024-08-01 10:44 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +    public boolean isMyRoundFinished(int myRound) {
의견) myRound는 `현재 라운드`와 같은 맥락에서 사용되는데 my라는 Prefix가 붙으니 개인적으로만 사용되는 값 같다고 느껴져서 변경할 필요가 있을 것 같다고 생각이 듭니다..
지금 당장은 떠오르는 단어가 없는데 같이 고민해봐요!

2024-08-01 10:44 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +        if (currentRound < round) {
사소한 의견) 진짜 별건 아닌데 비교의 주체가 되는 대상을 앞쪽에 써주면 읽는 순서가 정렬돼서 더 이해하기 쉽더라구요 ㅎㅎ
ex)
if(round > currentRound) == round가 currentRound보다 크다면
if(currentRound < round) == currentRound가 round보다 작다면

괜찮으시면 반영해주시고 아니면 넘어가셔도 됩니다!

2024-08-01 10:44 UTC, PgmJun commented on backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
> +            RoundFinishedResponse roundFinishedResponse = RestAssured.given().log().all()
의견) 다른 값들이 actual로 통일되어있어서 혹시 actual로 맞춰주실 수 있을까요?
저는 actual로 쓰나 dto명으로 쓰나 상관은 없어서 actual 맞춰서 사용했습니다!
반대로 dto명을 쓰고싶으시면 의견 제시해주시면 감사하겠습니다!

2024-08-01 10:44 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        private static final int FIXED_TOTAL_ROUND = 5;
사소한 의견) FIXED Prefix는 없어두 괜찮지 않을까요?? 큰 의미가 없을 것 같아서요!
암묵적으로 상수를 의미하는 대문자 언더스코어 케이스 문법이 해당 변수 값이 고정이라는 의미를 충분히 표현한다고 봅니다!

2024-08-01 10:44 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +            assertThat(actual).isFalse();
사소한 의견) 이해하기 쉽게 이렇게 작성해두는 것은 어떨까요? 한 줄로 이어지는 게 더 가독성 측면에서 좋아보입니다!

```java
// when & then
assertThat(room.isMyRoundFinished(myRound)).isFalse();
```

2024-08-01 10:44 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +                    .isExactlyInstanceOf(BadRequestException.class)
칭찬) 지금 당장은 BadRequestException 의 하위 클래스가 존재하지 않지만, 그래도 정확한 처리를 위해 좋은 코드인 것 같네요:) 굿굿입니다!

2024-08-01 10:44 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +        void 나의_라운드가_종료되면_게임은_종료되지_않은_상태이다() {
사소한 의견) 요 부분도 같이 네이밍 고려해보면 좋을 것 같아요..! 어려운 네이밍만 걸려버린 프린 고생이 많았습니다..

2024-08-01 10:44 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +                    () -> assertThat(roundFinishedResponse.isRoundFinished()).isFalse(),
사소한 의견) roundFinished가 false인데 게임이 종료된 상태인게 조금 어색하게 느껴지네요..! 요 부분도 네이밍 고려가 필요할듯 합니다!
같이 고민해봐요!

2024-08-01 11:22 UTC, leegwichan approved these changes
내가 눈에 보이는 것 위주로 적어 봤어! 다 사소한 의견이라서 Approve 할께!
사소한 의견 남긴 것에는 코멘트 달아줘!

2024-08-01 11:22 UTC, leegwichan commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        void 방_상태가_FINISH가_아니면_방의_전체_라운드가_종료되지_않은_것이다(RoomStatus status) {
사소한 의견) `@CsvSource` 쓰면 굳이 value를 명시하지 않아도 될 것 같아요. ( `@CsvSource` 보다 `@EnumSource`가 더 좋은 이유 있다면 알려주세요. 저도 쓰게...)
```suggestion
        @ParameterizedTest
        @CsvSource({"READY", "PROGRESS"})
        void 방_상태가_FINISH가_아니면_방의_전체_라운드가_종료되지_않은_것이다(RoomStatus status) {
```

2024-08-01 11:22 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    }
https://www.notion.so/ghenmaru/54eed00f2afe4710bbfbc6c67a9026f0#d0c2b30e0f824ee19fd4cca469b7d6b4
아하! 짧은 리소스 순서부터였군요 ㅎㅎ;; (백엔드 컨벤션에도 적어놓을꼐요)

2024-08-01 14:21 UTC, jhon3242 approved these changes
고생했어요 프린~ 확실히 코드를 보니까 왜 프린이 4시까지 API를 정리했는지 알 것 같네요 ㅎㅎ 프린이 있기에 든든합니다~

2024-08-01 14:21 UTC, jhon3242 commented on backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
> +            // given
칭찬) 타칸이 싼똥 치우는 당신은 진정한 검정고무신 똥푸는 아저씨
![image](https://github.com/user-attachments/assets/a01c3fc9-dfcd-4763-995c-40f15428ac83)

2024-08-01 14:21 UTC, jhon3242 commented on backend/src/docs/asciidoc/room.adoc
> +request fields
👍

2024-08-01 15:28 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +                    () -> assertThat(roundFinishedResponse.isRoundFinished()).isFalse(),
|myRound|roundFinished|
|--|--|
|false|false|
|false|false|

2024-08-01 15:32 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        private static final int FIXED_TIME_LIMIT = 30_000;
값을 직접 사용하는 로직은 없고 생성자용이라서 30으로 수정했습니다
https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/9f8b750b882712d296f2e7c6db771ce9a994e144

2024-08-01 15:33 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +    public boolean isMyRoundFinished(int myRound) {
내일 같이 얘기해봅시다!

2024-08-01 15:33 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +        if (currentRound < round) {
화살괄호 방향을 `<`로 하는게 습관인가봐요 😆
크게 신경쓰지 않는 부분이라서 https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/e078e877e39eba4bcdce81071803c6b498083589 에서 반영했습니다

2024-08-01 15:34 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
> +            RoundFinishedResponse roundFinishedResponse = RestAssured.given().log().all()
https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/48c4262116d0b1609205fc8763efedf33a610d4e 에서 반영완료우

2024-08-01 15:34 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        private static final int FIXED_TOTAL_ROUND = 5;
https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/2a122656f16a18771dfee25f4f8c2e3b891f1adb 에서 반영완료우

2024-08-01 15:35 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +            assertThat(actual).isFalse();
https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/dede05833006f187459957328dad651644a315c2 에서 반영완료우

2024-08-01 15:35 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +        void 나의_라운드가_종료되면_게임은_종료되지_않은_상태이다() {
살려줘~~~~~~~~~
일단 https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/67abce011708a83a9350a0ac579234d7f1959518 이렇게 변경해두었습니다

2024-08-01 15:58 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        void 방_상태가_FINISH가_아니면_방의_전체_라운드가_종료되지_않은_것이다(RoomStatus status) {
`@CsvSource`도 enum을 넣을 수 있군요 처음 알았네요!

더 좋은 이유보다는 쓰임이 다르다라고 답할 수 있을 것 같아요 `@CsvSource`는 csv 형식을 따르고 파라미터로 여러 값을 줄 때 사용합니다
```java
@ParameterizedTest
@CsvSource({"1, true", "2, false"})
void test(int value1, boolean value2) {
    System.out.println("value1 = %d, value2 = %b".formatted(value1, value2));
}
```

<img width="255" alt="스크린샷 2024-08-02 오전 12 50 55" src="https://github.com/user-attachments/assets/cbf3e2c3-97a4-45ae-82d4-8381e0e3e78b">

객체나 Collection이라면 `@MethodSource`를 사용하곤 해요

`@EnumSource`는 enum에 정의된 상수를 테스트할 때 사용합니다
그리고 기본 모드는 include인데, exclude 모드로 변경하면 명시한 상수를 제외한 모든 상수를 테스트할 수 있어요
```java
@ParameterizedTest
@EnumSource(mode = Mode.EXCLUDE, names = {"FINISH"})
void 방_상태가_FINISH가_아니면_방의_전체_라운드가_종료되지_않은_것이다(RoomStatus status) {
    // ...
}
```
메서드명에 맞춰서 exclude로 변경하고 value는 파라미터에 타입 명시되어 있으면 생략 가능해서 제거했습니다 https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/2338538817a2232f9fe2e42079c90b7795aeac37

2024-08-01 16:04 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +    }
오버플로우를 방지하려는 의도는 아니었고 `currentRound - round != 1`을 검증할 때 round는 항상 currentRound보다 1 작아야 하기 때문에 해당 조건을 추가했습니당

2024-08-02 05:00 UTC, leegwichan commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        void 방_상태가_FINISH가_아니면_방의_전체_라운드가_종료되지_않은_것이다(RoomStatus status) {
프린이 친절히 정리해 준 덕분에 제 코드에도 적용할 수 있겠네요! 고마워요!
저도 다음 코드에서 적용해보도록 할께요!!!!!!

2024-08-02 05:01 UTC, leegwichan approved these changes
프린 달아준 코멘트 잘 봤어! 프린 고생했어!

2024-08-02 06:06 UTC, PgmJun approved these changes
사소한 의견뿐이어서 approve 하겠습니다 확인 부탁드려요~~!

2024-08-02 06:06 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        void 방_상태가_FINISH가_아니면_방의_전체_라운드가_종료되지_않은_것이다(RoomStatus status) {
사소한 의견) 메서드명 앞쪽에 "현재 라운드가 전체 라운드와 같아도" 를 붙여주면 더 좋을 것 같아요

2024-08-02 06:12 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +        if (round < currentRound && currentRound - round != ALLOWED_ROUND_GAP) {
https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/78e2bc917bd2a47bac95aa3901cc90df2cfdf431 에서 반영 완료우~

2024-08-02 06:12 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        void 방_상태가_FINISH가_아니면_방의_전체_라운드가_종료되지_않은_것이다(RoomStatus status) {
https://github.com/woowacourse-teams/2024-ddangkong/pull/102/commits/42b53c77f4ec87c69296fc17d0f4cd10b2cf2984 에서 반영 완료우~!

2024-08-02 06:13 UTC, merged