[FEAT] 다음 라운드 넘어가기 API 일부 변경
woowacourse-teams/2024-ddangkong pull request #109
Opened 2024-08-01 11:40 UTC by leegwichan

## Issue Number
Closed #98 

## As-Is

- Sprint 3에 맞추어 '다음 라운드 넘어가기 AP'I 일부 변경 필요

## To-Be

- HTTP method 및 path 변경
  - POST `/api/balances/rooms/{roomId}/content` -> PATCH `/api/balances/rooms/{roomId}/next`
  - ResponseBody를 제거
- 검증
  - 현재 게임이 진행 중인지 검증한다.
- 다음 라운드로 넘어갈 때 아래와 같은 동작을 한다.
  - 마지막 라운드가 아닌 경우, `round += 1`을 한다.
  - 마지막 라운드인 경우, `status == END`로 한다.

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/56557c36-d7f2-415c-9992-216b8d5aebbc)

## (Optional) Additional Description

2024-08-01 14:20 UTC, GIVEN53 requested changes
고생 많았습니다 ~~ 👍🏻 
해당 API에 필요한 기능이 하나 빠진 것 같아서 의견으로 남겨두었어요 확인 부탁드려요!

2024-08-01 14:20 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    public void moveToNextRound(Long roomId) {
의견) 다음 라운드로 넘어갔을 때 다음 라운드의 RoomContent의 투표 제한 시간 설정도 필요할 것 같아요

2024-08-03 05:09 UTC, PgmJun reviewed
고생하셨어요 커찬! 의견이나 질문 몇 가지 남겨두었는데 확인 부탁드립니다!
가장 작업량 많으신데 힘드시면 저한테도 넘겨주세요~!

2024-08-03 05:09 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomContentTest.java
> +            Room room = new Room(5, roomRound, 10_000, RoomStatus.PROGRESS);
질문) 변수로 빼준값과 빼주지 않은 값들의 기준이 궁금합니다!
ex) 변수로 빼준 roomRound, 변수로 빼주지 않은 totalRound

2024-08-03 05:09 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
>          }
질문) 반복문을 사용하는 것보다, 차라리 currentRound와 totalRound가 같은 PROGRESS 상태의 방을 생성하는게 더 효율적이지 않을까? 반복문으로 구현해주신이유가 궁금합니다!

2024-08-03 07:08 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    }
오 좋은 의견이네요! 

질문) 
저는 생성자를 시작 상태로만 허용시켜 놓은 다음에, public method를 통해 특정 상태로 만드는 편이에요. 위와 같은 testable을 위한 생성자도 결국에는 '테스트를 위한 생성자'가 아닌가라는 생각도 들어서요.
위와 같은 이유로 id 값을 포함한 생성자는 만들지 않은 것으로 알고 있어요~ 같은 논리이지만 이든이 제안한 testable한 생성자를 허용하는 이든의 이유가 궁금해요!

반영 하겠습니다)
테스트의 편의성을 위해서 위와 같은 생성자는 좋은 것 같아요! (악용을 막겠다고 불편하게 사용하는 건 좀;;; 타협해야죠;;;) 이번에는 이든 의견 반영하고, 월요일에 가볍게 의견 나눠보죠!

cf)
이 논의와 별개로 다른 크루들의 의견을 물어볼 필요는 있을 것 같아요~ 제가 백엔드 짬통에 넣어두겠습니다.

2024-08-03 07:08 UTC, leegwichan commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    public void moveToNextRound(Long roomId) {
반영 완료했습니다!

2024-08-03 07:08 UTC, leegwichan commented on backend/src/test/java/ddangkong/domain/balance/room/RoomContentTest.java
> +            Room room = new Room(5, roomRound, 10_000, RoomStatus.PROGRESS);
`roomRound`와 `roomContentRound` 값이 다르다는 것을 강조하기 위해 변수로 추출했습니다.
다른 값들은 해당 테스트에서 중요하지 않은 값이라 값을 바로 입력해주었습니다.

2024-08-03 07:08 UTC, leegwichan commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
>          }
[위](https://github.com/woowacourse-teams/2024-ddangkong/pull/109#discussion_r1702460585)에서 언급드렸습니다~ 일단 이든 의견 반영해서 currentRound와 totalRound가 같은 PROGRESS한 방을 만들도록 하겠습니다~

2024-08-03 07:15 UTC, leegwichan commented on backend/src/test/java/ddangkong/domain/balance/room/RoomContentTest.java
> +            roomContent.startRound(currentTime);
이번 이뷰에 반영하도록 하겠습니다~

2024-08-03 07:17 UTC, leegwichan commented
## TODO List

- Path 수정
  - /api/balances/rooms/{roomId}/next -> /api/balances/rooms/{roomId}/next-round
- RoomContent
  - RoomContent에서 BassEntity 제거
  - RoomContent의 testable한 생성자 추가 및 정팩메 추가
  - RoomContent ErrorMessage에 "." 추가
- RoomContentTest
  - RoomContentTest.java 32번째 줄 currentTime 상수값으로 이용하기

2024-08-03 07:27 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    }
반영 감사합니다~!

질문하신 부분 답변드리자면
저는 `Testable한 코드`와 `테스트를 위한 코드`는 조금 별개의 문제로 생각합니다!

만약 테스트를 위해 RoomContent의 id를 조작하기 위해서 `AUTO_INCREMENT` 정책으로 인해 직접 선언해줄 이유도 필요도 없는 id값까지 받는 생성자를 작성한다면 그건 테스트를 위한 코드겠지만,
id를 제외한 모든 값을 받는 생성자는 테스트 외에도 이후 객체 생성 시에 충분히 활용될 수 있는 부분이라고 생각해서 Testable한 코드라고 생각이 됩니다.

실제로 이렇게 관리하여 불필요한 테스트코드(ex. 현재 반복문을 통해 currentRound를 totalRound와 동일하게 맞춰주는 코드)를 제거할 수 있는 이점도 크다고 생각해요~!

그리고 추가적인 맥락 없이 현재 상태와 같이 `roundEndedAt = null`, `usUsed = false` 를 처리해주는 생성자는
이후에 의미를 이해하기 어려운 코드가 되어 가독성을 저해시킬 것 같다는 생각이 들었습니다.
때문에 이름을 가질 수 있는 정적 팩토리 메서드를 제안드린 거구요:)

비슷한 예시로 제가 Room 클래스에 작성해둔 createNewRoom() 정팩메가 있습니다!
실제로 이렇게 처리해둔 덕분에 테스트 코드에서도 간편하게 생성자를 이용하고 있구요~!
```java
public static Room createNewRoom() {
        return new Room(DEFAULT_TOTAL_ROUND, START_ROUND, MAX_TIME_LIMIT_MSEC, RoomStatus.READY, Category.EXAMPLE);
    }

public Room(int totalRound, int currentRound, int timeLimit, RoomStatus status, Category category) {
        this.totalRound = totalRound;
        this.currentRound = currentRound;
        this.timeLimit = timeLimit;
        this.status = status;
        this.category = category;
}
```
충분히 답변이 되었을까요?

2024-08-03 07:30 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomContentTest.java
> +            Room room = new Room(5, roomRound, 10_000, RoomStatus.PROGRESS);
전부 변수화하여 관리하는 것이 아닌, 사용되는 주요 값만 강조하는 느낌이 들어 저는 좋은 것 같습니다~

2024-08-03 08:22 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    }
> id를 제외한 모든 값을 받는 생성자는 테스트 외에도 이후 객체 생성 시에 충분히 활용될 수 있는 부분이라고 생각해서 Testable한 코드라고 생각이 됩니다.

저도 이 부분에는 동의하지만, 오히려 악용될 여지를 열어주는 것이 아닌가 싶습니다.
기본적으로 "방이 생성되면 시작 상태로 되어야 한다"고 생각했거든요. 그리고 비즈니스 로직에서 중단 단계의 방을 생성해서 저장 할 수도 있어서... 의견을 내보았습니다.

2024-08-03 08:23 UTC, useon commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    @PatchMapping("/balances/rooms/{roomId}/next")
ㅋㅋㅋㅋ 프론트 담당자 썬데이 확인했습니다 푸하하 ^. ^~~~~~~ ✨

2024-08-03 12:38 UTC, jhon3242 approved these changes
LGTM 커찬 수고했어~~ 근데 ts 가 수정되어 있더라고요..? 확인부탁드려요~

2024-08-03 12:38 UTC, jhon3242 commented on frontend/src/components/common/Modal/Modal.styled.ts
..롸??

2024-08-03 12:40 UTC, leegwichan commented on frontend/src/components/common/Modal/Modal.styled.ts
이거 머지 커밋 때문에 딸려 들어갔음... (내가 기능 구현하는 동안에 Merge된 파일들 입니다.)

2024-08-03 13:51 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    }
말씀하신 부분도 타당한게 원래 그래서 정팩메를 사용할때 기존 매개변수를 받는 생성자는 private로 접근 제어를 걸어주더라구요. (지정해놓은 하나만 쓰라고)

근데 아무래도 그렇게 사용하기에는 테스트코드 작성에 값을 테스트를 위한 값으로 맞추기 위한 불필요한 로직이 추가되는 등 문제가 생겨서 이정도라면 열어주는 것도 괜찮을거 같다고 생각합니다..
현재 이 생성자로 인해서 발생하는 치명적인 문제는 없기도 하구요.

아니면 생성자를 private로 잠그고,
리플렉션을 사용해서 필드값을 원하는 값으로 꽂아주는 로직을 해당 도메인의 Fixture 관리 객체 로직에 담아도 괜찮을 거 같네요~!

2024-08-03 15:49 UTC, GIVEN53 reviewed
의견 반영 감사해요 👍🏻
질문 몇 개 남겼습니다 확인 부탁드려용~

2024-08-03 15:49 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    public static RoomContent createNewRoom(Room room, BalanceContent balanceContent, int round) {
사소한 의견) 
```suggestion
    public static RoomContent createNewRoomContent(Room room, BalanceContent balanceContent, int round) {
```

질문)
[게임 시작 API PR](https://github.com/woowacourse-teams/2024-ddangkong/pull/122/files#diff-d332bcf8aaa7431a1988b2d311c2404ae84f31b9796bc9ff4c88071d0e3da89a)에 있는 `createList()`와 쓰임이 다른가요?

2024-08-03 15:49 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +        if (room.isGameProgress() && isDifferentToRoomRound()) {
질문)
1. `RoomService.moveToNextRound()`에서 `room.isGameProgress()`가 true일 때 해당 메서드를 호출하고 있는데 여기서 추가로 검증하는 이유가 있을까요?
2. 지금 `startRound()`를 사용하고 있는 로직에서는 Room 객체 로드 후 RoomContent를 조회해서 괜찮지만, 다른 로직에서 Room 로드 없이 RoomContent를 사용하면 추가 쿼리가 발생할 것 같아요
RoomContent 내부에서 Room을 사용하는 이유가 궁금해요!
Room의 도메인 정책이 RoomContent에 녹아있는데 RoomContent는 이를 알 필요없을 것 같고, 각 도메인 정책을 연결하는 것은 business layer의 역할이 아닐까 생각합니다 커찬은 어떻게 생각하시나요??

2024-08-03 15:49 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    public void startRound(LocalDateTime currentTime) {
의견)
라운드의 시작은 Room과 관련한 것이라서 RoomContent에서 시작을 분리할 필요가 있어보여요
외부에서 메서드명만 봤을 때 어떤 책임을 수행하는지 감이 잘 안오더라구요!
`updateRoundEndedAt()`등과 같이 수정하면 어떨까요? 이건 하나의 예시일 뿐 이대로 수정하지 않아도 됩니다

2024-08-04 06:58 UTC, PgmJun approved these changes
제 approve 왜 풀려있죠...??? 다시 드립니다

2024-08-04 10:59 UTC, leegwichan reviewed
### TODO List

- RoomContent의 정팩메를 생성자를 사용하도록 변경
- RoomContent의 `startRound()` 메서드 이름 바꾸기

### c.f.

코멘트 하나 안달았는데, 제가 지금 피곤해서 답변이 안 나오네요. 월요일에 만나서 답변하겠습니다. (다른 팀원들과 의논해봐도 좋겠네요)

2024-08-04 10:59 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    public static RoomContent createNewRoom(Room room, BalanceContent balanceContent, int round) {
애초에 위 정팩메가 테스트에 사용하네요~ 그냥 생성자를 public 하게 사용하도록 바꿀께요~

2024-08-04 10:59 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    public void startRound(LocalDateTime currentTime) {
`updateRoundEndedAt()`만 쓰기에는 update 하는 기능 외에 다른 기능도 있는 것 같아요! (검증)
조금더 추상적이지만 `startRound`보다는 구체적인 메서드 이름이 필요하겠네요.

추천 받습니다~ (저도 조금 더 생각해보고 반영해볼께요~)

2024-08-04 12:08 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    public void startRound(LocalDateTime currentTime) {
개인적으로는 단순 setter가 아니기도 하고
`roundEndedAt`을 수정하기 위해 항상 검증해야하는 부분이라면 프린이 추천한 이름으로 가도 괜찮을 것 같은데요??

2024-08-05 10:24 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +        if (room.isGameProgress() && isDifferentToRoomRound()) {
[회의 내용](https://www.notion.so/ghenmaru/Sprint-3-2-86cad757883f4f52ab2e571901ac93a2) 반영해서 `RoomContent` 내의 `Room`과의 검증 로직은 서비스 레이어로 이동하겠습니다~

2024-08-05 10:53 UTC, GIVEN53 approved these changes
의견하나 남겨두었어요 확인부탁드려용
미리 approve하겠습니다

2024-08-05 10:53 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +        int afterSec = (room.getTimeLimit() + DELAY_MSEC) / 1_000;
의견)
timeLimit은 파라미터로 받는게 좋을 것 같습니다
LazyLoading 관련 이슈

2024-08-05 11:47 UTC, merged