[FEAT] 주제, 선택시 조회 시 방 상태 검증 추가 및 응답값에 제한시간 추가
woowacourse-teams/2024-ddangkong pull request #119
Opened 2024-08-03 07:08 UTC by jhon3242

## Issue Number
#113 

## As-Is

3차 데모데이 P1에 맞게 주제, 선택지 조회 API 로직을 수정해야한다.

## To-Be

- API 호출 시, 방 상태가 PROGRESS인지 검증하는 작업이 추가된다.
- response에 timeLimit 를 추가로 보내준다.

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
<img width="614" alt="image" src="https://github.com/user-attachments/assets/43c146f9-e93b-47b4-8fb0-fac9ec18373b">

## (Optional) Additional Description

2024-08-03 16:33 UTC, GIVEN53 reviewed
굿뽀이 ~~~
몇 가지 의견 남겼습니다 확인 부탁드려요!

2024-08-03 16:33 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private RoomContent findCurrentRoomContent(Room room) {
의견)
isUsed 검증도 필요할 것 같습니당

2024-08-03 16:33 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
> +        void 방의_상태가_진행중이_아닌_경우_예외를_던진다() {
의견)
하나의 테스트 케이스에서 두 개의 경우를 테스트하고 있네요 분리하는건 어떨까요?
https://tecoble.techcourse.co.kr/post/2020-04-24-one-test-must-check-one-scenario/
한 번 읽어보면 좋을 것 같아요!

Fixture가 구현되면 `@ParameterizedTest`로 status를 다르게 사용해볼 수 있겠네용

2024-08-04 02:25 UTC, leegwichan requested changes
타칸 주말에도 캠퍼스 나와서 고생 많았어~
리뷰 반영하고 디코로 멘션해줘~

2024-08-04 02:25 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentResponse.java
> +                roomContent.getRoom().getTimeLimit(),
RoomContent에 `getTimeLimit()` 만들어주세요~

2024-08-04 02:25 UTC, leegwichan commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private RoomContent findCurrentRoomContent(Room room) {
`roomContentRepository.findByRoomAndRoundAndIsUsed(room, room.getCurrentRound(), true)` 형식으로요~

2024-08-04 02:25 UTC, leegwichan commented on backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
> +        }
제안)
```java
        @ParameterizedTest
        @ValueSource(longs = {READY_ROOM_ID, FINISHED_ROOM_ID})
        void 방의_상태가_진행중이_아닌_경우_예외를_던진다(Long roomId) {
            // when & then
            () -> assertThatThrownBy(() -> balanceContentService.findRecentBalanceContent(roomId))
                    .isInstanceOf(BadRequestException.class)
                    .hasMessage("해당 방은 게임을 진행하고 있지 않습니다.");
        }
```

2024-08-04 05:05 UTC, jhon3242 reviewed
리뷰 반영했습니다~~ 다시한번 확인 부탁드릴게요!

2024-08-04 05:05 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentResponse.java
> +                roomContent.getRoom().getTimeLimit(),
이 부분을 고려하긴 했었는데 roomContent 를 통해서 timeLimit 를 가져오는 메서드가 있는게 어색하다고 느껴졌어요.(제한 시간은 방 컨텐츠의 책임이 아니니까요)

비즈니스 로직상 필요한 부분이 있다면 커찬의 의견대로 메서드를 추가할 것 같은데 해당 부분은 뷰에서만 활용하기 때문에 디미터법칙을 고려할 사항이 아니라고 생각해서 위와 같이 해두었습니다!

2024-08-04 05:49 UTC, GIVEN53 approved these changes
빠른 반영 👍🏻 LGTM~~!

2024-08-04 11:47 UTC, PgmJun requested changes
고생하셨습니다 타칸!! 중요한 의견을 남겨두었는데 확인 부탁드립니다!
타칸뿐만 아니라 @leegwichan @GIVEN53 전부 확인해주셔야할듯요!

2024-08-04 11:47 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private Room findProgessingRoom(Long roomId) {
의견) Progressing인데 Progessing으로 오타난 것 같아요!
그리고 roomId를 통해 직접 특정 방을 지정하여 찾아오는데, `findProgressingRoom`이라는 네이밍은 조금 어색하지 않은가라는 생각이 드네요.. 해당 네이밍은 모든 방 중에 status가 Progress상태인 모든 room을 찾아오는 메서드라는 의미일 것 같아요..

차라리 Room 엔티티가 status를 가지고 있으니
`roomRepository.findByIdAndStatus(roomId, RoomStatus.PROGRESS)` 로 찾아오는 것은 어떠신가요? 메서드 분리를 할 필요도 없어질 것 같아요!

2024-08-04 11:47 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private RoomContent findCurrentRoomContent(Room room) {
@leegwichan 
현재 `isUsed`를 true로 만들어주는 시점이 어디인가요??

repository 메서드 매개변수에 isUsed를 true로 보내라는 말씀을 해주셔서,
`다음 라운드로 넘어가기 API`에서 다음 라운드 질문을 Return해주니, 그때 isUsed를 true로 바꿀거라고 기대했는데 코드를 아무리 찾아도 `isUsed`를 `true`로 만들어주는 부분이 없습니다...!
확인부탁드려도 될까요??

![image](https://github.com/user-attachments/assets/9052438b-b18a-4f5c-acaf-0d253f1c6355)

2024-08-04 11:47 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private RoomContent findCurrentRoomContent(Room room) {
![image](https://github.com/user-attachments/assets/c759525e-47af-45b8-a2ff-8341c22b579f)

테스트도 해봤는데 다음라운드 이동에서 isUsed를 true로 만들어주는 부분이 없습니다..!!

2024-08-04 11:47 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private RoomContent findCurrentRoomContent(Room room) {
@jhon3242 그래서인지 타칸도 isUsed를 false로 처리해주셨는데
다음 라운드 넘어갈 때 투표 종료 시간까지 정해주니, 그때 true로 바뀌는 게 맞지 않나요??

2024-08-04 11:47 UTC, PgmJun commented on backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
> +                    30_000, // TODO sec 단위로 수정
감사) 투두 넘 잘남겨 주셔서 감사해요~!

2024-08-04 11:47 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
>          private static final Long NOT_EXIST_ROOM_ID = 99999999L;
사소한 의견) 해당 값도 괜찮긴 하지만, 아예 생성될 수 없는 값인 0 이나 -1 같은 숫자를 사용하는 것도 괜찮을 것 같아요 !

2024-08-04 11:47 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
> +        void 방의_준비_상태인_경우_예외를_던진다() {
질문) 밑에는 같은 문맥인데 방'이'_~~ 로 이어지지만 해당 메서드는 방'의'로 시작되네요 혹시 오타인가요??

2024-08-04 11:47 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
> +                    .isInstanceOf(BadRequestException.class)
의견) 프린이 하던 방식이라 괜찮아서 제가 따라하고 있는 방식인데요!
`isExactlyInstanceOf`로 잡아주는게 더 확실한 것 같기도 해요~!
지금은 BadRequestException은 딱 하나로 끝이지만, 도메인 객체 내부까지 BadRequest라는 응답에 관련된 정보가 노출되고 있어서 이후에 분명히 개선되어야할 부분일거에요.

그래서 지금부터 정확하게 잡지 않으면 이후에 하나하나 찾아서 검증로직을 고치기가 힘들 것 같다는 생각이 드네요 🥲

예를 들어서 만약 이후에 도메인 예외가 `BadRequestException`의 자식 예외로 관리되게 된다면
이 코드는 `BadRequestException`의 하위 예외를 모두 잡기 때문에 특정 예외가 발생한 것이 맞는지 정확히 검증하기에는 어려운 코드라고 봐요!

하지만 지금 `isExactlyInstanceOf`로 검증한다면 이후에 예외에 변화가 생겼을 때
터지는 테이스 케이스를 확인해서 손쉽게 검증 로직을 고칠 수 있을거에요.

물론 아예 다른 예외로 관리될 수도 있겠지만 어떻게 될 지 모르니
지금부터 `isExactlyInstanceOf`로 처리하는 것이 좋을 것 같아요!
그렇게 처리하는데 드는 비용도 전혀 크지 않구요!

타칸은 어떻게 생각하시나요?

2024-08-05 10:37 UTC, jhon3242 reviewed
든든 리뷰 반영했어요~ 확인 부탁드려요~

2024-08-05 10:37 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private Room findProgessingRoom(Long roomId) {
저도 그 부분에 대해서 동의합니다. 적절한 네이밍이 떠오르지 않아 우선 findProgesssingRoom이라고 했던 것 같아요. 두 가지 작업을 하나의 메서드에서 처리하려다보니 메서드 네이밍이 애매해지는 것 같아요. 검증 로직만 따로 분리하는 방식으로 바꿔볼게요!

2024-08-05 10:37 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private RoomContent findCurrentRoomContent(Room room) {
해결완료~

2024-08-05 10:37 UTC, jhon3242 commented on backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
> +        void 방의_준비_상태인_경우_예외를_던진다() {
넵 오타네요ㅎㅎ;; 꼼꼼한 리뷰 감사합니다!

2024-08-05 10:37 UTC, jhon3242 commented on backend/src/test/java/ddangkong/service/balance/content/BalanceContentServiceTest.java
> +                    .isInstanceOf(BadRequestException.class)
이든의 의견에 납득이 되는 것 같아요. 어떤 예외인지 명확하게 확인해줘야 우리가 의도한 예외가 발생한 것인지 파악할 수 있으니까요! 바꿔볼게요!

2024-08-05 10:59 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/content/BalanceContentService.java
> +    private RoomContent findCurrentRoomContent(Room room) {
결론: 시간이 없으니 우선은 모든 라운드가 종료되었을 때 isUsed를 모든 roomContent의 isUsed=true 변경 로직 수행.
이후에 isUsed 변경을 어디서 해줄지 다시 고민

2024-08-05 11:01 UTC, PgmJun approved these changes
고생하셨습니다 타칸! approve 드립니다 LGTM!

2024-08-05 11:22 UTC, leegwichan approved these changes
Approve 드리겠습니다...!

2024-08-05 11:33 UTC, merged