[FEAT] 밸런스 게임 시작 API 구현
woowacourse-teams/2024-ddangkong pull request #122
Opened 2024-08-03 08:47 UTC by leegwichan

## Issue Number
Closed #99 

## As-Is

- 게임 시작 API 필요

## To-Be

- Room의 `status = PROGRESS`로 바꿈
- `RoomContent`를 중복 없이 totalRound 갯수만큼 저장한다.
  - 저장 시의 BalanceContent는 랜덤으로 선택된다.
- 첫 `RoomContent`의 라운드를 시작한다.

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/a012a920-f6da-4427-a1fd-cac1ad27c4a2)

## (Optional) Additional Description

2024-08-03 13:45 UTC, jhon3242 requested changes
커찬 수고했어요~ 몇가지 의견 커멘트로 남겼는데 확인 부탁드릴게요 :)

2024-08-03 13:45 UTC, jhon3242 commented on backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
> +    }
의견) 이러면 1부터 totalRound 개수 만큼만 셔플이 될 것 같아요! 
다음과 같이 수정해주면 좋을 것 같아요!
추가적으로 findByIdIn 이 자동으로 오름차순으로 정렬되는 것 같아서 이 결과도 셔플해주면 더 좋지 않을까 생각해서 추가해봤어요!

```suggestion
    default List<BalanceContent> findByRandom(int count) {
        List<Long> ids = LongStream.rangeClosed(1, count()).boxed().collect(toList());
        if (ids.size() < count) {
            throw new InternalServerException("질문이 라운드만큼 존재하지 않습니다.");
        }

        Collections.shuffle(ids);
        List<Long> candidateIds = ids.subList(0, count);
        List<BalanceContent> result = findByIdIn(candidateIds);
        Collections.shuffle(result);
        return result;
    }
```

2024-08-03 13:45 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    }
의견) 게임을 시작하는 API는 PATCH로 얘기했던 것 같아요~  
(혹시 PATCH에서 POST 변경되었다면 API 문서도 같이 수정해주시면 감사하겠습니다!)

2024-08-03 13:45 UTC, jhon3242 commented on backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
> +            mockMvc.perform(post(ENDPOINT, roomId))
의견) 만약 PATCH 가 맞다면 이 부분도 수정해야할 것 같아요!

2024-08-03 16:17 UTC, GIVEN53 reviewed
굿뽀이 ~ 👍🏻
몇 가지 코멘트 확인 부탁드립니당

2024-08-03 16:17 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
> +    default List<BalanceContent> findByRandom(int count) {
의견)
랜덤 추출하는 것은 서비스에서 처리하는게 맞는 책임이지 않을까 생각합니다

이미 사용된 컨텐츠 제외는 차치하고, 1 ~ n개의 컨텐츠 id중에서 Room의 totalRound 수 만큼 id 랜덤 선택인거죠??
\+ 중간 id의 컨텐츠가 삭제되면 원하는 개수의 컨텐츠를 얻지 못할 수도 있을 것 같아요
BalanceContent가 몇 십만개가 되진 않으니(많아야 n백개로 예상) `findAll()`로 조회 후 진행하고(이미 사용된 컨텐츠 중복 제거도 추가한다면 notIn까지) 추후 병목이 생길 때 개선 방향을 고려하면 어떨까요?

2024-08-03 16:17 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +    public static List<RoomContent> createList(Room room, List<BalanceContent> balanceContents) {
의견) 
```suggestion
    public static List<RoomContent> createRoomContents(Room room, List<BalanceContent> balanceContents) {
```
타입은 언제든지 변경될 수 있으니 복수형으로 나타내는 것이 좋을 것 같아요

2024-08-03 16:17 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        @CsvSource({"PROGRESS", "FINISH"})
사소한 의견)
`@EnumSource`로 대체해도 좋을 듯 하네요!

2024-08-04 13:14 UTC, PgmJun reviewed
고생하셨습니다 커찬 !!! 의견 남겨두었으니 확인 부탁드려요!!!

2024-08-04 13:14 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        @CsvSource({"PROGRESS", "FINISH"})
@leegwichan 이 이전에 `@CsvSource`는 부가적인 코드없이
names에 입력된 값이 매개변수에 있는 타입으로 바로 변환된다고 해서 CsvSource를 사용한다고 말했던 기억이 나는데
찾아보니 `@EnumSource`는 names에 작성해준 문자열이 매개변수에 존재하는 Enum타입의 값이 아니라면 컴파일 시점에서 잡아줘서 저도 EnumSource를 추천드립니다!

![image](https://github.com/user-attachments/assets/176b8a9f-786a-48dd-8b4e-ed8dfaf3e802)

2024-08-04 13:14 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +        @CsvSource({"PROGRESS", "FINISH"})
```java
@EnumSource(mode = Mode.EXCLUDE, names = {"READY"})
void 게임이_이미_시작했다면_예외를_던진다(RoomStatus status) {
```
로 처리할 수 있겠네요!

2024-08-04 13:14 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +        }
질문) 하나의 동작에서 발생하는 작업인데 두 개의 테스트로 분리해주신 이유가 궁금합니다!

2024-08-05 01:52 UTC, leegwichan reviewed
### TODO List

- Controller 변경
  - HTTP Method를 Post에서 Patch로 변경
- RoomContent
  - 정팩메 이름 수정 (-> createRoomContents)
- Test
  - RoomTest의 `@CsvSource`를 `@EnumSource`로 변경
- 랜덤 조회 기능
  - 랜덤 추출 기능 서비스로 이동
  - 카테고리 기반 추출 (Room의 카테고리 이용)
  - id 조회 대신 객체 조회
  - DB에서 조회 후 랜덤 Sorting

## C.F.

입장이 다른 의견들에는 코멘트 남겨두었습니다~ 바로 할 수 있는 부분부터 작업 들어가고 나머지는 나중에 의논하고 반영하도록 하겠습니다~

2024-08-05 01:52 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
> +    default List<BalanceContent> findByRandom(int count) {
프린, 이든 의견 반영햇 수정하겠습니다~

2024-08-05 01:52 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/content/BalanceContentRepository.java
> +    }
오! 타칸 놓친 부분 알려줘서 고마워요~ 리뷰한 것 바탕으로 수정해볼꼐요~

2024-08-05 01:52 UTC, leegwichan commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +        }
하나의 단위 테스트에 한 가지 작업만을 검증하는 것이 좋다고 생각합니다.
하나의 메서드에서 두 개 이상의 행위를 할 때, 단위 테스트를 나눠 놓아야 어느 행동이 정상적으로 처리되지 않았는지 빠르게 파악할 수 있기 때문입니다.

2024-08-05 01:52 UTC, leegwichan commented on backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
> +                    .statusCode(204);
그... 204 No Content에서 Body에 값이 없어서 No Content라고 하더라구요...
그래서 204로 했습니다. 위에서 타칸이 언급했듯이 Patch로 바꾸도록 하겠습니다~

참고 자료)
- https://developer.mozilla.org/ko/docs/Web/HTTP/Status/204
- https://velog.io/@server30sopt/204-NOCONTENT%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%84%EC%8B%9C%EB%82%98%EC%9A%94

2024-08-05 01:52 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomStatus.java
> +
게임 진행이 끝난 이후, (프린이 작업 중인) "게임 종료 후 방 초기화 API"를 통해 다시 status를 READY로 바꿔줘서 큰 상관 없을 것 같아요.
제가 타칸의 의도를 잘 파악한 것이 맞을까요?

2024-08-05 01:52 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +                .toList();
> 저는 room의 totalRound만큼 RoomContent를 생성하는 로직은
RoomContent의 도메인 로직 보다는 startGame() 메서드의 비즈니스 로직에 가깝지 않나 싶습니다.

- 해당 정적 팩토리 메서드의 의도는 Room과 BalanceContent 여러 개를 통해 해당하는 RoomContent를 해당 개수 만큼 만든다는 데 의의가 있었습니다. 그래서 `room.getTotalRound()`가 아니라, `balanceContents.size()`를 통해서 개수를 확인합니다.
- 추가적으로 애초에 `room.getTotalRound()` 만큼 `List<BalanceContent>`를 조회해서 사용하기 떄문에 따로 검증 과정은 들어가지 않아도 된다고 생각합니다.

> 서버 회의시간에 얘기 나누었던 파사드 패턴을 적용할 때 처리해야할 부분같습니다!

저번에 도입하려고 했는데, 얻는 것보다 잃는 것이 많을 것 같다는 생각이 들었습니다. (퍼사드 계층에서는 DTO를 반환한다고 하면 하위 서비스 계층에서는 Entity를 반환해야 하는가?, 복잡도가 올라가는 것 만큼 코드가 줄어드는가?, ...) 해당 부분은 회의 시간에 더 다뤄보도록 하죠!

> 개인적인 의견이지만 설계를 잘 수행해낸다는 가정하에 Service 참조를 허용하는 것도 고민해보면 좋을 듯 하네요!

이거는 경험담으로 풀어드릴 수 있습니다. Service가 다른 Service를 참조하기 시작하면 정말 골치가 아파질 수 있습니다. 한 서비스가 다른 서비스를 참조하고, 또 레포지토리도 참조하고, ... (으아아아아아악!)
그래서 나중에는 다른 참조가 필요하면 기도를 하게 됩니다. (제발 순환 참조 일어나지 마라...)

결론은 일단 오늘 오후에 같이 의견 나눠 보시죠! (제발 오늘은 머지하고 싶어요 ㅠ_ㅠ)

2024-08-05 02:35 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +                .toList();
> 추가적으로 애초에room.getTotalRound() 만큼 List<BalanceContent>를 조회해서 사용하기 떄문에 따로 검증 과정은 들어가지 않아도 된다고 생각합니다.

어느정도 맞는 말씀이지만 그 검증은 커찬이 구현해주신 이번 서비스 메서드에서만 유효합니다.

도메인에 존재하는 해당 로직은
그 서비스 뿐만 아니라 도메인 객체를 생성한 모든곳에서 접근 가능하기 때문에 도메인 로직으로 두는 것이 문제가 될 수 있을 것 같다는 의견입니다.

또한 balanceContent의 개수만큼
RoomContent를 생성하는 것은 게임 시작이라는 행위에 내포된 비즈니스 로직인데 도메인에 존재하고 있으니 계속 어색함 느껴져서요🤔

차라리List<BalanceContent>가 아닌
BalanceContent, Room, round를 입력받아서 RoomContent내에서 생성하게 하고 서비스에서 반복문을 통해 그 값들을 입력해주는 것은 어떨까요?

2024-08-05 02:38 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +                .toList();
> 이거는 경험담으로 풀어드릴 수 있습니다. Service가 다른 Service를 참조하기 시작하면 정말 골치가 아파질 수 있습니다. 한 서비스가 다른 서비스를 참조하고, 또 레포지토리도 참조하고, ... (으아아아아아악!)
그래서 나중에는 다른 참조가 필요하면 기도를 하게 됩니다. (제발 순환 참조 일어나지 마라...)

저도 순환참조 경험이 있어서 그
고통을 알지요 ㅋㅋㅎㅋㅋ

그리고 파사드 패턴에서 DTO 관련 고민도 많이 해보신 것 같은데 요 부분은 DTO 개수가 하나의  파사드 메서드 당 최소 2개씩 생성되어 늘어난다는 것이 가장 문제이겟네요..

이 부분에 대해선 컨트롤러에서 여러 개의 서비스를 호출하는 방법도 있습니다. 같이 고민해보죠!

2024-08-05 02:43 UTC, PgmJun commented on backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
> +                    .statusCode(204);
제 질문의 의도는 post에서 하나의 값이라도 생성이 되었다면 201로 Response 해야하기 때문에 patch 204 또는 post 201 둘 중 하나로 설정해야할 것 같은데 두 개가 섞여있어서 드린 질문이었습니다 ㅎㅎ

patch로 변경하셨다면 문제는 없을 것 같습니다:)

https://httpwg.org/specs/rfc9110.html#POST

2024-08-05 10:32 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +                .toList();
[대화의 결론](https://www.notion.so/ghenmaru/Sprint-3-2-86cad757883f4f52ab2e571901ac93a2?pvs=4#a37e4308111b49819388b4a3abeba304)

2024-08-05 10:48 UTC, GIVEN53 approved these changes
커칭~~ 미리 approve 넣을게여

2024-08-05 11:55 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/RoomContent.java
> +                .toList();
서비스 계층으로 옮기도록 하겠습니다~

2024-08-05 13:16 UTC, jhon3242 approved these changes
리뷰 잘 반영해주었네요~~ 수고했어요 커찬!
이젠 제발 머지하자!

2024-08-05 13:42 UTC, PgmJun approved these changes
넘고생많았오유 커찬.... 커칭..ㅠㅠ approve!!

2024-08-06 01:00 UTC, merged