[FEAT] 대기실에서 초대하기 버튼을 누르면 초대하기 링크를 포함한 모달이 뜨는 기능
woowacourse-teams/2024-ddangkong pull request #150
Opened 2024-08-06 16:59 UTC by useon

## Issue Number
close #132 

## As-Is

멀티 플레이를 위해 링크 또는 QR을 통해 접속 링크를 공유하도록 하는 기능이 필요함.
## To-Be

- [x] 초대하기 모달 UI 구현
- [x] 해당 방의 초대 링크를 가져와서 링크 영역에 띄우는 기능
- [x] 클릭 시 복사가 되는 기능
- [x] 복사 되었다고 사용자에게 알리는 기능
- [x] 대기실에서 초대하기를 누르면 초대 하기 모달이 뜨는 기능
- [x] 초대 하기 모달 스토리북 작성
- [x] jest 테스트 시 미디어 모킹이 되지 않는 문제 해결

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

https://github.com/user-attachments/assets/d4a29b72-2c52-4def-a389-ed0ea854ef78

## (Optional) Additional Description
- QR은 P2라 추후에 추가하겠습니다 🙌
- test 작성하다가 계속 실패해서 일단 추후에 올려보도록 하겠습니다 🥹

2024-08-07 04:03 UTC, rbgksqkr requested changes
썬데이 모달 천재 고생많았습니다,,,공통 모달을 활용한 부분이라 공통 모달을 건드리게 되는데 이야기했던대로 구현하면 더 사용하기 편하고 유연한 모달이 될 것 같아용 굿굿굿

2024-08-07 04:03 UTC, rbgksqkr commented on frontend/src/components/common/Toast/Toast.styled.ts
> +  transition: opacity 0.3s ease-in-out;
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
animation을 사용하는데 transform은 translate하고 transition은 opacity에 줘서 어떤 효과가 있는지 궁금합니다!!

2024-08-07 04:03 UTC, rbgksqkr commented on frontend/src/mocks/handlers/roomHandler.ts
> +export const roomHandler = [http.get(MOCK_API_URL.roomMembers, getRoomMemberHandler)];
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
msw 모킹 아주 좋아요 👍👍👍

2024-08-07 04:38 UTC, novice0840 reviewed
고생 많았어요 썬데이~~~
피드백 할 내용이 많지는 않았던 것 같아요. 코멘트 남깁니다!!!!

2024-08-07 04:38 UTC, novice0840 commented on frontend/src/components/common/Toast/Toast.tsx
> +  return ReactDOM.createPortal(toastContent, document.body);
# 🙏 제안 🙏
createPortal의 return 타입을 알기 어려울 것 같은데 반환 타입을 함수에 적는 것은 어떤가요?

2024-08-07 04:38 UTC, novice0840 commented on frontend/src/components/common/Toast/Toast.styled.ts
> +`;
# 💭 질문 💭
Toast가 위에서 아래로 내려오는 애니메이션인가요?

2024-08-07 04:38 UTC, novice0840 commented on frontend/src/components/common/Toast/Toast.styled.ts
> +`;
# 🌸 칭찬 🌸
Toast 굿 칭찬해~~~

2024-08-08 02:22 UTC, novice0840 approved these changes
제안된 변경사항들이 있긴한데 엄청 중요한 부분들은 아니라서 approve하겠습니다~~ 공통 모달 만드느라 고생 많았어요~~~

2024-08-08 04:26 UTC, useon reviewed
말우 폼에 ~ ! ! 리뷰 사항에 대해 반영하고 코멘트를 달았습니다 확인 부탁드려요 ✨ !!!!!!!! 반영 못한 부분은 추후 리팩토링 해 보도록 하겠습니다 😆🙌

2024-08-08 04:27 UTC, leegwichan approved these changes
아, 좋네요. Approve 드리겠습니다.

2024-08-08 04:50 UTC, rbgksqkr commented on frontend/src/components/common/InviteModal/useClipBoard.tsx
> +  };
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
엇 제 생각에는 await 거는 게 더 맞다고 생각합니다 !!
clipboard 에 복사된 작업이 완료되는 것을 기다린 후 copy state를 변환해야 안전하다고 생각했습니다!
물론 해피케이스를 생각하면 작업이 끝나기 전까지 기다릴 필요가 있나 생각할 수 있는데, 복사가 느리게 된다고 가정하면 await을 걸어 완료된 후 넘어가는 게 어떨까요??

2024-08-08 04:52 UTC, rbgksqkr approved these changes
고생 천재 만재 고생 혼자 PR 싹쓸이해감 미쳐따 레전드 프론트엔드 개발자!!!!!! 감사합니다!

2024-08-08 04:56 UTC, useon commented on frontend/src/components/common/InviteModal/useClipBoard.tsx
> +  };
오프라인 토론에서 원래 상태로 돌리기로 합의하고 수정했습니다 🚀✨😆

2024-08-08 05:03 UTC, merged