Test/#152
woowacourse-teams/2024-ddangkong pull request #182
Opened 2024-08-15 17:56 UTC by novice0840

## Issue Number

#152 

## As-Is

기능 구현에 급급해서 테스트 코드가 부실했던 상황

## To-Be

useMakeOrEnterRoom
useGameStart
useGetRoomInfo

이렇게 3개의 hook에 대한 테스트가 추가되었다. 

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

![image](https://github.com/user-attachments/assets/454383c0-2965-4caa-8a3d-e7f3080c781d)

## (Optional) Additional Description

mocking이 너무 많아 실질적으로 테스트하는 부분이 적어 테스트가 추가된 것은 좋으나 효용성이 있는지에 대한 
의문이 들긴했다.

2024-08-16 02:17 UTC, rbgksqkr requested changes
테스트 코드 작성하느라 고생해써요~~~!~!~!! 테스트 코드를 모킹하느라 고생이 많았을 게 예상이 되네요 ㅎㅎ 근데 팀에서 정했던 테스트 코드 목적과 범위랑 살짝 달랐던 것 같아서 코멘트 살짝 남겨봤습니다!~!

2024-08-16 02:17 UTC, rbgksqkr commented on frontend/src/pages/NicknamePage/hooks/useMakeOrEnterRoom.test.ts
> +    jest.clearAllMocks();
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
jest.config에서 clearMocks:true를 설정해서 clearAllMocks를 별도로 적용하지 않아도 될 것 같아요!

2024-08-16 02:17 UTC, rbgksqkr commented on frontend/src/pages/NicknamePage/hooks/useMakeOrEnterRoom.test.ts
> +    expect(mockEnterRoom).not.toHaveBeenCalled();
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
모든 함수를 모킹해서 이 테스트 코드가 작성이 된 것 같은데, PR에도 작성해준 것처럼 효용을 느끼기 어려운 것 같아요!
아니면 user가 방 생성 버튼을 클릭하고, mutation에서 반환하는 데이터를 확인하는 건 어떨까요??

2024-08-16 02:17 UTC, rbgksqkr commented on frontend/src/pages/NicknamePage/hooks/useMakeOrEnterRoom.test.ts
> +    const { result } = renderHook(() => useMakeOrEnterRoom(), {
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
useMakeOrEnterRoom 훅이 이름부터 두 가지 역할을 한다고 생각이 들었는데 테스트 코드를 보니 더 그게 느껴지네요. 다른 테스트 케이스의 다른 입력값인데 테스트 수행 과정이 같다는 게 어색한 것 같아요 어떻게 생각하시나요??

2024-08-16 02:17 UTC, rbgksqkr commented on frontend/src/pages/ReadyPage/hooks/useGameStart.test.ts
> +}));
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
mutate를 jest로 모킹하는 것보단 현재 msw를 사용하고 있으니까 API 모킹을 msw로 활용해보는 건 어떨까요??

2024-08-16 02:17 UTC, rbgksqkr commented on frontend/src/pages/ReadyPage/hooks/useGameStart.test.ts
> +}));
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
모킹을 야무지게 잘하셨네요 굿굿 근데 recoil로 관리하던 유저 정보를 쿠키로 관리하도록 바뀌면 테스트코드를 다 다시 작성해야할 우려가 있긴 하네용

2024-08-16 02:17 UTC, rbgksqkr commented on frontend/src/pages/ReadyPage/hooks/useGetRoomInfo.test.ts
> +  it('게임이 시작되면 모든 유저는 게임화면으로 이동한다.', async () => {
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
이런 테스트 케이스가 애매하다고 느껴졌는데, 페이지를 이동하는 부분은 cypress의 역할로 양도하는 건 어떨까요? 모킹하느라 힘들었을 것 같은데 테스트 명세에 작성된 "게임화면으로 이동한다"에 비해, 화면으로 이동되는 것을 해당 테스트 코드에서 확인하기 어려운 것 같아요!

2024-08-17 08:22 UTC, useon approved these changes
저도 어제 테스트를 작성하느라 하루 종일 테스트 생각 밖에 안 한 것 같아요. 저도 이번 테스트 작성에 recoil을 모킹했지만, 과연 모킹이 많은 테스트가 좋은 테스트일까 하는 근본적인 고민부터 들었어요 방장 여부에 따른 구현이 다르기 때문에 어쩔 수 없다고 판단했지만요 !🥹 포메도 해당 작업들에 대한 테스트 코드를 작성하면서 많은 고민을 한 것 같네요. 지금 저희가 이제 recoil에서 cookie로 변경이 되면서 테스트 코드도 많이 수정될 것 같은 예감이 .. ^ ^ 따라서 지금 테스트 작업에는 최소한의 리소스를 들이고 P1 기능 개발로 얼른 나아갑시다 .. ! 수고 많았어요 폼에 ^. ^

2024-11-08 17:27 UTC, closed without merging