[FEAT] 라운드 결과에서 방장이 다음 라운드 버튼을 누르면 충분한 대화를 나눴는지 안내 모달을 띄우는 기능
woowacourse-teams/2024-ddangkong pull request #188
Opened 2024-08-16 11:45 UTC by useon

## Issue Number
#168 

## As-Is

유저 테스트를 통해 라운드 결과에서 대화를 많이 나누지 않는다는 문제를 알게 되었다. 
이를 해결하기 위해 **방장이 "다음"버튼을 누르면 대화를 충분히 나눴는지 묻고, "확인"을 누르면 다음 라운드로 넘어갈 수 있는 안내 모달이 뜨는 기능이 필요**했다. 

## To-Be

- [x] 모달에서 자주 사용되는 모달이 열렸는지 닫혔는지 상태, 모달을 여는 함수, 모달을 닫는 함수를 하나의 커스텀 훅으로 분리
- [x] 배열의 요소 중 하나를 랜덤으로 반환하는 유틸 함수 리팩토링
- [x] 방장이 다음 라운드 버튼을 누르면 안내 모달 띄우기
- [x] 안내 모달에서 확인을 누르면 다음 라운드로 넘어가도록 api 연결
- [x] 안내 모달 스토리북 작성
- [x] 라운드 결과 페이지에서 방장 권한에 따른 "다음"버튼 컴포넌트 상태 RTL 작성 

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
- RTL
![image](https://github.com/user-attachments/assets/8195d1d5-5534-45e2-b6d7-d8036edc55fd)
- 화면
https://github.com/user-attachments/assets/7a455b46-b1fb-4246-b31a-0b056b27458b

## (Optional) Additional Description
cypress로 페이지 단위 테스트를 작성할까 고민했지만 🥹
1. 현재 recoil persist를 사용하지 않아 cypress 코드 작성에 리소스가 많이 들어감
2. 이번 스프린트 내 방장 여부에 대해 recoil -> cookie 코드 변경 
의 이유로 라운드 결과 페이지에서 버튼에 대한 RTL과 안내 모달 스토리북으로 해당 기능의 테스트를 작성했습니다 ^. ^!

2024-08-16 17:43 UTC, rbgksqkr reviewed
cypress와 혈투 끝에 다음으로 미루게 된 썬데이,,,,고생하셨습니다,,,, 테스트 코드에 대해 고민이 많았 던 것 같은데 오히려 RTL로 깔끔하게 잘 해결해주셨네용 몇가지 코멘트 남겼으니 확인부탁드려요 !!

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/components/common/Button/Button.styled.ts
> +  background-color: ${disabled ? Theme.color.peanut300 : Theme.color.peanut400};
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
회의 반영 좋네용

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/components/common/Modal/hooks/useModalHandler.ts
> +const useModalHandler = () => {
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
handler 붙이는 걸로 유지했네요 ㅋㅋㅋㅋㅋㅌ 네이밍은 뭔가 취향차이라 참 어렵네용 handler라는 네이밍이 오히려 혼동의 여지가 있을 것 같아 useModal 을 생각하긴 했습니다!  Handler 라는 네이밍이 현재 msw handler에서도 사용되고, 이벤트 핸들러에서도 사용되는데 해당 훅은 다른 handler 느낌은 살짝 어색하다고 느껴지는 것 같긴 합니다,,,포메의 의견 듣고 다수결하는 것도 굿굿 래퍼런스는 작년 기수 팀바팀이랑 refine 첨부합니다:)

https://github.com/woowacourse-teams/2023-team-by-team/tree/develop/frontend/src/components/common/Modal
https://refine.dev/docs/core/hooks/utilities/use-modal/#usage

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +  const renderWithRecoilState = (isMaster: boolean) => {
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
오 이렇게 컴포넌트 하나 만들어서 하는 것도 좋은데용

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      <RecoilRoot
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
customRender 안에 RecoilRoot가 있는데 RecoilRoot를 두번 선언해도 딱히 문제가 없는거겠죠??

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      expect(handleModalOpen).toHaveBeenCalledTimes(1);
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
다음 버튼을 클릭했을 때 모달이 뜨는 사용자 액션 테스트를 잘 작성한 것 같아요! 
모킹 안하고 실제로 모달 뜨는 것까지 확인이 가능할 줄 알았는데, handleModalOpen 을 받기가 어려워보이네용 modal을 버튼 안으로 넣으면 테스트는 될 것 같지만 버튼 안에 넣는 건 좀 그렇긴 하네요 허허 썬데이도 같은 고민을 했을 것 같네욥

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
>            text={isLastRound ? '결과 확인' : '다음'}
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
나머지 다 같고 text만 다른 것 같은데 어떻게 리팩토링해볼 수 있을끼요??

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/pages/NicknamePage/createRandomNickname.ts
> +  const randomNoun = randomPicker(nouns);
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
굿굿굿

2024-08-16 17:43 UTC, rbgksqkr commented on frontend/src/pages/RoundResultPage/createRandomNextRoundMessage.ts
> +    '대화를 끝마쳤다면,\n확인을 눌러 다음 라운드로 이동하세요 :)',
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아이디어 뱅크 천재 만재 썬데이

2024-08-17 03:20 UTC, rbgksqkr commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +  it('방장이 "다음" 버튼을 클릭하면 안내 모달을 여는 함수가 호출된다.', async () => {
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
이건 사소하긴 한데 최근에 본 아티클에선 테스트 명세를 코드 레벨의 구현이 아닌 동작을 설명하듯이 서술하는 게 좋다고 하더라구요! 그래서 "방장이 "다음" 버튼을 클릭하면 다음 라운드 안내 모달을 띄운다." 이런 느낌도 괜찮은 것 같아요 해당 테스트 명세를 바꿔야한다는 아니지만 참고하면 좋을 것 같아 첨부해봅니다:)

<img width="400" alt="image" src="https://github.com/user-attachments/assets/022a5f13-843a-4794-9c7c-b455378d897d">

https://tosspayments-dev.oopy.io/share/books/unit-testing

2024-08-17 05:05 UTC, novice0840 requested changes
코드 확인 후 코드 리뷰 남깁니다. 고생 많았어요~~~

2024-08-17 13:54 UTC, useon commented on frontend/src/components/common/Modal/hooks/useModalHandler.ts
> +const useModalHandler = () => {
ㅋㅋㅋㅋㅋㅋ 아 .. 설득당했다 . . . useModal로 반영하도록하겠심니다 ^ .^

2024-08-17 13:56 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +  const renderWithRecoilState = (isMaster: boolean) => {
중복된 코드를 어떻게 개선하면 좋을까 고민하다가 해당 작업으로 같은 코드를 매번 하나하나 작성하지 않고renderWithRecoilState 함수를 통해 해결할 수 있어서 작성해 보았습니다 ^. ^ ..

2024-08-17 14:17 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      <RecoilRoot
중복으로 작성이 되긴 하지만 이렇게 하지 않으면 customRender를 이용하면서 initializeState 값을 설정할 수 없어서 작성을 하게 되었습니다 ! recoil 공식문서에 따르면 여러 개의 중첩된 RecoilRoot를 사용할 수 있고, 이 경우에는 가장 안 쪽의 RecoilRoot 컴포넌트가 우선순위가 된다고 하네요 ! 
 https://recoiljs.org/ko/docs/api-reference/core/RecoilRoot#%EC%97%AC%EB%9F%AC-recoilroot%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EA%B2%BD%EC%9A%B0
 
지금 떠오르는 방법은 세 가지입니다. 
1) 테스트 코드에서 customRender를 사용하지 않고 wrapper 자체를 다시 작성하는 방법 
2) customRender에 prop를 추가해서 initializeState값으로 전달할 수 있도록 하는 방법 
3) 현재 작성된 방식

마루 생각은 어떤가요 ? ? 🤓

2024-08-17 14:19 UTC, useon commented on frontend/src/pages/RoundResultPage/createRandomNextRoundMessage.ts
> +    '대화를 끝마쳤다면,\n확인을 눌러 다음 라운드로 이동하세요 :)',
사용자에게 어떻게 잘 안내하면 좋을지 멘트 고민이 더 힘들었던 🥹🥹 !! 알아주니 좋으네요 푸하하

2024-08-17 14:21 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +  it('방장이 "다음" 버튼을 클릭하면 안내 모달을 여는 함수가 호출된다.', async () => {
오오 좋아요 !! 저도 이 아티클을 봤는데 좋은 내용이 많더라고요 ! 참고해서 리팩토링할 때 사용자 입장에서 작성이 되도록 수정해볼게요 ✨✨

2024-08-17 14:24 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.tsx
>            text={isLastRound ? '결과 확인' : '다음'}
좋아요 안 그래도 해당 부분의 중복을 해결하면 좋을 것 같다고 생각은 하고 있었습니다 ! ! ! 반영하겠습니다 😉

2024-08-17 14:45 UTC, useon commented on frontend/src/utils/randomPicker.ts
> +export default randomPicker;
저는 지금까지 string 배열로 해당 유틸을 사용하는 경우 밖에 없어서 stirng 배열로 고정을 해두었는데, 확장성을 고려하면 배열에 여러 타입이 들어올 수 있도록 고려하는 것이 좋겠네요 ! unkown 배열보다는 제네릭으로 함수가 호출될 때 타입을 유추할 수 있도록 리팩토링 해 볼까요 ?
이 경우에는 배열의 모든 타입이 같아야 하지만(예를 들어, 배열 내 number타입과 string 타입이 함께 있는 경우 별도의 타입 정의가 필요함) unknown 과 다르게 반환 값이 전달된 배열을 추론하여 같은 타입으로 반환이 된다는 장점이 있어요 ! ! 폼에 생각이 궁금합니다 !
```ts
const randomPicker = <T>(array: T[]): T => {
  return array[Math.floor(Math.random() * array.length)];
};

export default randomPicker;
```

2024-08-17 14:45 UTC, useon commented on frontend/src/utils/randomPicker.ts
> +export default randomPicker;
저는 지금까지 string 배열로 해당 유틸을 사용하는 경우 밖에 없어서 stirng 배열로 고정을 해두었는데, 확장성을 고려하면 배열에 여러 타입이 들어올 수 있도록 고려하는 것이 좋겠네요 ! unkown 배열보다는 제네릭으로 함수가 호출될 때 타입을 유추할 수 있도록 리팩토링 해 볼까요 ?
이 경우에는 배열의 모든 타입이 같아야 하지만(예를 들어, 배열 내 number타입과 string 타입이 함께 있는 경우 별도의 타입 정의가 필요함) unknown 과 다르게 반환 값이 전달된 배열을 추론하여 같은 타입으로 반환이 된다는 장점이 있어요 ! ! 폼에 생각이 궁금합니다 ! 🙌
```ts
const randomPicker = <T>(array: T[]): T => {
  return array[Math.floor(Math.random() * array.length)];
};

export default randomPicker;
```

2024-08-17 14:48 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      expect(handleModalOpen).toHaveBeenCalledTimes(1);
맞아요 .. 모달이 뜨는 것까지 확인하면 좋았겠지만 .. 모달이 다음 버튼에 포함이 된다는 것이 이상하다고 생각했기 때문에 모달은 페이지 단에 위치하게 되었어요 🥹

2024-08-17 15:11 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +  const renderWithRecoilState = (isMaster: boolean) => {
컴포넌트를 렌더링하면서 isMaster 뿐만 아니라 memberInfoState 전체를 다시 set하기 때문에 **해당 함수가 Recoil 상태를 초기화하고 NextButton 컴포넌트를 렌더링하는 작업을 수행한다는 의미**를 담아서 해당 이름으로 작성을 했어요 ! 지금은 파일 내 작성된 모든 테스트의 인자값이 isMaster로 같지만 추후에는 다른 인자를 추가로 받게 될 수도 있다고 생각했어요! 🤓

2024-08-17 15:16 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +  const renderWithRecoilState = (isMaster: boolean) => {
포메의 의견을 반영한다면 renderWithRecoilStateIsMaster 요런식이 될텐데 인자가 늘어나거나 수정될 경우도 있지 않을까요? 컴포넌트를 렌더링하면서 isMaster 뿐만 아니라 memberInfoState 전체를 다시 set하기 때문에 **해당 함수가 Recoil 상태를 초기화하고 NextButton 컴포넌트를 렌더링하는 작업을 수행한다는 의미**를 담아서 해당 이름으로 작성을 했어요 ! 폼에 추천하고 싶은 네이밍 있으시다면 언제든 환영.. 🤓 ! !

2024-08-17 16:41 UTC, rbgksqkr commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      <RecoilRoot
오 공식문서 가져와버리니 바로 이해가 되버렸네요 ㅎㅎ 유강스가 선순환이 되는 것 같아 좋네용
recoil이 없어질 위기지만 만약 유지한다면 2번이 베스트지만 현재 상황에선 현재 방식이 베스트 일 것 같긴 해요!

궁금해서 2번을 트라이 해봤는데 wrapper를 좀 수정해야 가능하더라구요. 되는대로 써보고 이해했는데 원래는 wrapper가 그대로 들어가 있었던 부분에 인자를 넣어야 하는 상황이예요
근데 wrapper 내부에 있는 RecoilRoot에 initializeState를 넣어야 하니까 wrapper에 props를 뚫어야 하는데, React Element를 반환해야 하므로 커링을 걸어 함수를 반환하도록 해야 할 것 같네용 하하
```tsx
const wrapper = ({ children, state }: PropsWithChildren) => {
  return function a () {
    return (
      <QueryClientProvider client={queryClient}>
        <RecoilRoot initializeState={state}>
          <ThemeProvider theme={Theme}>
            <MemoryRouter initialEntries={['/']}>
              <Global styles={GlobalStyle} />
              {children}
            </MemoryRouter>
          </ThemeProvider>
        </RecoilRoot>
      </QueryClientProvider>
    );
  };
};



const customRender = (ui: React.ReactNode, options?: RenderOptions, state) =>
  render(ui, { wrapper: wrapper({children: ui}), ...options });


```

2024-08-17 17:18 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      <RecoilRoot
웁시 ^^ 맞아요 wrapper에 인자를 넣어주어야 해서 코드 수정이 고런 식으로 이루어지네요 .. 코멘트 읽고 바로 코드 작성해 보면서 이해하는 꼼꼼 말우 최고다🥹 일단은 그러면 유지하는 것으로 하겠습니다 🙌🙌 !!

2024-08-20 01:40 UTC, novice0840 commented on frontend/src/utils/randomPicker.ts
> +export default randomPicker;
오 이렇게 보니 제네릭이 더 좋은 것 같네요. 안에 값들의 타입을 모두 일치 시킬 수 있으니

2024-08-20 01:44 UTC, novice0840 commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +  const renderWithRecoilState = (isMaster: boolean) => {
음, 썬데이말도 일리가 있는 것 같네요. 전 썬데이 의견 괜찮은 것 같습니다.

2024-08-20 01:44 UTC, novice0840 approved these changes

2024-08-22 01:27 UTC, rbgksqkr commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      expect(handleModalOpen).toHaveBeenCalledTimes(1);
RTL 에서 clipboard 관련해서 테스트 코드가 있네요 이것도 추후에 적용해보면 좋을 것 같네요:)

https://testing-library.com/docs/user-event/clipboard/

2024-08-22 01:27 UTC, rbgksqkr approved these changes

2024-08-22 01:37 UTC, useon commented on frontend/src/components/common/NextRoundButton/NextRoundButton.test.tsx
> +      expect(handleModalOpen).toHaveBeenCalledTimes(1);
와 ! 좋아요 !! 추후 리팩토링에 반영하도록 하겠습니다 😊👍

2024-08-22 04:33 UTC, merged