[FEAT] 선택 완료 시 옵션 클릭되는 오류 해결 및 방설정 모달 구현
woowacourse-teams/2024-ddangkong pull request #200
Opened 2024-08-17 17:36 UTC by rbgksqkr

## Issue Number
#171 

## As-Is

- 방을 사용자가 원하는 대로 설정할 수 없음
- 선택 완료를 눌렀는데도 선택이 바뀌는 것처럼 옵션 버튼이 클릭이 됨

## To-Be

- 카테고리, 총 라운드, 타이머를 사용자 마음대로 설정할 수 있음
- 선택 완료를 누르면 옵션 버튼을 클릭할 수 없음
- dropdown 구현
- 방 설정 모달 구현
- 폴링으로 받는 방설정 정보를 초기값으로 설정
- 적용을 누르지 않고 모달을 끄면 변경사항이 적용되지 않도록 구현
- 유저 스토리 기반 RTL 테스트 코드 작성

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
<img width="600" alt="image" src="https://github.com/user-attachments/assets/e818192d-0fdd-4339-8f2e-2eff49eddd53">

## (Optional) Additional Description
- 분량 조절 실패 죄송합니다,,,,,,,,,,,,,,ㅎㅎ (css랑 테스트랑 모킹이랑 스토리북 빼면 대충 400줄 될 것 같긴해요,,,,,,,)
- 방장 구분 로직이 없어 `분기처리 필요`
- 카테고리 리스트 가져오는 게 아직 API가 완성되지 않아서, 명세 맞춰 msw로 카테고리 리스트 가져오는 것과 방 설정하는 API 모킹
  - 카테고리 리스트 가져오는 `API 완성 후 테스트 필요`

2024-08-18 03:57 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.stories.tsx
> +export const 방_설정_모달: Story = {
airbnb 모달 스토리북 보니까 모달 여닫는 버튼 두고 만들었길래 유사하게 만들어봤습니다

https://airbnb.io/lunar/?path=/story/core-modal--default-modal-600-px

2024-08-18 03:57 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
> +    customRender(<RoomSettingModal isOpen={true} onClose={jest.fn()} />);
함수 호출 여부가 테스트 대상이 아니라서 jest.fn() 을 사용하였습니다!

2024-08-18 03:57 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
> +  if (!categoryList || !category) return null;
jsx를 반환하면 모달을 처음킬 때 화면이 움직이는 현상이 생겨서 null을 반환하여 없을 때 해당 컴포넌트가 아무것도 반환하지 않도록 처리하였습니다!

2024-08-18 03:57 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/hooks/useRoomSetting.ts
> +const useRoomSetting = ({ onClose }: UseRoomSettingProps) => {
카테고리와 총 라운드, 라운드 당 타이머를 하나로 관리하는 커스텀 훅입니다

2024-08-18 03:57 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/hooks/useTimerPerRound.ts
> +  useEffect(() => {
props가 바뀔 때 useEffect를 실행하는 건 지양하는 패턴인데, 각 훅에 useEffect가 존재하는 이유는 쿼리의 응답값을 초기값으로 설정해야하기 때문입니다. query의 초기값이 undefined인데 useState는 초기값을 기억하기 때문에 props에 따라 바뀌지 않아 이렇게 사용하였습니다.

react-query의 undefined를 처리할 수 있는 더 좋은 방법이 있다면 말해주세요:)

2024-08-18 19:46 UTC, useon requested changes
안녕하세요 말우 .. 고봉밥 PR에 덩달아 리뷰도 고봉밥..  🥹 오류 해결에 ~ 방 설정 모달 디자인도 후다닥 해버리고~ 구현까지!! 고생 많았어요 역시 든든한 마루 !!! ✨ 몇 가지 제안 사항과 궁금한 점을 댓글 달았어요 🙌 저는 그저 제안한 것이라 마루가 판단하고 우선 순위에 차질이 없다면 고려해 주셔요 ~ ! ! 😊😊 _혹시 제가 이상하게 코멘트 단 부분이 있다면 수면 이슈일수도_ .. 🫠

2024-08-18 19:46 UTC, useon commented on frontend/src/apis/room.ts
> +    body: { totalRound, timeLimit, category },
# 💭 질문 💭
혹시 저희 방 설정에서 header는 안 넣어줘도 괜찮은 건가요?! 😎

2024-08-18 19:46 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingItem/RoomSettingItem.tsx
> +    <div css={roomSettingTitleContainer}>
# 🙏 제안 🙏
여러 선택 버튼의 중 하나의 항목을 나타내는 것 같은데, 해당 태그를 li로 하는 것은 어떨까요? 🙌

2024-08-18 19:46 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.stories.tsx
> +export const 방_설정_모달: Story = {
오 !!!!! 좋은데요 ?????? 열릴 때부터 알 수 있어 좋은 것 같아요! 저도 코드 리팩토링 할 때 참고하겠습니다 짱 😎✨

2024-08-18 19:46 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  width: 70vw;
# 💭 질문 💭
width를 vw 단위로 잡으신 이유가 있나요 ?! 🤓

2024-08-18 19:46 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  max-width: 768px;
# 💭 질문 💭
해당 max-width는 root에 적용되어 있지 않나요? 또한 root에 768px이 적용되어 있는데 그렇다면 방설정 모달이 앱 전체 크기와 동일하게 화면에 뜨지 않을까요 .. ? 혹시 제가 잘못 이해했다면 알려주세요 😊🙌

2024-08-18 19:46 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
> +            {TIMER_PER_ROUND_LIST.map((timer) => (
# 🙏 제안 🙏
제한 시간을 나타내는 의미를 담으면 어떨까요? timer는 해당 동작을 수행하는 도구 같은 느낌이라! timeLimit 과 같은 네이밍은 어떠신가요? 😊

2024-08-18 19:46 UTC, useon commented on frontend/src/types/room.ts
> +export type Category = '음식' | '연애' | 'MBTI' | '만약에';
# 🌸 칭찬 🌸
회의를 통해 정해진 카테고리에 대해서만 유니언 타입으로 정의 굿굿굿 !!!!!

2024-08-18 19:46 UTC, useon commented on frontend/src/hooks/useModal.ts
> +export default useModal;
# 🌸 칭찬 🌸
아 반갑습니다. 저는 내용은 같고 함수 이름만 다른 코드를 가지고 있는데요. 제 이름은 useModalHandler 입니다 곧 개명 예정임 ^ ^

2024-08-19 00:09 UTC, rbgksqkr commented on frontend/src/styles/Theme.ts
> +  normal: 1,
오!!!! 단순히 자주 사용될 것 같아 Theme으로 관리해야겠다고만 생각했는데 여러 값으로 관리될 수 있겠군요! 사실 네이밍을 꽤 고민했었는데 값을 여러개로 관리한다면 바꾸는 게 좋은 것 같아요!

2024-08-19 00:11 UTC, rbgksqkr commented on frontend/src/components/common/Dropdown/Dropdown.tsx
> +      }
분리한다는 게 useEffect 밖에 선언한다는 이야기일까요??
useEffect 밖에 선언한다면 함수를 useCallback 으로 감싸야할텐데 그 방향을 이야기하는 게 맞을까요?

2024-08-19 00:25 UTC, rbgksqkr commented on frontend/src/components/common/Dropdown/Dropdown.tsx
> +      }
분리한다는 게 useEffect 밖에 선언한다는 이야기일까요??
useEffect 밖에 선언한다면 함수를 useCallback 으로 감싸야할텐데 그 방향을 이야기하는 게 맞을까요?

2024-08-19 00:25 UTC, rbgksqkr commented on frontend/src/apis/room.ts
> +    body: { totalRound, timeLimit, category },
앗 카테고리 API가 구현중이라 실제 연결을 안해봐서 놓쳤는데 추가하겠습니다!

2024-08-19 00:25 UTC, rbgksqkr commented on frontend/src/components/common/Dropdown/Dropdown.tsx
> +      onKeyDown={() => setIsOpen((prev) => !prev)}
워후 엄청난 래퍼런스를 첨부해주셔서 천천히 다 읽어보겠습니다 ㅎㅎ select와 option으로 만들면 옵션이 커스텀이 안되는 걸로 아는데 접근성을 챙기는 게 더 나을까요??

> 목록을 ul로 감싸고 li로 항목을 명시하고 li 안에 각 클릭 가능한 옵션들을 button 태그를 달아주는 것은 어떨까요 ?

이 방식은 좋은 것 같아요!! 적용해보게씁니다

2024-08-19 00:25 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingItem/RoomSettingItem.tsx
> +    <div css={roomSettingTitleContainer}>
오 리스트 형태가 아니라고 생각했는데 아래로 나열되지 않더라도  목록의 항목이라는 의미에서 li 태그도 좋은 것 같네용

>HTML `<li>` 요소는 목록의 항목을 나타냅니다.

2024-08-19 00:25 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  width: 70vw;
화면이 컸을 때 너무 조그맣길래 설정했어요! 모달 크기가 보통 유동적인지 고정인지 모르겠네용 혹시 그럼 width를 24rem으로 잡으신 이유가 있을까요??

2024-08-19 00:25 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  max-width: 768px;
앗 넵 맞아요 ㅋㅋㅋㅋㅋㅋ 근데 약간 임시로 작성한 거긴 했어요! 왜냐면 위에서 width를 vw로 주니까 데스크톱에서는 너무 커서 max-width를 줘야 했는데, root 의 768에서 padding 조금빼서 720px 정도로 잡으면 다른 사람이 또는 나중에 봤을 때 어떤 값인지 이해가 안될 것 같아 일단 768로 두긴 했습니다!
width의 vw단위를 사용하지 않는다면 이부분도 없어지겠네용 어떻게 값을 잡는 게 나을까요??

2024-08-19 06:08 UTC, useon commented on frontend/src/components/common/Dropdown/Dropdown.tsx
> +      onKeyDown={() => setIsOpen((prev) => !prev)}
맞아요 select와 option으로 만들면 커스텀이 제한적이라서 저희 피그마대로 구현하기는 힘들 것 같아요. 일단 마루가 오케이 한 방법으로 적용해 보시고 이슈 발생하면 자유롭게 공유해 주세요 !!!! 😊 프론트엔드로서 웹 접근성 어렵지만 신경 쓰는 경험은 정말 좋은 것 같아요! 저도 덕분에 어제 웹 접근성에 대해 많이 공부해서 좋았습니다 푸하항 ^ .^

2024-08-19 06:20 UTC, useon commented on frontend/src/components/common/Dropdown/Dropdown.tsx
> +      }
처음에는 분리를 하면 좋지 않을까 생각했는데 ! 리액트 공식 문서에서 
Effect가 너무 자주 실행되는 것을 방지하기: https://ko.react.dev/reference/react/useCallback#preventing-an-effect-from-firing-too-often
해당 내용을 읽고 생각이 바뀌었어요.. ! ! ! 기존 코드를 유지해도 괜찮을 것 같아요 마루 생각은 어떠하쉼니까 😊

2024-08-19 06:34 UTC, rbgksqkr commented on frontend/src/components/common/Dropdown/Dropdown.tsx
> +      }
오 공식문서에서 명확하게 적혀있네요!
저도 테코톡 발표할 때 useEffect 관련된 공식문서를 여러번 읽었는데요
useEffect 내에서 선언한 값은 반응형값으로 인식하지 않아서 다른 부수효과가 발생하지 않고, useCallback을 사용하여 메모리를 사용하는 것보다 좋은 방법인 것 같아서 useEffect 내에 선언했습니다 👍

2024-08-19 06:42 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  width: 70vw;
제가 모달 width를 24rem으로 작성했던 이유는 루트에 설정한 화면의 크기에서 모달의 width가 어느 정도면 괜찮을까 하며 여러가지 값을 넣어보다가 24rem크기가 괜찮다고 생각해서 작성을 했어요 ! 하지만 이것은 기본으로 설정된 공통 모달의 크기이지 모달의 종류에 따라 width는 달라질 수 있다고 생각합니다. vw로 설정하면 768px 보다 화면이 큰 경우 모달의 width가 그에따라 더 커지지 않을까요 ???? 🤓 흠 .. 그렇다면 아예 rem으로 고정하거나 %로 맞춰야 하나 고민이 되네요. 마루 생각은 어때요 ?!

2024-08-19 06:45 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  max-width: 768px;
위의 코멘트와 연관될 사항인 것 같아요 ! 마찬가지로 vw로 잡은 것에 따라 해당 부분이 데스크톱에서 너무 크다고 느낄 것 같아요 ! 따라서 저는 vw 단위보다는 다른 방법을 생각해 볼 수 있을 것 같은데 마루는 어떻게 생각하시나요 ?! 😎

2024-08-19 06:51 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  width: 70vw;
> vw로 설정하면 768px 보다 화면이 큰 경우 모달의 width가 그에따라 더 커지지 않을까요 ????

vw로 해도 max-width를 설정하면 max-width 보다 커지지 않아서 max-width만 정하면 문제가 없긴 합니다!
%는 부모의 너비에 영향을 받기 때문에 디바이스를 기준으로 width 비율을 맞춰야된다고 생각하여 vw를 선택하였습니다!
위의 문제가 해결되어도 vw는 별로인 건가요??

2024-08-19 06:53 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  max-width: 768px;
고정으로 했을 때 크롬에서 제공하는 여러 디바이스를 클릭해보면 디바이스에 따라 좁다고 느껴졌습니다! 
그렇다고 중간 디바이스 크기를 기준으로 고정 픽셀을 잡으면 작은 디바이스에서는 모달이 깨질 것이구요
그래서 퍼센트 비율로 모달 크기를 나타내야 된다고 생각합니다!@!

2024-08-19 07:02 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  width: 70vw;
> %는 부모의 너비에 영향을 받기 때문에 디바이스를 기준으로 width 비율을 맞춰야된다고 생각하여 vw를 선택하였습니다!
해당 답변에서 vw를 사용한 것을 이해할 수 있었어요 ! 저는 테스크탑인 경우 모달이 화면에 너무 꽉차거나 클까 봐 말씀드린 내용이었는데 해당 부분이 해결이 된다면 괜찮을 것 같아요 😎

2024-08-19 07:03 UTC, useon commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  max-width: 768px;
아하 ! 그러면 공통 모달이 %로 기본 크기 조정이 필요하다고 생각하시군요 ! 좋은 것 같네요 🙌

2024-08-19 11:19 UTC, novice0840 requested changes
수고 많았어요!!!

소스 코드 다 읽어보고 리뷰 남깁니다. 천천히 반영해주세요

2024-08-19 11:19 UTC, novice0840 commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.test.tsx
> +      expect(result.current.roomSetting?.timeLimit).toBe(TIME_LIMIT);
# 🙏 제안 🙏
"특정 옵션을 변경 후 확인 버튼을 누른다"라는 동작이 반복되는 것 같은데 이 공통 부분을 함수로 만드는 건 어떤가요?

2024-08-19 11:19 UTC, novice0840 commented on frontend/src/components/common/RoomSettingModal/hooks/useCategoryListQuery.ts
> +  return { ...categoryListQuery, categoryList: categoryListQuery.data?.categoryList };
# 💭 질문 💭
혹시 만약 categoryList가 없는 경우에는 dropdown UI 자체가 안 보이게 되는건가요?

2024-08-19 11:19 UTC, novice0840 commented on frontend/src/components/common/RoomSettingModal/hooks/useRoomSetting.ts
> +  };
# 💭 질문 💭
혹시 이렇게 되면 방 설정 API가 실패해도 
모달이 닫히지 않나요?

2024-08-19 11:19 UTC, novice0840 commented on frontend/src/components/common/RoomSettingModal/hooks/useRoomSetting.ts
> +  const { timerPerRound, handleClickTimer } = useTimerPerRound(selectedRoomSetting?.timeLimit);
# 🌸 칭찬 🌸
각 요소를 별도의 hook으로 분리했다가 하나의 지점에서 모으는군요 ㅎㅎ

2024-08-19 11:19 UTC, novice0840 commented on frontend/src/components/common/SelectButton/SelectButton.tsx
> +  };
# 💭 질문 💭
handleClickSelected에는 인자가 없는 것 같은데 무엇을 선택했는지는 전달하지 않아도 되는 함수인가요?

2024-08-19 13:10 UTC, rbgksqkr reviewed
썬데이 코멘트 반영 완료하였습니다 ✨

2024-08-19 13:10 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.styled.ts
> +  max-width: 768px;
디스코드에서 이야기 나눈 것처럼 width를 해당 코드에서 제거하고 추후에 새로운 이슈에서 공통 모달에서 관리하도록 하였습니다~!

2024-08-19 13:10 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/RoomSettingModal.tsx
> +            {TIMER_PER_ROUND_LIST.map((timer) => (
반영하였습니다!

2024-08-20 08:41 UTC, rbgksqkr reviewed
포메 리뷰도 반영 완료하였습니다!

2024-08-20 08:41 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/hooks/useCategoryListQuery.ts
> +  return { ...categoryListQuery, categoryList: categoryListQuery.data?.categoryList };
오 신경을 못쓰고 있었는데 해당 코드라면 전체 방설정이 안보이게 될 것 같아요! null 을 반환한 이유는 레이아웃 변화가 생겨서 그랬던건데 근본적인 해결책이 아니였던 것 같아요 ㅎㅎ

그래서 생각해봤는데 Dropdown 자체는 공통 컴포넌트니까 한번 래핑한 CategoryDropdown 으로 방설정 모달에 사용되는 컴포넌트로 분리해봤습니다
그래서 컴포넌트 내에서 카테고리 목록 API를 호출하여 에러가 나더라도 드랍다운만 안보이게 됩니다!!!

2024-08-20 14:29 UTC, novice0840 approved these changes
달아준 답글들 확인했습니다 ~ 

이제 마지막이니까 조금만 더 힘냅시다. 화이팅~!!

2024-08-20 16:01 UTC, useon approved these changes
마루 모든 커밋 확인했어요 🍀🍀 포메와 저 둘 다 제안 사항이 많았는데 열심히 고민해주고 또 빠르게 반영해 주셔서 감사해요 코드 +1000줄을 넘겨버린 말우 .. 대단하자나 🥹 반영 확인한 코멘트 이모지 달았고 추가로 작업한 부분 위주로 코멘트 달았습니다 ! 고생했다 조말우 !!!!!

2024-08-20 16:14 UTC, rbgksqkr commented on frontend/src/components/common/RoomSettingModal/CategoryDropdown/CategoryDropdown.tsx
> +  if (!categoryList || !category) return <div>카테고리가 없습니다.</div>;
네넵 카테고리를 불러오지 못하더라도 라운드나 타이머는 설정할 수 있다는 장점이 있을 것 같은데, 다른 처리가 필요하다는 게 아예 방설정 모달이 안뜨게 처리하는 걸 생각하신걸까요??

2024-08-20 16:14 UTC, merged