[FEAT] 방이 활성화 중인지 여부 확인 API
woowacourse-teams/2024-ddangkong pull request #216
Opened 2024-08-19 13:40 UTC by jhon3242

## Issue Number
close #214 

## As-Is

유저가 방에 접속하거나 재접속시 전에 해당 방이 활성화 중인지 확인하는 API가 필요함(게임이 종료되었으면 방에 접속하지 못하게 하기 위함)

## To-Be

- 방이 활성화 중인지 확인하는 API 추가

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
<img width="734" alt="image" src="https://github.com/user-attachments/assets/29213c82-ae13-4426-9110-34c56a536de1">

## (Optional) Additional Description

2024-08-19 13:50 UTC, leegwichan reviewed
타칸의 기능 구현 속도에 두 번 놀랬습니다...
남긴 코멘트 확인해줘!

2024-08-19 13:50 UTC, leegwichan commented on backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
> +        }
제안) 해당 테스트들은 다른 `@Nested` class로 만드는 게 좋을 것 같아요.

> 하나의 기능에 대한 테스트를 작성할 때, `@Nested`로 내부 클래스를 생성하고 실패 테스트/성공 테스트 등 세부 테스트를 내부에 작성한다.
(BE 코드 컨벤션 중)

2024-08-20 05:29 UTC, PgmJun requested changes
고생하셨습니다 타칸

2024-08-20 05:29 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/room/Room.java
> +
의견) 방이 활성화 되어있는지 확인해서 접근 가능한 지 여부(isActivate)를 response하는 기능으로 알고 있는데 일단 재접속이라는 존재하지 않는 기능 구현을 위해서 isGameProgress가 valiate에 들어가게 된 것 같은데요..!
일단 저희는 재접속을 구현하지 않을 예정이니 isGameProgress()는 제거해야할 것 같습니다.

그리고 검증 로직이 isGameReady()로 끝날 것이 아니라
- room이 존재하는가 ✅ (getById 로 구현되어 있음)
- (member가 존재하는가는 필요없을 것 같아요 마지막 member가 삭제될 때 room이 하나의 트랜잭션에서 삭제되기 때문에 어짜피 끝난 방인데 room이 존재하면 member가 무조건 있을겁니다.)
- 방이나 방의 member가 modifiedAt이 120분이 이내인가 (기준이 120이긴한데 괜찮을지 얘기해봐야할 것 같아요 비활성화되어있는 방에 접속이 가능할 것 같아서요)
- Ready 상태가 맞는가

순서로 구현되어야하지 않을까 싶은데 커찬이 잡고있는 스케쥴링 부분과 공통된것 같아서 같이 얘기해서 처리해보심 좋을 것 같네요!

2024-08-21 08:06 UTC, leegwichan approved these changes
LGTM~!

2024-08-21 08:53 UTC, GIVEN53 reviewed
⭐️⭐️ API 명세에는 '방 참여 가능 확인'으로 다시 변경되었는데 PR은 아직 그대로입니다
논의된 바와 같이 '활성화'라는 컨텍스트를 아예 제거해주시면 감사하겠습니다!

2024-08-21 08:53 UTC, GIVEN53 commented on backend/src/docs/asciidoc/room.adoc
> +=== 게임 활성화 여부
의견)
'방 참여 가능 여부 확인'는 어떨까요?

2024-08-21 08:53 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/facade/room/RoomFacade.java
> +        Room room = roomService.getRoomWithLock(uuid);
질문)
락을 걸고 조회하는 메서드를 사용하신 이유가 있을까요?

2024-08-21 08:53 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/facade/room/dto/RoomStatusResponse.java
> +        boolean isReady
의견)
`isJoinable`과 같이 방 상태가 직접적으로 노출되지 않게 캡슐화하는 것은 어떨까요? 클라이언트 입장에서는 방 상태가 ready인지, progress인지 등의 컨텍스트는 아예 모르기 때문입니다
이와 관련해서 포메에게 구현 진척도를 물어봤는데 아직 반 정도 구현했다고 하네요 명세만 잘 업데이트하면 문제없을 것 같습니다

2024-08-21 08:53 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/room/member/RoomMembers.java
> +    public boolean isEmpty() {
질문)
해당 메서드를 사용하는 부분을 찾지 못했는데 사용되는 메서드인가요?

2024-08-21 12:12 UTC, jhon3242 commented on backend/src/docs/asciidoc/room.adoc
> +=== 게임 활성화 여부
꼼꼼한 확인 감사합니다!

2024-08-21 12:12 UTC, jhon3242 commented on backend/src/main/java/ddangkong/facade/room/RoomFacade.java
> +        Room room = roomService.getRoomWithLock(uuid);
앗.. UUid 를 사용해서 조회하는 메서드를 호출한다고만 생각했었는데 락이였군요.. 이 부분은 바꿔볼게요!

2024-08-21 12:12 UTC, jhon3242 commented on backend/src/main/java/ddangkong/facade/room/dto/RoomStatusResponse.java
> +        boolean isReady
명시적으로 Ready 임을 나타낼 필요가 없을 것 같긴하네요! 포메한테 얘기해서 반영해볼게요!

2024-08-21 12:56 UTC, GIVEN53 approved these changes
Good~~~~~~~~~~ 딱칸 멋져

2024-08-22 02:30 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/room/Room.java
> +
질문) 위에 메서드는 `isGameProgress()` 인데 해당 메서드는 `isReady()`로 되어있네요
통일부탁드려도 될까요??

2024-08-22 02:32 UTC, PgmJun commented on backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
> +            //when & then
사소한 의견) 띄어쓰기 가능??ㅎㅎ

2024-08-22 02:35 UTC, PgmJun commented on backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
> +        void 대기중인_방_참여_가능_여부_조회() {
의견) 별도 API라서 Nested로 분리해야할 것 같아여~!

2024-08-22 02:36 UTC, PgmJun commented on backend/src/test/java/ddangkong/facade/room/RoomFacadeTest.java
> +        void 준비중인_방에_참여_가능_여부를_조회한다() {
사소한 의견) 조회한다보다는 "~인 방에는 참여할 수 있다" 로 작성하는게 더 보기 편하지 않을까요??

2024-08-22 02:37 UTC, PgmJun requested changes
고생하셨습니다 타칸~! 리뷰 남겼으니 확인부탁드려요!!

2024-08-22 03:54 UTC, jhon3242 commented on backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
> +        void 대기중인_방_참여_가능_여부_조회() {
이것도 하나의 방 정보 조회라고 생각해서 넣어놨는데 API가 다르니까 분리하는게 맞을 것 같아요! 반영해볼게요!

2024-08-22 04:25 UTC, PgmJun approved these changes
수고하셨어요 탘한~~

2024-08-22 04:25 UTC, PgmJun commented on backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
> +        void 대기중인_방_참여_가능_여부_조회() {
다른 테스트 클래스에서는 Nested로 분리되어있어서 여쭤보았숨니다~

2024-08-22 04:26 UTC, merged