[FEAT] 투표 현황 페이지에서 투표를 하지 않은 참여자를 보여주는 기능
woowacourse-teams/2024-ddangkong pull request #218
Opened 2024-08-19 23:35 UTC by useon

## Issue Number
#199 

## As-Is

투표 현황 페이지에서 투표를 하지 않은 인원을 보여주지 않아 게임 하는 입장에서 혼란을 유발했다. 

## To-Be

- [x] 인원수가 적을 때 투표 현황 ui가 가운데로 정렬되는 문제 해결
- [x] 투표에 참여하지 않은 명단을 투표 현황에 추가
- [x] 프로필 이미지를 땅콩 이모지에서 직접 그린 땅콩 이미지로 수정 

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
- 수정 전
![image](https://github.com/user-attachments/assets/46f8374a-d608-49a1-8243-51430a7a2bd3)

- 수정 후
![image](https://github.com/user-attachments/assets/34d115c2-c592-41cb-bdac-4f9afee13a28)

## (Optional) Additional Description

2024-08-20 02:18 UTC, novice0840 requested changes
썬데이, 수고많았습니다~~

OptionParticipants component 파일이 안 보이는 것 같은데 혹시 안 올라온건지 확인한 번 부탁드립니다

2024-08-20 02:18 UTC, novice0840 commented on frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
> +        <div css={dividerLine}></div>
# 🙏 제안 🙏
영역을 구분할 때 선을 그려주는 css 속성으로 보이는데 속성 이름에 가로로 나누는지 세로로 나누는지를 명시하면 어떤가요?

2024-08-20 02:18 UTC, novice0840 commented on frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
> +        />
# 🌸 칭찬 🌸
깔끔하게 컴포넌트 분리 잘 되었네요.

2024-08-20 02:18 UTC, novice0840 commented on frontend/src/mocks/data/roundVoteResultInitialValue.json
> +      "memberCount": 0
# 💭 질문 💭
혹시 InitialValue를 별도로 만든 이유가 있나요?

2024-08-20 02:20 UTC, rbgksqkr reviewed
고생하셨습니다 썬데이!!!!!! 투표 현황 버튼을 차마 눌러볼 수 없었는데 드디어 보여줄 수 있겠군요 하하 몇가지 참고할 코멘트 남겨봤습니다 참고해주세요~!~

2024-08-20 02:20 UTC, rbgksqkr commented on frontend/src/components/NicknameItem/NicknameItem.tsx
> +      <img src={SillyDdangkong} alt="" css={profileImage} />
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
웹 접근성을 고려하여 alt 에 아이콘의 의미를 담으면 좋을 것 같아요! img 태그를 읽을 때는 이미지라는 텍스트를 넣지 않아도 된다고 해서 "사용자 프로필" 이라고 작성하면 좋을 것 같아요!

https://tech.kakaopay.com/post/accessibility-stories-for-everyone/

2024-08-20 02:20 UTC, rbgksqkr commented on frontend/src/components/NicknameItem/NicknameItem.styled.ts
>  export const nicknameListLayout = css`
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
nicknameItem의 최상단이 nicknameList 라는 단어를 써서 어색하게 느껴지는 것 같아요! 1개에 대한 스타일링이니까 nicknameItemLayout 은 어떨까요?

2024-08-20 02:20 UTC, rbgksqkr commented on frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
> +        <OptionParticipants
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
팀 코드 컨벤션에 따라 -s 대신 List를 사용하는 건 어떨까요??

2024-08-20 02:20 UTC, rbgksqkr commented on frontend/src/components/NicknameItem/NicknameItem.styled.ts
>    width: 50%;
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
사소한 의견인데 grid를 적용해보는 것도 좋은 것 같아요! grid를 쓰면 item의 width를 조정하여 신경써주지 않아도 레이아웃이 잡힌다는 장점이 있습니다~!

2024-08-20 02:20 UTC, rbgksqkr commented on frontend/src/types/roundVoteResult.ts
> +export type GroupMembersAndMemberCount = Pick<GroupOption, 'members' | 'memberCount'>;
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
giveUp 이라는 필드명과 타입명을 매칭시켜봤을 때 살짝 어색한 것 같아요! 네이밍에 고민이 많았을 것 같네용
GroupMemberInfo 정도로만 둬도 괜찮을 것 같아요
아니면 members와 memberCount 를 별도의 인터페이스로 선언하고, 타입을 합치는 방식으로 리팩토링하는 것도 깔끔해질 것 같네용

2024-08-20 02:20 UTC, rbgksqkr commented on frontend/src/mocks/data/roundVoteResultInitialValue.json
> +      "memberCount": 0
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
msw까지 굿굿굿

2024-08-20 02:20 UTC, rbgksqkr commented on frontend/src/types/roundVoteResult.ts
> +export type GroupMembersAndMemberCount = Pick<GroupOption, 'members' | 'memberCount'>;
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
이제 타입을 자유자재로 가지고 노는군요 타입 드리블 ㄷ ㄷ

2024-08-20 06:45 UTC, useon reviewed
안뇽하세요 여러분 !! 주신 달달한 리뷰 감사합니다 ~ ! 빠르게 (?) 반영해보았는데요 ! 질문에 대한 답변과 제안에 대한 반영 여부도 삭- 달아 놓았으니 확인 부탁 드릴게용 🍀🍀

2024-08-20 06:45 UTC, useon commented on frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
> +        <div css={dividerLine}></div>
가로로 나눈다는 선이라는 의미를 담아 네이밍을 수정할게요 !!!

2024-08-20 06:45 UTC, useon commented on frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
> +        <OptionParticipants
해당 OptionParticipants 컴포넌트가 여러 개의 OptionParticipant를 하나로 묶는 컴포넌트가 아니라 하나의 선택지와 해당 선택지에 투표한 투표자들을 보여주는 컴포넌트입니다 !! 따라서 하위 컴포넌트에는 nickNameList와 nickNameItem이 위치하게 됩니다. 😊

2024-08-20 06:45 UTC, useon commented on frontend/src/mocks/data/roundVoteResultInitialValue.json
> +      "memberCount": 0
초기 로딩 시 보여지는 msw data 입니다 ! 이미 작성되어 있는 로딩시 보여지는 data에 기권자 항목이 api에 추가됨에 따라 해당 giveUp 항목을 추가했습니다 😎

2024-08-20 06:45 UTC, useon commented on frontend/src/types/roundVoteResult.ts
> +export type GroupMembersAndMemberCount = Pick<GroupOption, 'members' | 'memberCount'>;
```ts
export interface GroupMemberInfo {
  members: string[];
  memberCount: number;
}

export interface RoundVoteResult {
  group: Group;
  total: Total;
}

export interface Group {
  firstOption: GroupOption;
  secondOption: GroupOption;
  giveUp: GroupMemberInfo;
}

export interface Total {
  firstOption: TotalOption;
  secondOption: TotalOption;
}

export interface GroupOption extends TotalOption, GroupMemberInfo {}

export interface TotalOption {
  optionId: number;
  name: string;
  percent: number;
}
```
고객님 주문대로 인터페이스 요리 했는데 어떠하십니까 ?? 👩‍🍳

2024-08-20 10:01 UTC, rbgksqkr approved these changes
굿굿 반영 모두 확인하여 어프루브 하겠습니다~!~!

2024-08-20 10:01 UTC, rbgksqkr commented on frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
> +        <OptionParticipants
토크토크 해봤는데 Option과 Participants 각각을 의미하는 걸 알게 되었어요! 확실히 그런 의미에선 List가 애매하긴 하네요 ㅎㅎ
groupRoundResult 섞어서 또는 투표 현황 아이템 느낌으로 해보는 건 어떤가용

2024-08-21 07:56 UTC, novice0840 approved these changes
변경사항 확인했습니다~~

2024-08-22 01:31 UTC, useon commented on frontend/src/types/roundVoteResult.ts
> +export type GroupMembersAndMemberCount = Pick<GroupOption, 'members' | 'memberCount'>;
추후 리팩토링에 반영하도록 하겠습니다 👍

2024-08-22 01:31 UTC, useon commented on frontend/src/components/OptionParticipantsContainer/OptionParticipantsContainer.tsx
> +        <OptionParticipants
추후 리팩토링에 반영하도록 하겠습니다 👍

2024-08-22 04:36 UTC, merged