[REFACTOR] 에러 핸들링 (대기 화면 & 게임 화면)
woowacourse-teams/2024-ddangkong pull request #255
Opened 2024-08-28 10:36 UTC by rbgksqkr

## Issue Number
#230 

## As-Is

- 이전에는 에러 발생 시 서비스가 터질 위험이 있었음
- 서버에서 내려주는 에러 정보를 사용하고 있지 않았음

## To-Be

- API 응답값의 타입 에러, 500 내부 서버 에러 등의 에러를 ErrorBoundary를 적용하여 처리
- errorCode 상수화 및 CustomError 선언
- 네트워크 에러는 CustomError 와 별도로 처리한 후 Network 에러는 Toast로 처리 (일시적인 문제라고 판단)
- ErrorBoundary로 처리 시 에러 UI로 이동하고, resetQuery를 사용하여 최근에 실패한 쿼리 재실행 가능
- 로딩 화면이 깜빡이는 것처럼 보여 UX를 해친다고 생각하여 300ms 안에 로딩 완료 시 로딩폴백 안보여줌
- skeleton UI를 사용하여 사용자에게 자연스러운 UX 제공

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
1. 대기 화면 skeleton, 2. 게임 화면 skeleton, 3. ErrorBoundary에 걸린 에러 UI, 4. 네트워크 오류 Toast

<img width="200" alt="readySkeleton" src="https://github.com/user-attachments/assets/32dab00f-8b6f-43cc-b094-60d6405b2ad9">
<img width="200" alt="gameSkeleton" src="https://github.com/user-attachments/assets/247c156d-8b84-4ace-8f15-8825e76b5dc1">
<img width="200" alt="errorFallback" src="https://github.com/user-attachments/assets/daef1b48-553a-400f-8332-5e8c536d5524">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/8dd21899-0a1d-4073-beff-8f6f87f064ba">

## (Optional) Additional Description
방학인데 고봉밥 PR 죄송합니다,,,기능 개발 때 못한 게 한이라서 좀 쏟아부었습니다,,,

**CustomError 관리**

- 서버에서 넘겨주는 에러 코드에 따라 다른 처리가 이뤄질 것 같아, Rest docs 참고하여 에러 코드 상수화
- 에러 코드에 따라 사용자에게 보여줄 메세지 출력
- 모든 경우의 수를 다 파악하지 못했지만, 파악한 내용에 대해선 에러 메세지 상수 옆에 주석 처리로 추가
- NetworkError는 런타임에 따로 구분하여 토스트를 띄워주기 위해 클래스 분리
```ts
export class CustomError extends Error {
  errorCode: string;
  status: number;

  constructor({ errorCode, status }: CustomErrorParams) {
    super();
    this.errorCode = errorCode;
    this.message = ERROR_MESSAGE[errorCode];
    this.status = status;
  }
}

export class NetworkError extends Error {
  status = 555;
  message = '네트워크가 불안정해요. 다시 시도해주세요!';
}

```

**UX를 고려한 로딩 UI 제어(DefferedComponent)**

저도 개발하면서 느꼈고, 사용자도 느꼈을 것 같은데, 로딩 될 때 로딩 UI가 보여지다가 데이터가 불러와지면 서비스가 보여지게 됩니다. 하지만 네트워크 응답속도가 빠를 경우 UI가 깜빡이는 것처럼 보이는 현상이 발생합니다. 따라서 이를 방지하기 위해 300ms 이내로 로딩이 완료되면 로딩 UI를 보여주지 않도록 처리하였습니다.

```ts
// loading fallback 을 지연시키는 wrapper 컴포넌트
const DeferredComponent = ({ children }: PropsWithChildren) => {
  const [isDeferred, setIsDeferred] = useState(false);

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setIsDeferred(true);
    }, 300);

    return () => clearTimeout(timeoutId);
  }, []);

  if (!isDeferred) {
    return null;
  }

  return <>{children}</>;
};

export default DeferredComponent;
```

2024-09-06 07:35 UTC, novice0840 requested changes
길고 긴 리뷰가 드디어 끝났네요 ㅎㅎ 

양이 많다 보니 코멘트도 같이 많아진 것 같네요. 천천히 확인하고 피드백 남겨주세용

2024-09-06 07:35 UTC, novice0840 commented on frontend/src/components/common/Skeleton/GameSkeleton/GameSkeleton.tsx
> +};
# 🙏 제안 🙏
혹시 skeleton 컴포넌트는 Storybook에는 안 올라가 있는 것 같은데 skeleton도 올리는 건 어떤가요?

2024-09-06 07:35 UTC, novice0840 commented on frontend/src/components/common/Skeleton/ReadySkeleton/ReadySkeleton.tsx
> +};
# 💭 질문 💭
현재 skeleton 컴포넌트가 2개가 있고 PR 본문에서 이미지를 봤을 때는 2개가 거의 동일한 것 같더라고요! 차이라고 하면 가운데 부분의 높이가 살짝 다른 정도?인데 2개로 나눌 필요가 있다고 보시나요?

2024-09-06 07:35 UTC, novice0840 commented on frontend/src/hooks/useBalanceContentQuery.ts
>    });
# 💭 질문 💭
suspense query를 사용하는 거면 부모 컴포넌트에서 Suspense로 감싸주고 있는 형태인건가요?

2024-09-06 07:35 UTC, novice0840 commented on frontend/src/index.tsx
> +          </ToastProvider>
# 🌸 칭찬 🌸
이제 서비스 전체에서 Toast를 함수 호출하는 것 만으로 사용할 수 있군요

2024-09-06 07:35 UTC, novice0840 commented on frontend/src/utils/error.ts
> +}
# 💭 질문 💭
이 에러는 네트워크가 offline이 되었을 때 나타나는 에러인가요?

2024-09-06 07:35 UTC, novice0840 commented on frontend/src/mocks/handlers/roomHandler.ts
> +  ROOM_INFO.roomSetting = { ...body, category: selectedCategory };
# 🙏 제안 🙏
인덱스로 접근하는 것이 가독성이 다소 떨어진다고 생각하는데 find로 category를 찾는 건 어떤가요?
```
const selectedCategory = CATEGORY_LIST.categories.find(
  (category) => category.value === body.category
);
```
이런식으로요!!

2024-09-06 09:05 UTC, rbgksqkr reviewed
포메 코멘트 답변 완료하였습니다 확인 부탁드려요:)

2024-09-06 09:05 UTC, rbgksqkr commented on frontend/src/components/common/Skeleton/ReadySkeleton/ReadySkeleton.tsx
> +};
음 꼭 하나로 추상화할 필요가 없다고 생각했습니다! 오히려 `*-Skeleton` 이라고 이름에 드러내서 어디에 사용되는지 명확하다는 생각이 들었습니다.
모든 페이지가 동일한 UI라면 공통적으로 사용할 것 같은데, 어떤 페이지는 공용으로 쓰고, 어떤 페이지는 새로 만들면 헷갈릴 것 같아서 분리하게 되었습니다! 이에 대해 어떻게 생각하시나요~?

2024-09-06 09:05 UTC, rbgksqkr commented on frontend/src/mocks/handlers/roomHandler.ts
> +  ROOM_INFO.roomSetting = { ...body, category: selectedCategory };
오 좋은데요?? 데모데이 때 급하게 만드느라 생각 못했네요 반영하겠습니다!

2024-09-07 16:35 UTC, novice0840 commented on frontend/src/components/SelectContainer/SelectContainer.tsx
> -  const { balanceContent, isLoading, isFetching } = useBalanceContentQuery(Number(roomId));
엉뚱한 줄에 코멘트를 남겨버렸네요 ;;;  ㅎ
확인했습니다!

2024-09-07 16:39 UTC, novice0840 commented on frontend/src/components/common/ErrorBoundary/AsyncErrorBoundary.tsx
> +}: PropsWithChildren<AsyncErrorBoundaryProps>) => {
아아 API 호출에 의한 에러라서 async를 붙인거군요 이해했습니다. API이외의 다른 에러가 발생하는 거나 한건 아닙니다

2024-09-07 16:49 UTC, novice0840 commented on frontend/src/components/common/Skeleton/ReadySkeleton/ReadySkeleton.tsx
> +};
이해했어요! skeleton을 여러 UI에 맞게 분리하는 것은 좋다고 생각해요

2024-09-07 17:00 UTC, novice0840 approved these changes
코멘트 남긴 것들 확인했습니다. ~~ 답글들 달았습니다. 이만 approve할게요!

2024-09-11 06:16 UTC, useon commented on frontend/src/components/TopicContainer/TopicContainer.test.tsx
> +      expect(screen.getByTestId('skeletonCategory')).toBeInTheDocument();
# 💭 질문 💭
오호 getByTestId를 사용하기 위해서 GameSkeleton에서 data-testid 속성을 넣은 것이군요 ?!! getByTestId로 작성하게 된 이유가 있나요??

2024-09-11 15:32 UTC, rbgksqkr reviewed
답변 완료했습니다 이해가 안됐거나 답변이 안됐다면 말해주세요:)

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/components/StartButtonContainer/StartButton/hooks/useGameStart.ts
> +    throwOnError: (error: CustomError) => isServerError(error.status),
throwOnError의 기본값은 false입니다! 기본값은 try-catch로 fetch 함수를 감쌌다고 생각하면 편해요! try-catch로 감싸면 외부로 에러가 전파되지 않는다는 의미죠! throwOnError: true 가 되면 비동기 에러를 잡아서 다음 렌더링 프로세스에 던지는거죠

>조건이 충족되지 않는 경우에만 onError로 처리가 되는 건지 궁금합니다 😊

onError와 throwOnError에서 모두 콘솔을 찍어봤는데요! onError로 들어온다음 throwOnError가 찍히더라구요
예시를 빌리면 startGame에서 에러가 나면 던져진 에러가 onError의 넘겨준 함수의 인자로 들어옵니다. 
onError에서는 네트워크 에러라면 토스트, 아니면 모달을 띄우는 로직입니다! 그런데 그 에러가 서버 에러라면 에러바운더리로 던져서 에러 폴백 UI를 보여주도록 구현해보았습니다. 잘 설명이 되었을까요?? 그리고 이러한 처리에 대해 어떻게 생각하시나요?

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/components/TopicContainer/TopicContainer.test.tsx
> +      expect(screen.getByTestId('skeletonCategory')).toBeInTheDocument();
음 test-id를 지양하라고 공식문서에 나와있어서 저도 쓰고싶지 않은데요,,,div 태그에다가 텍스트도 없어서 test-id를 추가하게 되었습니다,,,,혹시 좋은 아이디어가 있다면 공유해주세요~!~

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/components/common/Skeleton/GameSkeleton/GameSkeleton.tsx
> +};
넵 반영해보겠습니다~!~

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/components/layout/Header/Header.tsx
> +        {balanceContent ? `${balanceContent?.currentRound}/${balanceContent?.totalRound}` : '0/0'}
으음 저도 살짝 고민하긴 했었는데 로딩 텍스트는 또 깜박임 현상이 발생할 것 같아서 제외하였고, 숫자 형태였다가 불러와지면 올바른 숫자로 바뀌는게 자연스럽다고 생각했어요! 불러오는 시간이 늦어지면 혼란이 올 수 있겠네요,,,
근데 Suspense에 같이 잡히는 걸로 수정해서 로딩중인 상태가 없을 것 같긴 하네용 확인해보고 변경해보겠습니다~!~

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/constants/message.ts
> +  INVALID_ROUND_GAP: 'currentRound과 round의 차이는 ?이하여야 합니다.',
바로 보여지는 게 상수 맞습니다! 근데 일부는 API 명세 그대로 옮겨 적은 부분이 있어요. 왜냐면 어디서 발생하는 에러인지 명확하게 파악하지 못해서 그에 맞는 메세지를 작성하지 못했어요. 제가 모든 에러 상황을 테스트해보지 못해서, 이 부분은 자기 파트 에러핸들링 구현하면서 주석 추가해주면 좋을 것 같아요!!!

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/hooks/useBalanceContentQuery.ts
>    });
넵 비동기 호출을 하는 컴포넌트를 Suspense로 감싸야 Suspense에서 로딩 상태를 받을 수 있는 걸로 이해하시면 도리 것 같습니당

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/utils/error.ts
> +export class CustomError extends Error {
> 에러를 다루는 유틸은 보통 class로 작성되나요? 

보통 class로 작성된다기보단 타입을 런타임에 잡기 위해서 클래스를 사용했다가 맞을 것 같아요! 클래스를 런타임 타입체크용으로 사용했다는 의미입니다!
타입스크립트는 빌드하면서 타입이 제거되고 자바스크립트로 컴파일되는데, 타입에 따라 분기처리를 하려면 자바스크립트 문법이여야 해요! 그래서 런타임에 분기처리할 수 있는 게 제가 알기론 3가지가 있습니다.

1. 속성값 체크 (`in` 연산자)
2. 태그된 유니온 기법 (런타임에 접근 가능한 타입 정보를 명시적으로 저장하는 태그기법)
3. 클래스 (타입과 값을 모두 사용)

속성값은 `in` 연산자를 사용하는 것인데, 보통 객체의 필드값 여부로 타입을 체크하는 것이고, 태그된 유니온 기법(brand)도 속성을 줘서 필드값으로 타입 체크하는 것입니다. 모든 커스텀 에러가 각각 갖는 고유값으로 분기처리를 하는 것보단 하나의 타입으로 뭉쳐서 처리하는 경우가 많기 때문에 클래스를 선택하게 되었습니다.

클래스로는 `instanceof` 를 사용하여 런타임에 타입체크를 할 수 있습니다. `throw new CustomError()` 를 한다면 사용처에서 `if(error instaceof CustomError)` 하는 느낌?? 입니닷!

https://medium.com/@yujso66/%EB%B2%88%EC%97%AD-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%97%90%EC%84%9C-%EC%A0%84%EB%AC%B8%EA%B0%80%EC%B2%98%EB%9F%BC-%EC%97%90%EB%9F%AC-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0-39d14f5cc6a2
https://ko.javascript.info/custom-errors

2024-09-11 15:32 UTC, rbgksqkr commented on frontend/src/utils/error.ts
> +}
오프라인인데 요청을 보내면 발생하는 에러입니다!

2024-09-13 16:35 UTC, merged