[FEAT] 500 에러가 아닌 에러 핸들링하기
woowacourse-teams/2024-ddangkong pull request #266
Opened 2024-09-12 07:49 UTC by leegwichan

## Issue Number
Closed #265 

## As-Is

- Client에서 요청이 잘못된 상황까지 Discord 알람이 온다.

## To-Be

- HttpMediaTypeNotSupportedException, ClientAbortException을 400번대 에러로 처리

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/09454f0d-d8a6-4a31-8ab3-8e7f5425e5c1)

## (Optional) Additional Description

9/12 기준 dev, prod에서 온 알람 (SQL 관련 에러 제외)

### `HttpMediaTypeNotSupportedException`
```text
org.springframework.web.HttpMediaTypeNotSupportedException: Content-Type 'text/plain;charset=UTF-8' is not supported
```

해당 요청의 Content-Type을 지원하지 않는 것이므로 405 Method Not Allowed를 반환함

### `ClientAbortException`
```text
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:341)
    at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776)
    at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:673)
    at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:376)
    at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:354)
```

클라이언트가 서버와의 연결을 갑작스럽게 종료했을 때 발생하는 에러이다.
400 Bad Request를 반환하도록 함

#### `CannotAcquireLockException`
- SQL Lock 관련 문제라서 서버 에러가 맞음

#### `AsyncRequestNotUsableException`
- Spring Framework에서 비동기 요청 처리와 관련된 문제로 발생하는 예외입니다. 이 예외는 주로 Spring MVC에서 비동기 요청을 처리하려고 할 때, 클라이언트 요청이 비동기 방식으로 처리될 수 없는 경우에 발생한다.
- 500 서버 에러로 처리

2024-09-14 15:14 UTC, PgmJun approved these changes
디테일한 처리 고마워요 커찬~!
의견 남겼는데 사소한 거라서 생각해보시고 반영해주셈요 감사합니다!

2024-09-14 15:14 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = {HttpRequestMethodNotSupportedException.class, HttpMediaTypeNotSupportedException.class})
```suggestion
@ExceptionHandler(value = {
        HttpRequestMethodNotSupportedException.class, 
        HttpMediaTypeNotSupportedException.class
    })
```
사소한 의견) 요렇게 잘라줘도 가독성 좋을 것 같네요~!

2024-09-16 08:18 UTC, jhon3242 approved these changes
LGTM~~  수고했어 커찬!

2024-09-19 09:50 UTC, GIVEN53 requested changes
커찬 고생했어요! 코멘트 하나만 확인해주세여

2024-09-19 09:50 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/controller/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = {HttpRequestMethodNotSupportedException.class, HttpMediaTypeNotSupportedException.class})
Media Type Not Supported는 415 status code를 반환한다고 합니다

reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415

2024-09-19 13:28 UTC, GIVEN53 approved these changes
LGTM!

2024-09-23 04:03 UTC, merged