[REFACTOR] 만료된 방 삭제 시, 발생 Delete 쿼리 수 4N -> 4로 변경
woowacourse-teams/2024-ddangkong pull request #275
Opened 2024-09-19 10:18 UTC by PgmJun

## Issue Number
#268 

## As-Is

## To-Be

## Check List
- [ ] 테스트가 전부 통과되었나요?
- [ ] 모든 commit이 push 되었나요?
- [ ] merge할 branch를 확인했나요?
- [ ] Assignee를 지정했나요?
- [ ] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description

2024-09-19 10:53 UTC, leegwichan approved these changes
LGTM~! 👍
RoomFacade에 있는 로직이 잘 응집화되었네요!

2024-09-19 11:44 UTC, jhon3242 requested changes
든든 수고했어용~~ 커멘트 몇개 남겼는데 확인해주세요!

2024-09-19 11:44 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +
사소한 의견) save 보다는 migrateTotalVotes가 더 맞을 것 같아요!

2024-09-19 11:44 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +        List<RoomBalanceVote> deletedRoomVotes = deleteMemberVotes(member);
Ditto

2024-09-19 11:44 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +    }
사소한 의견) 아직 migrate 되지 않은 투표들이니까 migrated는 조금 어색한 것 같아요. 차라리 migrate 될 투표 대상들이니까 targetRoomBalanceVotes 같은 네이밍이 더 맞지 않을까요??

2024-09-19 11:44 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +    }
의견) 다른 migrate 를 prefix로 사용하고 있는 메서드들은 투표를 `복사`한 후 `삭제` 작업까지 해주고 있는데 이 메서드만 `복사` 작업만 하고 있어서 혼동이 올 것 같아요. 혼동을 줄이기 위해 해당 메서드명은 다른 prefix를 사용하는게 좋을 것 같습니다!

2024-09-19 11:44 UTC, jhon3242 commented on backend/src/main/java/ddangkong/facade/room/RoomFacade.java
> +        expiredRoomMigrator.deleteRoomVotes(roomBalanceVotes);
의견) 굳이 facade 레이어에서 두 메서드를 따로 호출할 필요가 없을 것 같아요! 다른 migrate 메서드와 동일하게  migrateRoomVoteToTotalVote 하나의 메서드 안에서 삭제 작업까지 처리하는게 좋을 것 같습니다!

2024-09-19 11:44 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +    }
👍👍 이러면 쿼리를 4개만 날리면 되겠네요 ㄷㄷ 역시 든든

2024-09-22 13:17 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +    }
target 네이밍 좋은데요??

2024-09-22 14:13 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +    }
> 의견) 다른 migrate 를 prefix로 사용하고 있는 메서드들은 투표를 `복사`한 후 `삭제` 작업까지 해주고 있는데 이 메서드만 `복사` 작업만 하고 있어서 혼동이 올 것 같아요. 혼동을 줄이기 위해 해당 메서드명은 다른 prefix를 사용하는게 좋을 것 같습니다!

로직을 다시 한 번 읽어보면서 혼동이 없도록 수정해두었습니다 확인부탁드려요!

2024-09-22 14:15 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/room/balance/roomvote/ExpiredRoomMigrator.java
> +
리팩토링 되면서 메서드들이 좀 더 의도를 명확히 드러내도록 변경되었어요!
확인부탁드립니다!

- migrateExpiredRooms
- migrateMemberVotes
- migrateFinishedRoom

2024-09-22 14:17 UTC, PgmJun commented on backend/src/main/java/ddangkong/facade/room/RoomFacade.java
> +        expiredRoomMigrator.deleteRoomVotes(roomBalanceVotes);
마찬가지로 리팩토링 되면서

```java
@Transactional
    public void resetRoom(Long roomId) {
        Room room = roomService.reset(roomId);
        roomContentService.deleteRoomContents(room);
        roomMigrator.migrateFinishedRoom(room);
    }
```

이런 코드로 변경되었습니다:)
다시 한 번 확인 부탁드려요~!~!

2024-09-22 14:31 UTC, PgmJun reviewed
## 1차 리뷰 이후 변경사항

- migrate 로직 메서드 분리를 통한 세분화된 책임 분리 및 로직 정리
- 애매했던 메서드 네이밍 구체적으로 변경
- 여러 개의 방 정보 마이그레이션 테스트 코드 작성
- Migrator에서 만료, 종료 등 방 정보에 대한 상태 제거 (마이그레이션 역할만 담당하도록 하고, 조건은 Migrator를 호출하는 외부 로직에서 처리)

### 테스트 코드 동작
<img width="832" alt="image" src="https://github.com/user-attachments/assets/a1a47626-a7d2-4d75-a7c3-5f43cc481dba">

2024-09-23 04:35 UTC, jhon3242 approved these changes
명확한 의도를 들어내도록 리팩터링 되었네요!
너무 좋습니다! LGTM~ 든든 수고했어용👍

2024-09-23 11:09 UTC, merged