[REFACTOR] 모달을 Context로 관리하여 사용성 개선
woowacourse-teams/2024-ddangkong pull request #277
Opened 2024-09-20 11:34 UTC by rbgksqkr

## Issue Number
#272 

## As-Is

- 라운드를 넘어갈 때, mutation 에러를 처리할 때 등 사용자에게 알림을 보여줘야할 때 모달을 많이 사용
- 모달을 사용할 때마다 모달 컴포넌트가 해당 컴포넌트에 위치하는 것에 불편함을 느낌
- 에러에 따라 다른 메세지를 보여줘야 할 때 대응 어려움

## To-Be

- 모달을 context로 관리하여 Modal을 관리하는 게 컴포넌트의 역할이 아닌 ModalContext의 역할로 위임
- 함수의 인자로 컴포넌트와 message를 받아 어떤 모달을 어디서든 띄울 수 있도록 구현
- 테스트 코드를 구현해놓고 리팩토링 후에도 정상적으로 동작하도록 개발

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description
## 모달을 Context로 관리

기존에 모달을 사용하려면 모달을 컴포넌트 내부에 위치시키고, 하나의 isOpen 상태를 공유해야 했다.

이러한 문제 때문에 컴포넌트의 역할이 아닌데도 해당 컴포넌트가 의존해야하고, 에러 상황에서만 발생하는 모달도 컴포넌트에 있어야 했다.

또한 title과 message도 동적으로 넘겨주기 어려웠다.

이러한 문제를 Modal을 Context로 관리하고, 함수로 인자들을 받을 수 있도록 설정하여 해결할 수 있었다. 이를 통해 컴포넌트는 성공한 케이스만 갖고 있고, 에러 핸들링도 쉬워져 코드의 전체적인 가독성이 높아졌다.

### ❌ before

```tsx
const GameResult = () => {
  const { isOpen, show, close } = useModal();

  return (
    <>
      ...
      <FinalButton showModal={show} />
      <AlertModal
        isOpen={isOpen}
        onClose={close}
        title="방 초기화 에러"
        message="방을 초기화하는데 실패했어요. 다시 시도해주세요"
      />
    </>
  );
};
```

### ✅ after

```tsx
import FinalButton from '../common/FinalButton/FinalButton';

const GameResult = () => {
  return (
    <>
      ...
      <FinalButton />
    </>
  );
};

export default GameResult;
```

## 🌸 Storybook 배포 주소 

> https://woowacourse-teams.github.io/2024-ddangkong/storybook/

2024-09-23 07:50 UTC, useon requested changes
하이루요 마루 ~ ! ! 해당 작업으로 불 필요한 코드가 엄청 줄었네요 대마루 !!🌟커밋도 잘 나누어져 있어서 보기가 편했답니다 ! Context로 관리를 하게 되는 것 뿐만 아니라 useModal의 유연성과 사용성을 더 높이고 test util 작성 및 테스트 추가까지 꼼꼼 최고 ,, 몇 가지 코멘트 달았으니 편하게 확인해 주시고 답변 주세요오 ~ 수고하셨습니다 🤭👍

2024-09-23 07:50 UTC, useon commented on frontend/src/components/layout/Header/Header.test.tsx
> +  it('방 설정 버튼을 클릭했을 때, 방 설정 모달이 뜬다.', async () => {
# 🌸 칭찬 🌸
모달 개선 작업을 하면서 모달이 뜨는 부분에 대한 헤더 테스트도 추가했군요 !!!!?? 참으로 꼼꼼한 청년 🤭👍

2024-09-23 07:50 UTC, useon commented on frontend/src/hooks/useModal.ts
>  export default useModal;
# 🙏 제안 🙏
useModal이 Modal 컴포넌트 폴더 내에 말고 hooks 폴더에 위치하여 있는 점이 살짝 고민되네요 ! 저는 여러 곳에서 사용되는 훅이 아니라 hooks 폴더 보다는 Modal 폴더 내에 위치하는 것이 더 찾기 편하다 생각하는데 마루 생각은 어떠신가요 ? 🙌

2024-09-23 07:50 UTC, useon commented on frontend/src/pages/NicknamePage/NicknamePage.tsx
> -      />
# 🌸 칭찬 🌸
정말 많은 코드가 이런 식으로 줄일 수 있게 되어 좋아요 🤭👍👍👍 !!!

2024-09-23 07:50 UTC, useon commented on frontend/src/components/common/AlertModal/AlertModal.tsx
> +    onClose();
# 🌸 칭찬 🌸
오 알람 모달과 안내 모달을 하나로 합치면서 확인 함수가 있는 경우에만 onConfirm 동작을 하고 모달이 닫히도록 유연하게 수정이 되었네요 !! 좋은데 ........ ???????? 천재만재.

2024-09-23 07:50 UTC, useon commented on frontend/src/components/common/AlertModal/AlertModal.tsx
> +        {message &&
# 🌸 칭찬 🌸
혹시 메세지가 없는 경우가 있을 수도 있으니 꼼꼼한 처리 ........... 감동.

2024-09-23 07:50 UTC, useon commented on frontend/src/providers/ModalProvider/ModalProvider.tsx
> +  const dispatch = useMemo(() => ({ show, close }), []);
# 💭 질문 💭
해당 부분에 useMemo를 사용하는 이유가 무엇인지 궁금해요 ! 불필요한 리렌더링을 방지하고자 작성하신 걸까요? show와 close에 useCallback을 사용하지 않으면 동일한 참조가 유지 안 되지 않나 하는 생각이 들어서요 !!  제가 useMemo와 useCallback을 많이 사용해 보지 않아서 .. 마루의 맛도리 설명을 기다려요 .. 🫡🙌

2024-09-23 15:33 UTC, novice0840 approved these changes
Modal이 깔끔하게 분리가 잘 되었네요!! 
반복되는 코드들이 있어 코드 양에 비해 리뷰할게 적었던 것 같아요. 크게 신경쓰이는 부분은 없었어서 이번에는 바로 approve 하겠습니다

2024-09-23 17:05 UTC, rbgksqkr reviewed
코멘트 완료했습니다:) 답변 부탁드려용

2024-09-23 17:05 UTC, rbgksqkr commented on frontend/src/providers/ModalProvider/ModalProvider.tsx
> +  const dispatch = useMemo(() => ({ show, close }), []);
# Context API memoization (useMemo vs useCallback)

>불필요한 리렌더링을 방지하고자 작성하신 걸까요?

넵 맞습니다! velopert 님이 작성한 블로그글을 참고하여 "그럴 것 같다" 라고만 생각했는데, 코멘트가 들어온김에 직접 측정하여 useMemo를 적용하지 않은 경우와 적용한 경우를 비교해봤습니다!

>useMemo를 사용하기 때문에 처음 생성한 dispatch 객체에 있는 show와 close 함수는 최초 생성된 함수이고 show와 close 함수는 각각 useCallback을 사용하지 않아 매번 새로운 함수를 참조할텐데 여기서 발생하는 문제는 없을까요?

심신미약 상태라 문장을 제대로 이해하지는 못했지만 메모이제이션이 제대로 되지 않을 것을 우려한 것 같아요 ㅎㅎ
useMemo는 첫번째 인자로 들어오는 함수의 반환값을 리렌더링 간에 캐싱하는 훅, useCallback은 첫번째 인자로 들어오는 함수 자체를 리렌더링 간에 캐싱하는 훅입니다!

useCallback은 테스트해보니 큰 효과가 없었어요! 궁금해서 이유를 생각해보니 setState가 발생하면 리렌더링이 발생하여 컴포넌트 내의 코드가 다시 실행될텐데, dispatch가 매번 새로운 객체를 만드니까 참조하는 컴포넌트도 리렌더링이 일어나는 것으로 보입니다! context로 내려주는 dispatch는 useMemo로 반환값인 { show, close } 를 캐싱한 것이고, 의존성 배열이 빈 배열이므로 그대로 반환하게 되는 것이죠!

### 성능 실험

useMemo를 적용하지 않은 경우 modal을 열거나 닫을 때 이를 참조하는 컴포넌트들이 리렌더링됩니다.
왼쪽 이미지를 보시면 RoomSettingHeader와 ReadyMembersContainer에서 show 함수를 참조하고 있기 때문에 리렌더링이 발생하였습니다.
이와 달리 useMemo를 적용한 오른쪽 이미지는 Provider만 리렌더링된 것을 확인할 수 있습니다.

**useMemo X / useMemo O**

<img width="350" alt="useMemo 적용x" src="https://github.com/user-attachments/assets/8d976a3f-06a5-42c8-8425-aa3280f78bee"> <img width="350" alt="useMemo 적용o" src="https://github.com/user-attachments/assets/6aa53d97-6669-4766-abc7-2937f9bfda7a">

**useCallback**

<img width="500" alt="useCallback" src="https://github.com/user-attachments/assets/db553013-7371-47e4-bd4e-fe2fc414090a">


[다른 사람들이 안 알려주는 리액트에서 Context API 잘 쓰는 방법 - velopert](https://velog.io/@velopert/react-context-tutorial#%EA%B0%92%EA%B3%BC-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-%ED%95%A8%EC%88%98%EB%A5%BC-%EB%91%90%EA%B0%9C%EC%9D%98-context%EB%A1%9C-%EB%B6%84%EB%A6%AC%ED%95%98%EA%B8%B0)

2024-09-24 05:04 UTC, rbgksqkr commented on frontend/src/components/common/FinalButton/FinalButton.test.tsx
> +    });
오호 중복해서 사용되고 있긴 하네용 다만 개인적으로 중복을 줄이는 것도 좋지만 가독성과 직관적인 것도 중요하다고 생각합니다! 그래서 expect문을 중복을 줄이기 위해 추상화하는 게 테스트 코드의 유지보수를 용이하게 만들지는 고민해봐야겠네용
함수명을 잘 지어도 그 안에 어떤 expect문이 있는지는 한번더 확인해야 알 수 있다고 생각합니다. 추후에 프로덕션 코드가 변경되었을 때 찾기 어려울 거라고 생각이 들었어요! 어떻게 생각하시나요??

2024-09-25 07:25 UTC, useon commented on frontend/src/hooks/useModal.ts
>  export default useModal;
오 ... 너무나도 설득력 있는 주장이군요 !!! 마루가 왜 거기에 위치시켰는지 단번에 이해했습니다 ^ .^ 저도 좋네요 !

2024-09-25 07:25 UTC, useon commented on frontend/src/components/common/AlertModal/AlertModal.tsx
> +    onClose();
좋아요 해당 UI가 생기게 된다면 그때 고민해 봅시다 ^^

2024-09-25 07:30 UTC, useon commented on frontend/src/providers/ModalProvider/ModalProvider.tsx
> +  const dispatch = useMemo(() => ({ show, close }), []);
이렇게 성능 실험한 내용을 보여주니 useMemo를 왜 사용했는지 확실히 와 닿는 것 같아요 !!!!! useCallback에 대한 코멘트도 남겼는데 직접 적용해 보시고 알려주셔서 정말 따봉입니다요 🤭👍👍👍

2024-09-25 07:35 UTC, useon approved these changes
이미지와 읽어보면 좋을 아티클까지 첨부하신 정성스런  답변 최고입니다요 .. 🤭 코멘트 확인 후 어프루브 드립니다 !!! 고생많았숨니다 ^___^ 이거 머지되면 제 파트 에러 처리하려 합니다 두근세근..

2024-09-26 03:20 UTC, rbgksqkr commented
[ 추후 개선 사항 ]
- mutation 또는 query에 타입 모두 명시할 것인지?
  - 할거면 다 명시하고, 안하면 다 빼는 게 맞을 것 같아요!

2024-09-26 04:11 UTC, merged