[FEAT] 대기방 UI 수정 및 런칭 데이 피드백 반영
woowacourse-teams/2024-ddangkong pull request #288
Opened 2024-09-24 08:35 UTC by novice0840

## Issue Number

#274 

## As-Is

- 런칭 데이 피드백을 기반으로 "대기방 페이지" UI 수정
- Modal이 off 된 후에 다시 스크롤이 생기는 버그가 있었음

## To-Be

- [x]  닉네임 입력 시, 화면이 확대되지 않도록 한다. 
- [x] 초대하기 버튼 UI 수정
- [x] 라운드와 타이머를 카테고리와 함께 표시
- [x] 총 인원 글씨 키우기, 버튼에 참여 인원 표시 
- [x] 닉네임 페이지에서 키보드가 올라가면 "참가 버튼"도 같이 올라간다. 
- [x] 카테고리 영역 클릭 시 카테고리 변경 가능 
- [x] 나가기 버튼 클릭 시 최종 확인 모달 띄우기 
- [x] 모달 on 되면 없어졌던 스크롤이 다시 생기는 버그 해결

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

피드백 반영 후 대기방 UI 
![image](https://github.com/user-attachments/assets/73413e2c-54b7-4aad-a4bd-f2db5920b022)

## (Optional) Additional Description

2024-09-25 04:47 UTC, rbgksqkr requested changes
고생하셨습니다 포메~! 사소한 질문과 제안사항 몇가지 남겨봤습니다 확인부탁드려요:)
개인적으로는 UI에 라운드랑 타이머가 저렇게 크게 위치하는 것보단 하단에 작게 작성된 UI를 선호하는 것 같아요 ㅎㅎ 또 타이머도 보여줄거면 초단위로 바꿔야한다고 생각합니돠 UI는 디자인적인 부붕니라 고민을 같이 해봐야겠네용
그리고 useKeyboardUp을 모바일에서 확인하기가 어려워서 화면녹화를 올려주시면 감사하겠숩니다!

2024-09-25 04:47 UTC, rbgksqkr commented on frontend/src/pages/NicknamePage/NicknamePage.tsx
> +      nicknameInputRef.current.focus();
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
이건 어떻게 동작하는 로직인가요??

2024-09-25 04:47 UTC, rbgksqkr commented on frontend/webpack.config.dev.js
> +    open: true, // 개발 서버 시작 시 자동으로 브라우저 열기
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
있어도 괜찮은 것 같네용 이것도 주석 지워도 될 것 같아요!!

2024-09-25 04:47 UTC, rbgksqkr commented on frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
> +const randomNickname = createRandomNickname();
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
오 이러면 한번만 랜덤 닉네임 설정하겠네용
그런데 서비스가 켜져있는 상태에서 다시 방을 만들면 랜덤 닉네임이 안바뀔 것 같긴 한데, 그런 케이스가 거의 없어서 크게 상관 없을 것 같아용

2024-09-26 03:51 UTC, novice0840 reviewed
피드백 반영했습니다! 그 useKeyboard는 휴대폰에서만 동작하는 기능이라서 화면 녹화가 힘들어 못했네요 ㅠ 

이 기능은 직접 보여주는게 좋을 것 같아요

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/components/CategoryContainer/CategoryContainer.tsx
> +        onClick={isMaster ? show : () => {}}
방장이 아니면 show 함수 자체가 전달이 안 되서 disabled를 굳이 사용하지 않아도 된다고 판단했습니다! 
스타일을 수정할 수 있긴 한데 이미 다른 곳에서는 disabled를 스타일 수정 없이 사용하고 있어서 일관성이 떨어진다고도 생각했어요

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/components/CategoryContainer/CategoryContainer.tsx
> +          <h1 css={subtitle}>{roomSetting.totalRound}</h1>
h1은 제목을 나타내는 태그라서 페이지에 하나만 있어야 되는군요! 
생각해보니 라운드 / 카테고리 / 타이머는 같은 레벨인 것 같아서 같은 태그로 수정해 주었습니다

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
> +import { RefObject, memo } from 'react';
memo를 사용했다가 지웠었는데 import를 지우는 걸 깜빡한 것 같아요. 지웠습니다!

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/hooks/useKeyboardUp.ts
> +export const useKeyboardUp = () => {
수정했습니다!

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/hooks/useKeyboardUp.ts
> +      window.addEventListener('remove', handleResize);
` window.addEventListener('remove', handleResize)`는 제가 잘못 적어서 `window.removeEventListener('resize', handleResize)`로 수정했어요! 

모바일 브라우저에서 키보드가 위로 올라가면 `resize` 이벤트가 발생합니다!

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
> +const randomNickname = createRandomNickname();
닉네임이 컴포넌트가 re-rendering이 될 때 마다 랜덤 닉네임이 바뀌더라고요. 그래서 안 바뀌도록 컴포넌트 밖에서 선언해주었습니다!

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/pages/NicknamePage/NicknamePage.tsx
> +      nicknameInputRef.current.focus();
첫 페이지 시 닉네임이 focus가 되도록 하는 동작인데 생각해 보니 그냥 HTML의 기본 기능을 쓰면 될 것 같아서 수정했습니다!

2024-09-26 03:51 UTC, novice0840 commented on frontend/src/pages/NicknamePage/NicknamePage.tsx
> +      nicknameInputRef.current.focus();
저 autofocus로 수정했는데 저희 eslint 컨벤션에서 autofocus는 사용성과 접근성이 떨어져서 
금지하고 있네요.... 다시 되돌렸습니다

2024-09-26 04:32 UTC, useon approved these changes
포메 ~~ 여러 피드백을 반영하시느라 고생많았어요 !!! 몇 가지 코멘트 남겼으니 확인해 주시고 답변주세요 !!!!! 그리고 대기방에 카테고리를 보여주는 디자인을 함께 고민해 보면 좋을 것 같아요 !!!!! 일단 어프루브 드립니다 🌞✨

2024-09-26 04:32 UTC, useon commented on frontend/src/components/CategoryContainer/CategoryContainer.test.tsx
> +      const roomSetting = screen.queryByText('방 설정');
# 💭 질문 💭
저도 같은 문제를 겪어서 다른 방식으로 해결했는데 queryByText로 하면 찾아지던가요 ?? 저는 이것도 안 됐어서 🥹🥹 혹시 한 스크린에 '방 설정'이 있고 '방'이 있는 경우 여러 엘리멘트가 잡힌다는 에러는 뜨지 않는지도 궁금하네요 .. 이건 차차 답변해 주셔도 괜찮습니다 !!!!

2024-09-26 04:32 UTC, useon commented on frontend/src/components/CategoryContainer/CategoryContainer.tsx
> +          <span css={roomSettingLabel}>타이머</span>
# 🙏 제안 🙏
제한 시간으로 명시가 더 적절할 것 같은데 포메 생각은 어떠신가요 ?!!?

2024-09-26 04:32 UTC, useon commented on frontend/src/components/CategoryContainer/CategoryContainer.tsx
> +          <h1 css={subtitle}>{roomSetting.timeLimit}</h1>
# 🙏 제안 🙏
초 단위로 표시되면 보기 편할 것 같아요! RoomSettingContainer 참고하시면 좋을 듯 합니다!!!!

2024-09-26 04:32 UTC, useon commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.styled.ts
>  export const inviteButton = css`
# 🙏 제안 🙏
화면에서 확인해 보았을 때 연하다는 느낌이 있어, 초대 버튼의 글자를 bold로 처리해주면 더 잘 보일 것 같아요!

2024-09-26 05:01 UTC, novice0840 reviewed
썬데이 피드백 답변 남겼습니다!

2024-09-26 05:21 UTC, novice0840 commented on frontend/src/components/CategoryContainer/CategoryContainer.tsx
> +          <h1 css={subtitle}>{roomSetting.timeLimit}</h1>
초 단위로 변경했습니다!

2024-09-26 05:38 UTC, rbgksqkr approved these changes
굿굿 반영사항 확인했습니다!!!

2024-09-26 05:40 UTC, merged