[FEAT] 매칭 결과 페이지 피드백 반영
woowacourse-teams/2024-ddangkong pull request #289
Opened 2024-09-24 16:47 UTC by useon

## Issue Number
#273 

## As-Is

매칭 결과 페이지에 대한 설명이 없으니 어떤 내용인지 파악하기 힘들다는 유저 피드백

## To-Be

- [x] 게임 결과를 매칭 결과로 텍스트 수정 및 설명 추가
- [x] 매칭 인원이 8명 이상인 경우 화면 잘리는 문제 개선
- [x] 매칭도 바의 길이보다 닉네임 길이가 긴 경우 개선 
- [x] 숫자가 두 자리인 경우 정렬 어긋남 개선
- [x] 스크롤바를 없애고 플로팅 버튼으로 스크롤이 가능함을 인지하도록 개선

## Check List
- [ ] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description
# 1. 게임 결과를 매칭 결과로 텍스트 수정 및 설명 추가
![image](https://github.com/user-attachments/assets/d164230d-898c-4e4e-9798-c73e58258c0d)
- 해당 과정에서 매칭 결과에만 사용되는 빈 헤더를 매칭 결과 헤더로 수정하여 사용했습니다.
# 2. 매칭 인원이 8명 이상인 경우 화면 잘리는 문제 개선
https://github.com/user-attachments/assets/4e1f8fb3-d56a-4389-889c-d092f56b959b
- 매칭도가 그려지는 영역(전체 화면 길이 - 헤더 길이 - 버튼 길이)을 주고 원래 적용되어 있던 스타일 때문에 원하는 위치와 크기만큼 잡히지 않아서 스타일을 수정했습니다.
# 3. 매칭도 바의 길이보다 닉네임 길이가 긴 경우 개선 
![image](https://github.com/user-attachments/assets/559bcdb6-98e9-4fe7-ab86-70d1c978cfbe)
- 원래 word-break: auto-phrase 속성을 사용하여 매칭 바 안에 위치시키면서 단어가 아닌 글자여도 줄바꿈이 일어나도록 하고 싶었어요. 하지만 사파리에서 지원하지 않는 문제가 있었고, 통일성을 지키는 것이 좋다고 생각해서 위처럼 개선했습니다.
<img src="https://github.com/user-attachments/assets/259716a2-983f-46a9-9ccd-b7cf5512f9b9" width='300' ><img src="https://github.com/user-attachments/assets/9425a32c-6e35-475a-80ee-1e66d668f414" width='500'  height='300'>
# 4. 숫자가 두 자리인 경우 정렬 어긋남 개선
![image](https://github.com/user-attachments/assets/f181a0e9-b849-48db-b91a-571f3164a4d6)
# 5. 스크롤바를 없애고 플로팅 버튼으로 스크롤이 가능함을 인지하도록 개선
https://github.com/user-attachments/assets/411a40ea-1cd9-474a-b5ed-6656439bae41
- 스크롤바를 원하는 대로 커스텀 하고자 했지만 브라우저마다 다르게 보이고, 모바일 환경에서 이미 좁은 간격에 스크롤바가 생기니 더 좁게 느껴졌어요. 따라서 플로팅 버튼으로 스크롤 할 수 있음을 사용자에게 인식시키고 버튼을 눌렀을 때도 스크롤이 되도록 구현했습니다.
- 첫 로드 시 스크롤이 생기는 컨텐츠의 길이라면 하단 플로팅 버튼이 생깁니다.
- 최상단 도달시 상단 플로팅 버튼 사라지고 최하단 도달시 하단 플로팅 버튼 사라집니다.
- UI를 가리지 않을까 하는 우려를 투명도를 높여 닉네임이 최대한 안 가리는 방식으로 구현했습니다.
- 색상은 땅콩이 연한 버전으로 골라보았습니다 😆

2024-09-25 05:34 UTC, rbgksqkr requested changes
고생하셨습니다 썬데이~!~ 피드백 반영 중에도 UI나 UX 측면의 디테일한 부분들을 신경써줘서 너무 좋네용 몇가지 코멘트와 질문 남겼으니 확인부탁드려요 :)

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/GameResult.styled.ts
> +  z-index: 1000;
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
zindex를 1000으로 설정한 이유가 있을까요??

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/GameResult.styled.ts
> +  position: fixed;
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
top과 bottom에 10%, 15% 으로 뒀는데 화면 높이에 따라 다른 간격이 될 수도 있을 것 같아요! 그래서 fixed 대신 absolute로 처리하는 건 어떤가요??

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/hooks/useScrollControl.ts
> +        top: resultContainerRef.current.scrollHeight,
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
오호 해당 로직 동작이 궁금합니다! 함수명으로 맨하단 스크롤인 건 이해했는데, resultContainer가 스크롤된만큼 스크롤을 내리는 걸까요??

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    if (!container) return;
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
이 부분에서도 container가 사용되는 건가요??

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    if (!container) return;
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
container가 값이 없는 경우도 있는건가요?? 만약 항상 존재하는건데 ref 특성상 DOM 을 인식하지 못하는 경우라면 타입 단언을 사용하는 게 어떤가요? container 값에 따라 얼리 리턴하는 형태가 살짝 어색하다고 느껴지네용 어떻게 생각하시나요??
```tsx
const container = resultContainerRef.current as HTMLDivElement;
```

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +  }, [initialDelay]);
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
container의 높이를 계산할 때 delay를 주는 이유는 무엇인가요?? 추측으로는 ref값이 처음에 null이여서 컴포넌트를 그리고 해당 로직이 실행되도록 하려는 거였을까요? 엇 그럼 delay를 넘겨주는 의미가 없어지긴 하네요 엇 로직 흐름이 궁금합니다!

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/layout/Header/Header.tsx
> -export const EmptyHeader = () => <header css={headerLayout()}></header>;
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
빈 헤더 없앤거 좋네용

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/layout/Header/Header.tsx
> +      <h2 css={matchingResultCaption}>매칭도를 통해 당신과 가장 잘 맞는 사람을 알아보세요😊</h2>
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
텍스트가 모바일로 보면 잘 안보일 것 같은데 bold를 주는 건 어떤가용

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/mocks/data/finalResult.json
>    "matchedMembers": [
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
모킹 미쳐따 ㄴㅇㅅㄴㅇㅅ

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    setIsAtBottom(scrollTop + clientHeight >= scrollHeight - 1);
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
이건 어떤 계산을 의미하는 걸까요??

2024-09-25 05:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    handleScroll();
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
뭔가 이벤트 리스너에 콜백함수를 추가하는 부분이랑 바로 호출하는 부분이 같이 있는 게 어색하게 느껴지는 것 같아요! handleScroll의 setState를 하기 위해 호출한 것처럼 보여요. 

그런데 어떤 상황에서 호출이 필요한지 궁금합니다! 초기값 설정이라면 다른 페이지를 이동했다가 돌아오는 형태도 아니여서 isAtTop은 true, isAtBottom은 false로만 해도 될 것 같다는 생각이 드네용 어떻게 생각하시나요???

필요한 호출이라면 useEffect를 따로 분리하는 것이 좋다고 생각합니다!

2024-09-25 09:44 UTC, novice0840 requested changes
UI가 이쁘게 잘 구현되었네요 ㅎㅎ

코드 잘 읽고 피드백 남겼습니다 !

2024-09-25 09:44 UTC, novice0840 commented on frontend/src/components/GameResult/hooks/useScrollControl.ts
> +        top: resultContainerRef.current.scrollHeight,
# 🙏 제안 🙏
함수 이름은 스크롤을 바닥까지 내린다고 생각이 되는데 실제 구현 동작은  `resultContainerRef` 태그의 스크롤 높이만큼 Top을 주는 방식이니까 다소 안 맞는 부분이 있다고 생각해요. 

resultContainerRef라는 특정 컴포넌트 이름보다는 조금 더 넓은 의미로 `component` 이런 식으로 지어도 괜찮지 않을까요?

2024-09-25 09:44 UTC, novice0840 commented on frontend/src/components/GameResult/GameResult.tsx
> +        )}
# 🙏 제안 🙏
각 컴포넌트마다 조건문이 다양해서 어떤 상황에 어떤 UI가 그려지는지 코드만 보고 한 눈에 알기가 어려울 수 있을 것 같아요.
early return을 사용해서 isLoading 조건과 existMatching 조건을 미리 처리해주면 
남은 부분이 더 깔끔해 질 것 같은데 어떻게 생각하세요?

2024-09-25 09:44 UTC, novice0840 commented on frontend/src/components/layout/Header/Header.tsx
> +      <h2 css={matchingResultCaption}>매칭도를 통해 당신과 가장 잘 맞는 사람을 알아보세요😊</h2>
# 🌸 칭찬 🌸
요구사항 반영 굿굿

2024-09-25 09:44 UTC, novice0840 commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    }, initialDelay);
# 💭 질문 💭
1초 간격을 두는 이유가 있나요?

2024-09-25 09:44 UTC, novice0840 commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    handleScroll();
# 💭 질문 💭
매 스크롤 마다 이벤트가 발생되면 아마 함수가 굉장히 많은 횟수가 실행될 것 같은데 
debounce로 handleScroll 함수의 실행 횟수를 줄여줄 필요는 없을 까요?

2024-09-26 04:34 UTC, useon commented on frontend/src/components/GameResult/GameResult.styled.ts
> +  height: calc(100vh - 15vh - 7.2rem);
오 좋네요 !!!! 추가해둘게요 ^.^

2024-09-26 05:54 UTC, useon commented on frontend/src/components/GameResult/GameResult.styled.ts
> +  position: fixed;
화면 높이에 따라 다른 간격을 우려하신 것 같아요 ! 
fixed인 경우는 이렇게 나타납니다 ! (원래 코드)
- 아이폰 SE
![image](https://github.com/user-attachments/assets/387fc580-cc84-4043-a4e5-9a53757a7932)
- 아이폰 12 pro
![image](https://github.com/user-attachments/assets/ddb20d88-7bc1-4b9c-a4fa-6ffa937908b5)
- 노트북 화면 기준
![image](https://github.com/user-attachments/assets/b81b5b34-0452-498e-999d-670676b0c68d)
개발 시 차이가 별로 없어서 fixed로 두긴 했었는데 어떻게 생각하세요 마루 ?!

2024-09-26 06:01 UTC, rbgksqkr commented on frontend/src/components/GameResult/GameResult.styled.ts
> +  position: fixed;
아이폰 SE랑 노트북이랑은 좀 차이가 있어보이긴하는데, 차이가 별로 없다고 하면 안나긴 하네용
저는 유지보수 관점에서 보면 왜 같은 간격이 아니지?!? 라는 생각이 들 수 있을 것 같아 낸 의견이였습니당

2024-09-26 06:04 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollControl.ts
> +        top: resultContainerRef.current.scrollHeight,
scrollToBottom 함수에서 resultContainerRef.current.scrollTo({ top: resultContainerRef.current.scrollHeight, behavior: 'smooth' }) 코드를 통해, 스크롤의 top 위치를 scrollHeight로 설정하고, 이를 통해 요소의 맨 아래까지 바로 이동하게 됩니다.

따라서 스크롤만큼 이동하는 것이 아니라 버튼을 누르면 최상단/최하단으로 이동합니다. 
이렇게 작성한 이유는 최대 게임 인원 수가 12명이라서 매칭 결과 길이가 그렇게 길지 않을 것으로 판단했고 버튼 한번만 누르면 바로 모든 매칭을 확인할 수 있어 편하지 않을까 생각했습니다. 또한 스크롤이 되므로 그냥 위 아래로 스크롤 내릴 수 있으니 버튼에는 조금 더 간편하게 스크롤을 사용할 수 있도록 했습니다 !

2024-09-26 06:24 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    if (!container) return;
container가 할당되지 않는 경우를 확인하고, container에 이벤트 리스너를 등록하는 다음 동작을 실행하기 위해서 작성되었습니다 !

2024-09-26 06:29 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    if (!container) return;
아하 마루 의견대로 타입 단언을 사용할 수도 있겠군요 ! 반영하여 수정했습니다 ^.^

2024-09-26 06:33 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +  }, [initialDelay]);
처음 데이터를 불러올 때 정해진 영역보다 컨텐츠의 길이가 긴 경우 바로 하단 플로팅 버튼을 띄우기 위함입니다 !

2024-09-26 06:34 UTC, rbgksqkr commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    if (!container) return;
아하 컨테이너에 이벤트를 다는거군요! 오호오호

2024-09-26 06:35 UTC, useon commented on frontend/src/components/layout/Header/Header.tsx
> +      <h2 css={matchingResultCaption}>매칭도를 통해 당신과 가장 잘 맞는 사람을 알아보세요😊</h2>
좋아요 !! 수정했습니다 ^_______^

2024-09-26 06:39 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    setIsAtBottom(scrollTop + clientHeight >= scrollHeight - 1);
최하단에 도달한 것을 인식하지 못하는 문제가 있더라고요 .. 해당 조건을 주니 제대로 인식되었습니다 🥹

2024-09-26 06:39 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    handleScroll();
추후 리팩토링 해 보도록 할게요 !!!!

2024-09-26 06:40 UTC, useon commented on frontend/src/components/GameResult/GameResult.styled.ts
> +  background-color: #f7d7b4db;
전역 변수에 만들어 놓은 값이 아니고 이번에 새로 추가되었습니다 ! 아직 여러 곳에서 사용하지 않고 플로팅 버튼에만 사용하고 있는 색상 + 투명도라서 추후에 여러 곳에서 사용된다면 분리해 볼게요 !!!

2024-09-26 06:42 UTC, useon commented on frontend/src/components/layout/Header/hooks/useRoutePath.ts
> +    isMatchingResultPage: currentPath.isMatchingResultPage,
저도 이 부분에 대해 고민을 했는데요. 한번 잡고 바꿔야 할 것 같아서 현재는 새로 추가되거나 수정된 로직 위주로만 수정했습니다 ! 너무 많은 파일 체인지와 예상하지 못하게 꼬일 것을 우려했어요 추후 이런 식으로 이름이 변경된 대상들을 한 번에 바꿔야 할 것 같아요 🥹!

2024-09-26 06:44 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollControl.ts
> +        top: resultContainerRef.current.scrollHeight,
함수의 이름대로 버튼을 클릭하면 매칭 결과의 최하단으로 이동하게 됩니다 !!! 스크롤하는 만큼 이동도 가능하고 플로팅 버튼을 누르면 매칭 결과의 최상단과 최하단으로 이동할 수 있습니다. 🤭🤭

2024-09-26 06:44 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    }, initialDelay);
처음 데이터를 불러올 때 정해진 영역보다 컨텐츠의 길이가 긴 경우 바로 하단 플로팅 버튼을 띄우기 위함입니다 !

2024-09-26 06:44 UTC, useon commented on frontend/src/components/GameResult/GameResult.tsx
> +        )}
추후 리팩토링시 반영해 보겠습니다 ^,^

2024-09-26 06:45 UTC, useon commented on frontend/src/components/GameResult/hooks/useScrollState.ts
> +    handleScroll();
그럴 수 있겠군요 ! 추후 리팩토링 시 반영해 보도록 하겠습니다 ^ .^

2024-09-26 07:48 UTC, novice0840 approved these changes

2024-09-26 07:49 UTC, rbgksqkr approved these changes
마지막까지 피드백과 코멘트 반영하기 위해 정성껏 코드 작성해줘서 고생하셨습니다!!!!!@!@ 어프루브!!!!!!

2024-09-26 07:56 UTC, merged