Refactor/#322
woowacourse-teams/2024-ddangkong pull request #326
Opened 2024-10-10 09:33 UTC by novice0840

## Issue Number

#322 

## TODO ✅
- [x] 방 정보 한 번에 읽기 
- [x] 대기방에 참여 중인 멤버가 바뀔 때 바뀐 총 인원 읽어 주기
- [x]  방 정보 변경 시 다시 방 정보 읽음 
- [x] 닉네임 페이지에서 닉네임 Input에 focus 시 `닉네임 입력` 메세지 읽어주기  
- [x] 방 나가기 버튼 클릭 시 확인 modal 
- [x] 아이콘 화질 저하 문제 발생해 확장자 svg로 변경  

## As-Is

1. 스크린 리더기가 카테고리 박스에 접근 시 구체적인 `방 정보`를 읽지 못함
2. 대기방에 멤버가 들어오거나 나간 경우 변경을 감지하지 못함
3. 방장이 `방 정보` 변경 시 멤버들이 변화를 감지 못함
4. 닉네임 Input에 focus가 되어도 스크린 리더기에서 인지하지 힘든 상황

## To-Be
1.  스크린 리더기가 `방 설정 컴포넌트`에 접근 시 `타이머`, `카테고리`, `총 인원`을 한 번에 읽는다
2. align-live를 사용해 `총 인원`의 변경을 감지한다
3.  `방 설정 컴포넌트`에 align-live를 사용하여 변경 사항이 있을 경우 감지한다
4. 닉네임 Input에 focus가 되면 `aria-label`을 통해 `닉네임 Input`인 것을 읽는다. 

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description

2024-10-11 15:00 UTC, useon requested changes
안녕하세요 폼에 ~ 닉네임 설정 페이지와 대기방 페이지의 주요 개선을 빠르게 해 주셔서 감사합니다 !!!! 👏👏 몇 가지 코멘트 남겼으니 확인해 주셔요 !! 생각보다 논의 할 내용이 계속 생기네요 쉽지 않은 이 작업 .. 🤭 답글 달아주시면 다시 오겠습니다 ! 파이팅팅 ~~~ 🌞

2024-10-12 08:44 UTC, rbgksqkr requested changes
고생하셨습니다 포메~!~ 빠르게 접근성 개선 작업 해주셨네요 👍👍👍 접근성은 뭔가 디자인같은 느낌이라 개인 취향에 따라 다른 것 같아 어려운 것 같아요ㅜ
PR 내용을 자세히 작성해주셔서 개선 작업에 대해 이해하기 편했습니다! 다만, 스크린리더 음성을 확인하기 위한 영상인데 음성이 제대로 들리지 않아서 반영 내용을 파악하기 어려웠어요ㅠ 몇가지 코멘트 남겨봤는데 확인 부탁드려요:) 

그리고 닉네임 페이지도 작업한 것 같은데 PR 제목에도 해당 내용 포함시켜서 컨벤션 맞춰서 바꿔주면 좋을 것 같아요! `ex) [REFACTOR] 대기방 페이지 및 닉네임 페이지 스크린 리더기 개선`

고생하셨습니다 포메 🔥🔥🔥

2024-10-12 08:44 UTC, rbgksqkr commented on frontend/src/components/GameResultItem/GameResultItem.tsx
> +          <img src={SillyDdangkongMedium} alt="사용자 프로필" css={profileImage} />
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
2개의 이미지로 분리한 건 좋은 것 같은데 small을 따로 사용하고 있지 않은 것 같아요! 반영되지 않은 걸까요?

2024-10-12 08:44 UTC, rbgksqkr commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
> +                <img src={SillyDdangkongMedium} alt="사용자 프로필" css={profileImage} />
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
사용자 프로필 이미지를 스크린 리더로 읽도록 설정한 이유가 궁금합니다! 닉네임에 대한 정보만 궁금하지 않을까요??

2024-10-12 08:44 UTC, rbgksqkr commented on frontend/src/components/layout/Header/Header.tsx
> +        {/* <ExitIcon /> */}
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
주석은 제거해도 될 것 같아요!

2024-10-12 08:44 UTC, rbgksqkr commented on frontend/src/components/TabContentContainer/TabContentContainer.styled.ts
> +export const RoomSetting = css`
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
팀 컨벤션에 따라 카멜 케이스가 좋을 것 같아요! 그런데 두 옵션명만 담고 있는 것 같은데 네이밍이 살짝 어색한 것 같아요

2024-10-12 08:44 UTC, rbgksqkr commented on frontend/src/components/layout/Header/Header.tsx
> +  };
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
반영 굿굿

2024-10-12 08:44 UTC, rbgksqkr commented on frontend/src/components/RoomSetting/RoomSetting.tsx
> +      />
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
읽어주는 순서를 바꿔보는 건 어떤가요? 카테고리가 가장 중요하다는 생각이 들었습니다! 그리고 텍스트마다 끊어서 읽어주는 게 좋을 것 같아요
```tsx
      <A11yOnly
        aria-live="polite"
      >
      방 설정.
      카테고리.{roomSetting.category.label}. 
      라운드.{roomSetting.totalRound}라운드.
      타이머.{roomSetting.timeLimit / 1000}초.
     </A11yOnly>
```

2024-10-12 08:44 UTC, rbgksqkr commented on frontend/src/components/RoomSetting/RoomSetting.tsx
> +      />
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
button에 label 달아주면 하위 요소는 안읽는걸로 아는데 A11yOnly 컴포넌트를 사용한 이유가 궁금합니다! 제가 잘못 알고 있는거라면 말씀해주세요!

2024-10-13 12:19 UTC, novice0840 commented on frontend/src/components/RoomSetting/RoomSetting.tsx
> +      />
내부에 넣은 텍스트가 리더기에서 읽히는지 `명시적`으로 알기가 힘들어
aria-label 속성을 사용하여 `리더기 전용 텍스트`를 나타내고 싶어 사용했습니다.

2024-10-13 12:24 UTC, novice0840 commented on frontend/src/components/RoomSetting/RoomSetting.tsx
> +      />
읽는 순서 변경했습니다! 
오 `.`을 사용하면 텍스트를 끊어서 읽을 수가 있군요. 

`방 설정` 버튼을 별도로 만들어서 읽어주고 싶었습니다. 방 정보가 텍스트가 생각보다 많아 
우선 방 정보를 리더기로 읽고 이 방 정보를 바꾸고 싶으면 `방 설정` 버튼을 클릭하도록 하는 것이 
사용자 편의성이 좋다고 생각했습니다.

2024-10-13 12:39 UTC, novice0840 commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
>                  <span>{member.nickname}</span>
이미지가 `왕관`인데 대체 텍스트가 `방장`이 되어버리면 이미지와 텍스트가 서로 불일치하게 되지 않을까요?

2024-10-13 12:41 UTC, novice0840 commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
> +        <div aria-live="polite">총 인원 {members.length}명</div>
어 제 폰에서는 `총 인원 5명` 한 번에 읽히는데 `아이폰`에서는 다르게 읽히나요?

2024-10-13 12:51 UTC, novice0840 commented on frontend/src/components/ExitModal/ExitModal.tsx
> +const ExitModal = ({ isOpen, onClose }: ExitModalProps) => {
AlertModal이 있군요! 이걸 사용하면 굳이 없어도 되겠네요!!

2024-10-13 13:55 UTC, novice0840 commented on frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
> +        aria-label="닉네임 입력"
저도 한 번 카카오톡 오픈 채팅방 리더기로 확인해 봤는데 20자를 입력하면 `최대 길이에 도달했습니다`라는 알람이 나오더라고요. 아마 안드로이드에서만 나오는 것 같아요. 

매 글자 입력할때 마다 `닉네임 입력`이라는 메세지가 나온다고 하셨는데 이것 역시 안드로이드에서는 안나오네요 ㅎㅎ....

최대 길이에 도달했을 때 알려주는 기능은 필요할 것 같아서 `입력 길이 === 최대 길이` 인 경우에 aria-label을 통해 최대 길이에 도달했다는 메세지를 읽도록 변경해주었습니다.

2024-10-13 14:00 UTC, novice0840 commented on frontend/src/components/layout/Header/Header.tsx
> +        {/* <ExitIcon /> */}
제거했습니다!

2024-10-13 15:02 UTC, novice0840 commented on frontend/src/components/GameResultItem/GameResultItem.tsx
> +          <img src={SillyDdangkongMedium} alt="사용자 프로필" css={profileImage} />
원래 맨 처음에 Small 을 사용 했었는데 사이즈를 너무 줄인 건지 화질이 떨어지더라고요. 그래서 Medium으로 변경했습니다.

2024-10-13 15:54 UTC, novice0840 commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
> +                <img src={SillyDdangkongMedium} alt="사용자 프로필" css={profileImage} />
웹 접근성 가이드라인대로 의미를 전달하는 이미지가 아니기 때문에 `alt=""`로 수정했습니다!

2024-10-16 02:25 UTC, rbgksqkr reviewed
접근성 회의한 내용 반영하고 머지하면 될 것 같습니당 수고하셨습니다:)

2024-10-16 02:25 UTC, rbgksqkr commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
> +        <div aria-live="polite">총 인원 {members.length}명</div>
<img width="400" alt="image" src="https://github.com/user-attachments/assets/d8ecb483-184b-4388-9dda-ab398db550c1">

2024-10-16 02:25 UTC, rbgksqkr commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
> +                <img src={SillyDdangkongMedium} alt="사용자 프로필" css={profileImage} />
<img width="400" alt="image" src="https://github.com/user-attachments/assets/f81c7ce1-a256-4cb6-bc14-7c1352c40efa">

2024-10-16 02:25 UTC, rbgksqkr commented on frontend/src/components/ReadyMembersContainer/ReadyMembersContainer.tsx
>                  <span>{member.nickname}</span>
<img width="400" alt="image" src="https://github.com/user-attachments/assets/0f1fbe77-487b-4172-9184-a9ad65c8f7d2">

2024-10-16 02:25 UTC, rbgksqkr commented on frontend/src/pages/NicknamePage/NicknameInput/NicknameInput.tsx
> +        aria-label="닉네임 입력"
<img width="400" alt="image" src="https://github.com/user-attachments/assets/56847a98-fc75-41e0-a254-5de74a5ccbfe">

2024-10-16 08:04 UTC, useon approved these changes
폼에 ~~ 코멘투 달았어요!!! 쪼매만 다시 수정 부탁드립니다 팟팅 !!!!  ^ .^

2024-10-16 12:29 UTC, rbgksqkr approved these changes

2024-10-16 12:30 UTC, novice0840 commented on frontend/src/components/RoomSetting/RoomSetting.tsx
> +        onClick={isMaster ? handleClickCategory : () => {}}
![image](https://github.com/user-attachments/assets/25d9bd80-8905-41ef-886a-653d4608c446)

button에는 aria-hidden이 들어가면 안되는 것 같네요 ㅎㅎ... 넣으니까 에러가 떠버리네요

2024-10-16 12:40 UTC, merged