[REFACTOR] 라운드 결과 페이지 스크린 리더 개선
woowacourse-teams/2024-ddangkong pull request #328
Opened 2024-10-10 18:06 UTC by useon

## Issue Number
#325 

## As-Is

### 투표 통계 탭

- 개선 전

https://github.com/user-attachments/assets/0334c3e8-72e6-49d0-91d4-e9812f06b6f0

```
📢
2 배너 랜드미크 
슬래시
5
투표 결과 머리말 레벨 1 앤드 배너
투표 통계 버튼 앤드 탐색 랜드마크
투표 현황 버튼 앤드 탐색
지금 20억 한꺼번에 받기 vs 죽을 때까지 매달 1000만원 받기
지금 20억 한꺼번에 받기
죽을 때까지 매달 1000만원 받기
100
%
0
%
2
명
0
명
땅콩 땅콩 유저 중
100
%
는
죽을 때까지 매달 1000만원 받기
를 선택했어요!
방장이 진행해 주세요 흐리게 표시 됨 버튼
```
- 문제점
1. 헤더의 정보를 끊어서 읽는다. 
2. 투표 통계와 투표 현황을 버튼으로 읽기 때문에 탭임을 인지하지 못한다.
3. 투표 통계를 끊어서 읽는다. 
4. 전체 땅콩 유저 투표 통계 요약을 끊어서 읽는다.

### 투표 현황 탭

https://github.com/user-attachments/assets/b1093121-bfed-448d-9bc7-ad5cb768e8d6

```
📢
투표 현황 버튼 앤드 탐색
지금 20억 한꺼번에 받기 vs 죽을 때까지 매달 1000만원 받기
지금 20억 한꺼번에 받기 
콜론
2
사용자 이미지
엉뚱한 염소
사용자 이미지
웃긴 참새
죽을 때까지 매달 1000만원 받기
콜론
0
명
투표에 참여하지 않으셨어요
콜론
0
명
```
- 문제점
1. 선택지와 투표 인원 정보를 끊어서 읽고, 불필요한 텍스트까지 읽는다.

## To-Be

- [x] 투표 통계, 투표 현황 탭인지 인식할 수 있도록 role="tab"으로 수정
- [x] 투표 통계, 투표 현황에서 현재 어떤 탭에 위치하고 있는지 알 수 있도록 aria-current 적용
- [x] 라운드 결과 헤더에 현재 라운드 및 페이지 이름을 알려주기 위해 헤더 시각적 요소에 aria-hidden 처리 및 A11yOnly 컴포넌트를 활용하여 접근성 전용 텍스트 추가
- [x] 투표 통계 탭 내용에서 끊어 읽는 문제를 해결하기 위해서 시각적 요소에 aria-hidden 처리 및 A11yOnly 컴포넌트를 활용하여 접근성 전용 텍스트 추가
- [x] 전체 유저의 결과를 요약해서 보여주는 텍스트 수정
- [x] 투표 현황 탭 내용에서 끊어 읽고, 불 필요한 콜론을 읽는 문제를 해결하기 위해 옵션과 투표 수의 시각적 요소를 aria-hidden 처리를 하고 A11yOnly 컴포넌트를 활용하여 접근성 전용 텍스트 추가

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description
### 투표 통계 탭

- 개선 후

https://github.com/user-attachments/assets/b24a5108-2af6-49d6-973e-4fcced7a387a

### 투표 현황 탭

- 개선 후

https://github.com/user-attachments/assets/b3424263-e51c-42b6-a0cf-ce229da007c5

처음에는 aria-label과 role='text'와 A11yOnly 컴포넌트 이용 중 어떻게 적절하게 사용할지 고민이 되었습니다.

그 중에서 A11yOnly을 많이 활용하여 개선한 가장 큰 이유는 `기존의 시각적 요소 코드는 놔두고, 접근성을 위한 콘텐츠를 명시적으로 추가하여 코드를 관리하고 파악하기 용이`하다고 생각했기 때문입니다 🌞
또한 role="text"는 mdn의 aria 속성에서 찾을 수 없었고, 접근성 개선을 위해 role="text"를 사용하는 것에 대해 신중해야 한다는 아티클을 보아서 공유합니다 .. 🥹 !!

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles
https://www.boia.org/blog/should-your-site-use-the-text-role-for-accessibility

추가로 개선되어야 하거나 회의가 필요한 부분 얼마든지 환영합니다 파이탱탱탱 🌟👏

2024-10-12 08:01 UTC, rbgksqkr approved these changes
고생하셨습니다 썬썬썬!!!!! PR에도 자세히 작성해주고 접근성 고수(?)의 면모를 보여줘서 코멘트를 남길 게 많지 않았네용 스크린 리더로 읽었을 때 훨씬 깔끔해진 것 같아요! 몇가지 코멘트 남겼는데 큰 변경사항은 아니여서 일단 approve 드리겠습니다 🔥🔥🔥🔥🔥

2024-10-12 08:13 UTC, rbgksqkr commented
변경사항에 잡히지 않아서 까먹고 넘어갔는데 사용자 프로필 이미지를 스크린 리더로 읽도록 설정한 이유가 궁금합니다! 닉네임에 대한 정보만 궁금하지 않을까요??

2024-10-13 09:52 UTC, useon reviewed
마루 ~ ! ! 주신 코멘트에 대한 리뷰 반영을 완료했습니다 👏 커밋 단위로 나눠 놓았으니 읽어보셔요 !!!! 그리고 추가로 투표 현황에서 프로필 이미지 읽어주는 것에 대한 의견 달아주셔서 생각해 보았는데, 마루 말대로 투표 현황에서 프로필 이미지가 필요할까? 하는 생각이 들더라고요! 카카오톡 투표에서 확인해 보았는데 카카오톡도 마찬가지로 닉네임만 읽어주더라고요 !! 그래서 이미지 alt 값을 빈 값으로 처리해서 읽지 않도록 수정했습니다 👍

2024-10-13 09:52 UTC, useon commented on frontend/src/components/RoundVoteContainer/RoundVoteContainer.test.tsx
> +      expect(screen.getByText('안녕하세요안녕하세요안녕')).toBeInTheDocument();
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이번에도 테스트 깨져서 수정을 했더랍죠 .. 좋은 생각입니다.. 바꿔보았습니다 !!!!!! 👏👏

2024-10-14 12:08 UTC, novice0840 requested changes
우선, 한 번 훑어 보고 리뷰 남깁니다. 내일 회의 때 다시 한 번 얘기해봐요!

2024-10-16 07:26 UTC, novice0840 approved these changes

2024-10-16 08:56 UTC, useon reviewed
![image](https://github.com/user-attachments/assets/6ea76dad-d273-4da6-acd7-fd30b787a439)

1. RoundResultHeader 분리
2. IOS에서는 ','를 넣으면 끊어 읽지만 안드로이드에서는 끊어 읽지 않는 문제가 있어 ','를 '.'로 수정했습니다.

2024-10-16 10:51 UTC, merged