[REFACTOR] 게임 화면 웹 접근성 개선 & 모바일 애니메이션 버벅임 해결
woowacourse-teams/2024-ddangkong pull request #329
Opened 2024-10-10 18:15 UTC by rbgksqkr

## Issue Number
#321 

## As-Is

- 게임 화면을 스크린 리더로 플레이할 수 없음
- 모바일 크롬, 사파리에서 애니메이션 버벅임 문제 발생

## To-Be

- 게임에 필요한 정보들을 위주로 스크린 리더에서 접근 가능하도록 개선
  - 전체 라운드 중 현재 라운드, 질문, 옵션 선택지, 버튼 선택 여부 등을 알림
  - 불필요한 요소들을 aria-hidden 속성 부여 
  - 5초부터 타이머 알림
- 모바일 크롬, 사파리에서도 애니메이션 적용

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

### 게임 화면 접근성 개선

- 1초마다 타이머를 알려주면 너무 정신없길래 5초 남았을 때부터 알려주는 것으로 설정하였습니다.
- 확실히 스크린 리더로 게임하기엔 시간이 부족하다고 느껴집니다. 고민하는 시간이 없고, 읽기만 해도 30초가 지나가더라구요! 그렇다고 방설정에 1분 이상 주는 건 애매하긴 하네용

https://github.com/user-attachments/assets/80c1273f-3689-495a-a369-3a30fa0d07b6

**개선 후**
```
📢
5라운드 중 1라운드 밸런스 게임 페이지 배너 랜드마크
질문 : 둘 중 한 사람과 사귄다면? 1번. 나의 위로 15살 차이에 재산 30억. 2번. 나이 위아래로 2~3살 차이인데 빚 3억.
(현재 남은 시간)
나의 위로 15살 차이에 재산 30억
나이 위아래로 2~3살 차이인데 빚 3억
클릭 시(선택됨)
선택 버튼
```

## (Optional) Additional Description

### 모바일 환경에서 애니메이션 버벅임 해결

- 모바일 앱에서 애니메이션이 뚝뚝 끊기는 문제가 발생했습니다.
- 모바일 환경은 PC에 비해 성능도 느리고, 비율 계산이 정확하지 않아 발생한 것으로 추정됩니다. 
  - 기존에 scale값을 계산하기 위해 처리한 나누기 연산을 제거하고, timeLimit 만큼 애니메이션이 진행되도록 수정하였습니다.

#### ✅ 개선 전

**크롬 모바일**

https://github.com/user-attachments/assets/3040a2ad-4be1-4885-aab1-9de95cc548f2

**사파리**

https://github.com/user-attachments/assets/74b5a5f3-aa63-4a71-bb31-cd3b5a073ad0

#### ✅ 개선 후

**크롬 모바일**

https://github.com/user-attachments/assets/6ec699d0-ca19-4670-bfc6-dfc364098d10

**사파리**

https://github.com/user-attachments/assets/4ae42e99-7e86-4d5a-b0f1-d5db67e0b0ef

2024-10-11 16:28 UTC, useon requested changes
안녕하세요 마루 ~ ! 접근성 뿐만 아니라 몇 가지 에러 해결까지 함께 하셨군요 ..!!!! 문제를 해결하고 싶어서 괴로워하던 그의 모습 참 개발자 같았습니다 👍 PR에 자세히 적어 주셔서 확인하는데 편했어요 감사합니다 🌟 몇 가지 코멘트 달았는데 확인해 주시고 열심히 토론해 봅시다 ,, 접근성 관련해서 많은 토론을 했지만 또 토론을 .. 🥹 그래도 함께 고민할 수 있어서 힘이 납니다 파이팅 !!!!!!!! 🌞👏

2024-10-11 16:28 UTC, useon commented on frontend/src/components/SelectOption/SelectOption.tsx
> +      aria-pressed
# 🌸 칭찬 🌸
오오 마루 ~ 저는 pressed가 익숙하지 않아서 왜 selected를 사용하지 않았을까? 했는데 button에는 aria-selected를 지원하지 않는군요 .. 멋집니다 ^ .^ 다만 지금은 aria-pressed 가 true로 설정되어 있어도 누르지 않은 항목에도 "누름"이라고 말해서 혼란스러울 것 같은데 어떻게 생각하시나용 ?

2024-10-11 16:28 UTC, useon commented on frontend/src/components/TopicContainer/TopicContainer.tsx
> +      <A11yOnly>{isGamePage && screenReaderQuestion}</A11yOnly>
# 💭 질문 💭
오 ! 변수로 관리하는 방법 좋아 보이네요😊 하지만 한 파일에 접근성 변수가 많아질 경우에는 코드가 복잡해질까 우려도 되는데요! 이에 대해 마루는 어떻게 생각하시는지 궁금합니다 🌟

2024-10-11 16:28 UTC, useon commented on frontend/src/components/common/ErrorFallback/RootErrorFallback/RootErrorFallback.tsx
> +    window.location.href = '/';
# 💭 질문 💭
'이미 홈으로 리다이렉트된 경우 에러가 남아 있어 페이지가 리로드되지 않는 문제 해결'에 대한 과정이 궁금해요!  navigate를 사용하면 왜 리로드 되지 않고 해당 코드로 수정해야 됐나요 ? 🙌

2024-10-11 16:28 UTC, useon commented on frontend/src/components/common/SelectButton/SelectButton.tsx
> +        aria-pressed
# 🙏 제안 🙏
위와 마찬가지로 기본적으로 true로 설정되니 누름이라고 인식할 수 있을 것 같아요!

2024-10-12 07:43 UTC, rbgksqkr reviewed
썬데이 코멘트 반영했습니다! 질문 답변도 남겼는데 확인부탁드려요:)

2024-10-12 07:43 UTC, rbgksqkr commented on frontend/src/components/TopicContainer/TopicContainer.tsx
> +      <A11yOnly>{isGamePage && screenReaderQuestion}</A11yOnly>
그리고 코멘트와 별개로 해당 컴포넌트가 GamePage와 RoundResultPage에서 공통으로 사용되는데요!
현재 isGamePage로 분기처리가 되어 있는데, 2개가 되니까 헷갈리는 것 같아서 2가지 방안이 있을 것 같아요. 썬데이의 생각도 궁금합니다.

1. 컴포넌트를 분리해서 GamePage와 RoundResultPage 각각 사용하기
2. 분기문 자체를 페이지별로 나누기

```tsx
  const isGamePage = location.pathname === ROUTES.game(Number(roomId));

  if (isGamePage) {
    return (
      <section css={topicContainerLayout}>
        <A11yOnly>{getScreenReaderQuestion(balanceContent)}</A11yOnly>
        <span css={categoryText} aria-hidden>
          {balanceContent.category}
        </span>
        <span css={topicText} aria-hidden>
          {balanceContent.question}
        </span>
      </section>
    );
  }

  return (
    <section css={topicContainerLayout}>
      <span css={topicText} aria-hidden>
        {balanceContent.question}
      </span>
    </section>
  );
```

2024-10-12 07:43 UTC, rbgksqkr commented on frontend/src/components/common/ErrorFallback/RootErrorFallback/RootErrorFallback.tsx
> +    window.location.href = '/';
단순하게는 SPA 방식의 리액트는 페이지별로 HTML을 만들지 않고, url에 매칭된 컴포넌트를 렌더링합니다! 그래서 화면을 이동할 때 a 태그와 달리 깜박임이 발생하지 않는거구요

react-router는 window history API를 기반으로 만들어진 라이브러리라고 해요! history API는 url만 바꿔주고 서버 요청을 보내지 않는다고 합니다. 그래서 리액트에서 리로드 없이 부드러운 UX를 제공하는데, 저희 상황에서는 에러폴백에서 리로드가 필요한 상황이라 location.href으로 바꿔줬습니다!

https://reactrouter.com/en/main/hooks/use-navigate

2024-10-12 07:43 UTC, rbgksqkr commented on frontend/src/components/SelectOption/SelectOption.tsx
> +      aria-pressed
엇 다르게 읽히는군요!! 수정했습니다!

2024-10-12 07:43 UTC, rbgksqkr commented on frontend/src/components/common/SelectButton/SelectButton.tsx
> +        aria-pressed
수정했습니다!

2024-10-12 10:15 UTC, useon requested changes
마루 ~ ! 2차 리뷰 했습니다 ! 질문에 대해 상세히 설명해 주시고 바로 반영해 주셔서 감사해요 ! 의견 물어보신 부분 저의 의견 남겼으니 확인 부탁 드려요 !!! 개선 후 마루 branch로 게임해 보면서 추가로 타이머에 대한 개선 방안 떠올라 남겼습니다 🙌 읽어보시고 함께 고민해 봐요 ~~!!!! 👍👍👍

2024-10-12 10:15 UTC, useon commented on frontend/src/components/SelectContainer/Timer/Timer.tsx
> +        </A11yOnly>
# 🙏 제안 🙏
마루 branch 받아와서 게임 해보는데 막판에 5초 때부터 초를 계속 말해주고 그 타이밍에 선택을 누르면 "선택됨" 안내랑 겹치니까 너무 혼란스럽더라고요. (내가 선택을 한 것인지 하고 있는데 헉?? 그 와중에 계속 3초 ! 2초 ! 이러고 있으니) 그래서 고민을 해 보았는데 혹시 처음 타이머 시작했을 때, 30초 남았습니다. 절반이 지났을 때, 절반이 지났습니다. 또는 15초 남았습니다. 마지막으로 5초 남았을 때, 5초 남았습니다. 이런 식으로 안내를 주는 것에 대해 어떻게 생각하세요 ?? 혹시 또 생각나는 다른 방법이 있다면 !! 알려주세요 같이 고민해봐요 ~~ ! 😊🙌

2024-10-12 13:49 UTC, rbgksqkr reviewed
## 코멘트 반영사항
- 게임 화면 처음에 질문만 읽어주도록 변경
  - 중간에 타이머 읽어주도록 설정하니 옵션이 길어지면 타이머를 못읽어주는 경우 발생
- 절반 남았을 때와 5초 남았을 때만 타이머 안내 음성 제공

2024-10-13 07:08 UTC, useon commented on frontend/src/components/TopicContainer/TopicContainer.tsx
> +      <A11yOnly>{isGamePage && screenReaderQuestion}</A11yOnly>
> 제가 말한 유틸함수 방식은 재사용되지 않더라도 유의미하다고 생각해요! 컴포넌트 자체에 위치하지 않아도 되는 부분이 사라지기 때문인데요. 저희가 사용하는 컴포넌트명.utils.ts, 컴포넌트명.hooks.ts 방식도 재사용 목적이 아니라 컴포넌트단에 UI 로직만 남기기 위해서와 같은 맥락입니다!

아하! 이해했어요 마루 !! 👏👏👏
그치만 파일 분리까지 이루어질 정도인가 싶긴 해서 일단은 변수 선언 방식으로 가보시죠 ~~ 좋아요 ~!~!!! 🌟

2024-10-13 07:40 UTC, useon commented on frontend/src/components/SelectContainer/Timer/Timer.tsx
> +        </A11yOnly>
오호 ! 근데 어차피 라운드 결과 페이지로 화면이 넘어가면 제일 먼저 라운드 결과 페이지라고 알려줄테니 흠 .. 어떻게 하죠. 넘어갈 때 라운드가 종료되었습니다 음성을 출력할 수 있나요 ? ? ! 그렇다면 라운드 결과 페이지(제 담당)에서도 마찬가지로 다음 라운드로 넘어갑니다. 라는 멘트를 추가해야 할 것 같네요 !

2024-10-13 07:43 UTC, useon commented
안뇽하세요 마루 3차 리뷰 .. 완료 ..  ! 빠른 반영 감사드려요 👏👏👍👍 혹시 아직 헤더에는 타이머 안내 추가가 되지 않은 것인가욥 ?!!

2024-10-14 13:41 UTC, novice0840 requested changes
접근성 개선하느라 수고 많았습니다~~ 피드백 남깁니다. 
내일 회의 때 다시 얘기해봐요

2024-10-14 13:41 UTC, novice0840 commented on frontend/src/components/SelectContainer/Timer/Timer.tsx
> +        </A11yOnly>
# 💭 질문 💭
5초부터 타이머가 `polite`로 바뀌는 거면 30초부터 25초 동안은 리더기가 몇 초 남았는지는 모르는 건가요?

2024-10-14 13:41 UTC, novice0840 commented on frontend/src/components/SelectContainer/Timer/Timer.util.ts
>  };
# 💭 질문 💭
타이머가 `alert`로 바뀌는 조건이 2개인 이유가 있나요?

2024-10-14 13:41 UTC, novice0840 commented on frontend/src/components/SelectOption/SelectOption.tsx
> +      aria-pressed={selectedId === option.optionId}
# 🌸 칭찬 🌸
`toggle`을 나타낼 때 사용하는 `aria-pressed`라는 속성도 있군요!

2024-10-14 13:41 UTC, novice0840 commented on frontend/src/components/common/ErrorFallback/RootErrorFallback/RootErrorFallback.tsx
> +    window.location.href = '/';
# 🌸 칭찬 🌸
navigator 방식으로 해줘서 home 화면에서 에러가 발상하면 `홈으로 이동` 버튼을 누르는 게 의미가 없었는데 이제 고쳐졌네요 ㅎㅎ

2024-10-14 13:41 UTC, novice0840 commented on frontend/src/components/layout/Header/Header.tsx
>      </header>
# 🙏 제안 🙏
혹시 그냥 header에 `aria-label={screenReaderHeader}`를 넣는 건 어떻게 생각하시나요? 그럼 굳이 aria-hidden도 없어도 되고 `A11yOnly` 태그도 필요가 없을 것 같아서요

2024-10-16 03:01 UTC, rbgksqkr reviewed
회의 완료했습니다~! 주석 반영하겠습니다~! 고생하셨습니다:)

2024-10-16 03:01 UTC, rbgksqkr commented on frontend/src/components/TopicContainer/TopicContainer.tsx
> +      <A11yOnly>{isGamePage && screenReaderQuestion}</A11yOnly>
<img width="500" alt="image" src="https://github.com/user-attachments/assets/3579de75-8ad0-494f-8875-7d6917021cc1">

2024-10-16 03:01 UTC, rbgksqkr commented on frontend/src/components/layout/Header/Header.tsx
>      </header>
팀 컨벤션에 따라 작성했습니다~!

2024-10-16 07:15 UTC, rbgksqkr commented on frontend/src/components/SelectContainer/Timer/Timer.tsx
> +        </A11yOnly>
<img width="400" alt="image" src="https://github.com/user-attachments/assets/ab0beaa8-62f9-4279-b45b-e3756dfe3fa9">

2024-10-16 07:34 UTC, rbgksqkr commented
## 코멘트 반영사항
- 타이머가 읽히는 시점 판단하는 주석 추가 (isAlertTimer)
- 스크린 리더로 읽히는 부분 불필요한 분기문 제거 (TopicContainer)
- GameHeader 컴포넌트 분리

2024-10-16 07:40 UTC, useon approved these changes
확인했습니다 빠른 반영 감사드립니다 마루 !!!!!!!!!!! LGTM ~~~~~~ !!!

2024-10-16 08:04 UTC, novice0840 approved these changes

2024-10-16 12:29 UTC, merged