[FEAT] 방 게임 진행 시간 변경
woowacourse-teams/2024-ddangkong pull request #332
Opened 2024-10-14 11:23 UTC by leegwichan

## Issue Number
Closed #331 

## As-Is

- 프론트 행님들이 스크린 리더 개선하는데 15초는 플레이 타임이 짧음
- 30초 설정 추가 필요

## To-Be

- 방의 게임 시간 설정에 30초 추가
- RoomSetting 관련 테스트 일부 추가

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/f982bccb-4cbe-4077-942a-5cf33b4127f2)

## (Optional) Additional Description

2024-10-14 13:44 UTC, GIVEN53 approved these changes
gooooooooooooood boy

2024-10-15 01:06 UTC, PgmJun requested changes
직접 나서주셔서 감사합니다 커찬!
시간 부분만 수정 부탁드리겠습니다.!

2024-10-15 01:06 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/room/RoomSettingTest.java
> +    private static final List<Integer> ALLOWED_TIME_LIMIT = List.of(5_000, 10_000, 15_000, 30_000);
10 15 30 60 아닌가요~?!

2024-10-15 01:09 UTC, leegwichan commented on backend/src/test/java/ddangkong/domain/room/RoomSettingTest.java
> +    private static final List<Integer> ALLOWED_TIME_LIMIT = List.of(5_000, 10_000, 15_000, 30_000);
빠르게 반영하겠습니다

2024-10-16 12:18 UTC, jhon3242 approved these changes
커찬 수고했어요~ 커멘트 남겼는데 납득이 되시면 반응 부탁드릴게요! 사소한 의견밖에 없어서 Approve 드립니다~

2024-10-16 12:18 UTC, jhon3242 commented on backend/src/main/java/ddangkong/exception/ClientErrorCode.java
> +    INVALID_TIME_LIMIT("시간 제한은 %s 만 가능합니다. requested timeLimit: %d"),
질문) s로 변경한 이유가 궁금합니다!

2024-10-16 12:18 UTC, jhon3242 commented on backend/src/test/java/ddangkong/domain/room/RoomSettingTest.java
>          }
사소한 의견) 테스트 이름에 변경 가능성이 높은 비즈니스 정책이 있으면 정책 변경 시 테스트 이름도 변경해줘야하는 리소스가 있는 것 같아요. 그래서 개인적으로 "라운드 수가 범위를 벗어나는 경우 예외를 던진다"와 같이 비즈니스 정책이 변경되어도 대응이 가능한 메서드명을 사용하는것을 선호합니다! 납득이 되시면 변경해주세요!

2024-10-17 01:19 UTC, leegwichan commented on backend/src/main/java/ddangkong/exception/ClientErrorCode.java
> +    INVALID_TIME_LIMIT("시간 제한은 %s 만 가능합니다. requested timeLimit: %d"),
이거 매번 시간 제한 선택지가 늘어날 때마다 메시지가 바뀌는 게 마음에 안들었습니다.
그래서 List<Integer>를 toString으로 바꿔서 에러 메시지로 넣도록 했습니다~

2024-10-17 01:41 UTC, merged