[FEAT] 쿠키를 통한 유저 정보 조회
woowacourse-teams/2024-ddangkong pull request #334
Opened 2024-10-15 11:12 UTC by jhon3242

## Issue Number
close #264 

## As-Is

프론트엔드에서 전역으로 관리하던 유저 정보가 새로고침할 때마다 사라지는 문제가 발생했습니다. 유저들이 새로고침을 빈번히 사용하면서, 이로 인해 사용자 경험이 저하되는 큰 문제를 발견했고, 이를 해결하여 개선하고자 했습니다.

## To-Be

- 쿠키를 도입하여 방에 처음으로 참여시 쿠키를 저장
- 유저 정보 조회 API 생성
  - 프론트엔드에서 전역으로 관리하던 유저 정보가 사라지게 되면 유저 정보를 조회하는 API로 유저 정보를 요청한다. 이때 쿠키에 있는 값을 통해 유저 정보를 가져온다.

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/047acbc8-f907-4092-9dfb-058aa7424b93)

## (Optional) Additional Description

2024-10-16 06:44 UTC, leegwichan requested changes
코드 확인했습니다.
리뷰 반영 or 코멘트 추가 부탁드립니다.

2024-10-16 06:44 UTC, leegwichan commented on backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
> +
각 테스트를 위의 `class 방_생성`, `class 방_참가` 로 옮기는 게 어떨까요?

2024-10-16 06:44 UTC, leegwichan commented on backend/src/test/resources/application.yml
> +  algorithm: "AES"
해당 값을 application-dev.yml과 application-prod.yml에도 따로 추가하는 것이 좋지 않을까요?
특히 `encrypt.secret-key`와 `encrypt.algorithm`은 시크릿으로 관리해야 할 것 같아요.

2024-10-16 06:44 UTC, leegwichan commented on backend/src/main/resources/application-test.yml
??????????????? 왜 주석 처리 되어 있죠?

2024-10-16 06:44 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/room/RoomController.java
>      }
`HttpServletRequest`, `HttpServletResponse`를 받아서 쓰는 방법 외에 다른 방법 없나요?
Cookie 객체나, `@CookieValue`를 이용해서 쿠키를 받는 방법, ResponseEntity를 이용하여 쿠키를 넣는 방법도 있을 것 같아요!

2024-10-16 13:26 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/room/RoomController.java
>      }
`@CookieValue`를 활용하면 더 깔끔해지겠네요! 활용해볼게요! 

다만 ResponoseEntity를 사용하는 방식에 대해선 이전에 ResponoseEntity 대신 `@ResponseStatus` + `@ResponseBody` 를 사용하는 방식으로 컨벤션을 정했던 것 같아요! 그래서 적용하지 않았습니다!

2024-10-16 13:26 UTC, jhon3242 commented on backend/src/test/java/ddangkong/controller/room/RoomControllerTest.java
> +
이 부분에 대해서 저도 고민했었던 부분이였어요! 😁
하지만 적용하지 않은 이유는 테스트에서 보고자하는 관심이 다른 것이라고 생각했어요. 방 생성 및 참가에 대한 테스트는 무사히 방이 생성되고 참가가 되는지 확인하는 테스트라고 생각했어요. 그래서 쿠키 관련 테스트는 쿠키에서 공통적으로 보는게 더 맞다고 생각했습니다!

ps. 추가로 `의견`인지 `사소한 의견`인지 언급해주시면 더 좋을 것 같아요! 😊

2024-10-16 13:26 UTC, jhon3242 commented on backend/src/test/resources/application.yml
> +  algorithm: "AES"
네! 맞아요! 따로 시크릿으로 관리할 부분이에요! ㅎㅎ 그래서 테스트에서는 노출되어도 상관 없도록 일부러 테스트용으로 다른 값을 사용했습니다! ㅎㅎ

우선 리뷰를 받고 dev 랑 prod yml에도 적용하려고 합니다! 다들 이 방식이 괜찮으시면 반영해서 dev 랑 prod yml에도 적용해볼게요! 😊

2024-10-16 13:55 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/room/EncryptCookie.java
> +public class EncryptCookie {
그러네용.. 동사가 prefix에 있어서 어색한 것 같네요 변경해볼게요!

2024-10-16 13:55 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/room/EncryptCookie.java
> +    @Value("${cookie.key}")
final를 사용해보려다가 실패했는데 생성자에서 사용하면 되겠네요! 반영해볼게요!

2024-10-16 13:55 UTC, jhon3242 commented on backend/src/test/java/ddangkong/documentation/room/RoomDocumentationTest.java
> +                    .andDo(document("room/rejoin",
오홍 쿠키에 대한 스니펫이 따로 있었네요! 적용해볼게요!

2024-10-17 01:19 UTC, GIVEN53 approved these changes
반영 감사합니다 ( - - ) ( _ _ )

2024-10-17 01:26 UTC, PgmJun reviewed
타칸 고생해셨어요! 의견 남겨두었는데 확인 부탁드립니다:)

2024-10-17 01:26 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/room/RoomController.java
> +        response.addCookie(encodedCookie);
의견) Cookie를 설정하는 로직은 메서드 분리 가능할 듯 !

2024-10-17 01:26 UTC, PgmJun commented on backend/src/main/java/ddangkong/facade/room/RoomFacade.java
> +    public RoomJoinResponse rejoinRoom(String memberIdObject) {
의견) memberIdObject라는 네이밍이 조금 아쉬운 것 같아요 외부에서 Long으로 만들어서 전달하는게 낫지 않을까 싶어요

2024-10-17 07:02 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/room/RoomController.java
> +        response.addCookie(encodedCookie);
**쿠키를 받고 reponse 객체에 쿠키를 추가하는 로직만 따로 분리하면 좋을 것 같아요!**
로직을 분리하면서 추후 다른 로직에서도 사용하기 위해서 key. value를 받는 형식에 대해서도 고려해보았어요.

key. value를 받는 형식으로 리팩터링 하면 다음과 같을 것 같아요.
```java
@ResponseStatus(HttpStatus.CREATED)
@PostMapping("/balances/rooms")
public RoomJoinResponse createRoom(@Valid @RequestBody RoomJoinRequest request, HttpServletResponse response) {
    RoomJoinResponse roomJoinResponse = roomFacade.createRoom(request.nickname());
    setCookie(response, encryptKey, cookieEncryptor.getEncodedValue(roomJoinResponse.member().memberId()));
    return roomJoinResponse;
}

private void setCookie(HttpServletResponse response, String key, String value) {
    Cookie cookie = CookieUtils.getCookie(key, value);
    response.addCookie(cookie);
}
```
중복 코드는 줄어들 수 있을 것 같아요! 다만, 여기서 사용하는 쿠키의 경우 키 값을 외부에 노출시키지 않기 위해 시크릿키로 관리하고 있어요. 그래서 쿠키를 설정하는 로직을 따로 분리하여 key. value를 인자로 받는식으로 바꾸게 된다면 컨트롤러 내부에서 encryptKey를 받기 위해서 생성자를 추가해줘야할 것 같아요.
따라서 실제 코드는 아래와 같겠죠.
```java
@RestController
@RequestMapping("/api")
@Validated
public class RoomController {

    private final RoomFacade roomFacade;
    private final CookieEncryptor cookieEncryptor;
    private final String encryptKey; // 쿠키의 key 값

    public RoomController(RoomFacade roomFacade, CookieEncryptor cookieEncryptor, @Value("${cookie.key}") String encryptKey) {
        this.roomFacade = roomFacade;
        this.cookieEncryptor = cookieEncryptor;
        this.encryptKey = encryptKey;
    }

    @ResponseStatus(HttpStatus.CREATED)
    @PostMapping("/balances/rooms")
    public RoomJoinResponse createRoom(@Valid @RequestBody RoomJoinRequest request, HttpServletResponse response) {
        RoomJoinResponse roomJoinResponse = roomFacade.createRoom(request.nickname());
        setCookie(response, encryptKey, cookieEncryptor.getEncodedValue(roomJoinResponse.member().memberId()));
        return roomJoinResponse;
    }

    private void setCookie(HttpServletResponse response, String key, String value) {
        Cookie cookie = CookieUtils.getCookie(key, value);
        response.addCookie(cookie);
    }
    ...
}
```
이는 오히려 코드의 복잡성이 늘어날 것 같습니다!
따라서 결론적으로 처음에 말했던 방식대로 쿠키 생성 로직과 response 객체에 쿠키를 추가하는 로직만 분리할게요!

2024-10-17 08:43 UTC, leegwichan approved these changes
천재 만재 타칸 
He is Legend 석유 부자

2024-10-17 08:46 UTC, merged