[FEAT] CD(Continuos Delievery & Deploy) 파이프라인에 Docker 사용
woowacourse-teams/2024-ddangkong pull request #35
Opened 2024-07-19 00:52 UTC by PgmJun

## Issue Number
#33 

## As-Is

## To-Be

## Check List
- [ ] 테스트가 전부 통과되었나요?
- [ ] 모든 commit이 push 되었나요?
- [ ] merge할 branch를 확인했나요?
- [ ] Assignee를 지정했나요?
- [ ] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description

2024-07-19 04:01 UTC, GIVEN53 requested changes
고생했어요 이든! 질문 몇 개 남겨놨는데 확인 부탁드려요

2024-07-19 04:01 UTC, GIVEN53 commented on .github/workflows/be-cd-dev.yml
> +          ddangkong/ddangkong-api-dev:latest
의견) EOF 확인 부탁드립니당

2024-07-19 04:01 UTC, GIVEN53 commented on backend/Dockerfile
> +EXPOSE 8080
질문) 8080 노출을 명시하는 이유가 있나요??

2024-07-19 04:31 UTC, PgmJun commented on .github/workflows/be-cd-dev.yml
> +        run: docker build --platform linux/arm64/v8 -t ${{ secrets.DOCKER_REPOSITORY_NAME }}/ddangkong-api-dev:latest .
platform 설정 없이 Git Actions에서 빌드하게되면
EC2와 빌드 플랫폼이 달라서그런지 EC2에서 플랫폼 문제로 인해 작동하지 않더라구요

2024-07-19 04:31 UTC, PgmJun commented on .github/workflows/be-cd-dev.yml
> +          ddangkong/ddangkong-api-dev:latest
확인 감사합니당!

2024-07-19 11:00 UTC, PgmJun commented on backend/Dockerfile
> +EXPOSE 8080
제가 EXPOSE를 잘못 이해하고 있었습니다 ㅎㅎ..
그리고 -p 8080:8080 으로 처리하고있어서 필요 없을 듯하네요
제거하겠습니다!

2024-07-19 14:03 UTC, PgmJun commented on .github/workflows/be-cd-dev.yml
> +        run: ./gradlew clean bootJar
clean은 빼야지 했다가 빼지 못한 부분인 것 같습니다.
꼼꼼한 체크 감사합니다~!

추가 질문으로 주신 task부분도 답변드리자면
CI에서 Test를 포함한 build Task를 수행합니다.
build Task는 모든 테스트 실행, 프로덕션 artifact 생성을 포함하여 모든 것을 빌드한다고 공식문서에 작성되어 있는데요.
이를 통해서 정상적으로 프로덕트가 정상 작동 가능한 지 검증합니다.

그리고 이 과정을 CI에서 이미 거치기 때문에 성능적인 측면을 고려하여,
CD에서는 bootJar task만 동작시켜 실행가능한 artifact 생성만 수행하도록 하였습니다.

2024-07-19 14:09 UTC, leegwichan submitted a review, later dismissed

2024-07-19 15:06 UTC, jhon3242 commented on .github/workflows/be-ci-dev.yml
> +        run: ./gradlew build
질문) clean 은 왜 빠진거죠?? 특별한 이유가 있는지 궁금합니다!

2024-07-19 15:07 UTC, jhon3242 submitted a review, later dismissed

2024-07-19 15:11 UTC, PgmJun commented on .github/workflows/be-ci-dev.yml
> +        run: ./gradlew build
clean Task는 기존 프로젝트 build 과정에서 생성된 build 디렉토리를 삭제하기 위해 존재하는데요~
스크립트 내에서 build를 단 한 번만 수행하기 때문에 clean Task가 하는 일이 사실상 없습니다!

2024-07-20 07:32 UTC, GIVEN53 commented on .github/workflows/be-cd-dev.yml
> +        run: docker build --platform linux/arm64/v8 -t ${{ secrets.DOCKER_REPOSITORY_NAME }}/ddangkong-api-dev:latest .
이미지가 arm64가 아니라서 추가되었군요 답변 감사합니다 👍🏼

2024-07-20 07:47 UTC, GIVEN53 commented on .github/workflows/be-cd-dev.yml
> +        run: ./gradlew clean bootJar
build task에는 이든이 말씀해주신 것 처럼 테스트를 실행하는 test task, 실행 가능한 jar 파일을 생성하는 bootJar task를 포함합니다그리고 github actions 트리거를 봤을 때 ci는 PR이 생성되었을 때, cd는 PR이 머지되었을 때 동작하는 것으로 이해했어요
제 코멘트는 ci에서 bootJar를 포함한 build task 실행이 필요할까에 대한 고민으로 달게 됐어요 ci에서 jar 파일은 필요없으니 test만 돌아도 되지 않을까?하는 생각이었어요
하지만 cd에 필요한 산출물 생성도 정상 동작되는지 검증하는 절차도 포함한다면 충분히 이해가 됩니다! ci와 cd의 트리거 시점이 다르기도 하구요

> 그리고 이 과정을 CI에서 이미 거치기 때문에 성능적인 측면을 고려하여,
CD에서는 bootJar task만 동작시켜 실행가능한 artifact 생성만 수행하도록 하였습니다.

test를 제외하고 필요한 task만 실행해주신 점 👍🏼👍🏼

2024-07-20 07:54 UTC, GIVEN53 approved these changes
한 가지 코멘트만 확인해주세요!
먼저 approve하겠습니당

2024-07-20 07:54 UTC, GIVEN53 commented on backend/deploy/docker-compose-dev.yml
> +    entrypoint: [ java, -jar, -Dspring.profiles.active=dev, -Duser.timezone=Asia/Seoul, app.jar ]
의견) `-Duser.timezone=Asia/Seoul`이 Dockerfile과 중복됩니다

2024-07-20 09:30 UTC, jhon3242 reviewed
든든 칭찬해~

2024-07-22 08:41 UTC, PgmJun commented on .github/workflows/be-cd-dev.yml
> +        shell: bash
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults

2024-07-23 00:54 UTC, PgmJun commented on backend/deploy/docker-compose-dev.yml
> +    entrypoint: [ java, -jar, -Dspring.profiles.active=dev, -Duser.timezone=Asia/Seoul, app.jar ]
ARG, ENV 활용하여 다른 중복 EntryPoint도 처리하였습니다 :)

2024-07-23 00:56 UTC, leegwichan approved these changes
이든 고생했어~

2024-07-23 01:06 UTC, GIVEN53 approved these changes
LGTM 🥰

2024-07-23 01:07 UTC, merged