Refactor/#405
woowacourse-teams/2024-ddangkong pull request #420
Opened 2024-12-03 01:59 UTC by novice0840

## Issue Number

#405 

## As-Is
기존에 트랜스파일러로 babel을 사용하고 있었음

## To-Be
SWC로 변경해 트랜스파일 시간을 단축시킴

## Before
Webpack Production Build
![before](https://github.com/user-attachments/assets/fe2e3ec1-766f-462b-8df5-c38d36339ccb)
Storybook Build
![storybook-before](https://github.com/user-attachments/assets/9f05e762-c953-45b4-8f74-bc78220e8939)

## After
Webpack Production Build
![after](https://github.com/user-attachments/assets/b0ca17f1-bd48-4e39-90e5-23ac9a264fe1)
Storybook Build
![storybook-after](https://github.com/user-attachments/assets/fcc95ecf-b416-4d71-a1c9-a4b8189746a9)

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description

2024-12-03 03:42 UTC, rbgksqkr requested changes
안녕하세요 포메~! 트랜스파일러를 swc로 변경하셨군요!
속도가 빨라진 것은 좋지만 어떤 도구를 변경하는 거라면 트레이드오프가 있을 거라고 생각해요! PR에 babel과 비교해서 어떤 점이 좋아 swc로 변경하게 되었는지 알려주시면 감사하겠습니다:)
babel에서 설정한 polyfill과 브라우저 호환성이 swc에서도 동일하게 적용되는건지도 궁금해요. 만약 장점이 속도에만 있다면 다음 부분이 우려가 됩니다. 사실 13초에서 11초가 된게 퍼센트로 보면 유의미하지만, 13초의 빌드속도가 도구를 변경할만한 시점인가가 우려가 되어 질문드립니다!!

2024-12-03 03:42 UTC, rbgksqkr commented on frontend/package.json
> +    "@tanstack/react-query-devtools": "^5.62.1",
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
dev dependency로 옮긴 이유가 있나요?? tanstack-query 공식문서에서 dependency로 설치하기도 하고, production 빌드에서 제외된다는 내용이 있어서요! 따로 조사해본 내용이 있는지 궁금합니다.

https://tanstack.com/query/latest/docs/framework/react/devtools

2024-12-03 03:42 UTC, rbgksqkr commented on frontend/package.json
> +  "packageManager": "yarn@4.1.0+sha512.5b7bc055cad63273dda27df1570a5d2eb4a9f03b35b394d3d55393c2a5560a17f5cef30944b11d6a48bcbcfc1c3a26d618aae77044774c529ba36cb771ad5b0f"
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
이건 어떤 내용인가요?? swc를 설정하기 위해 필요한 것인가요?

2024-12-03 03:42 UTC, rbgksqkr commented on frontend/webpack.config.prod.js
> +        use: ['swc-loader'],
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
swc로 빌드하면 기존의 polyfill 적용이 다 되나요??

2024-12-03 21:59 UTC, novice0840 commented on frontend/package.json
> +  "packageManager": "yarn@4.1.0+sha512.5b7bc055cad63273dda27df1570a5d2eb4a9f03b35b394d3d55393c2a5560a17f5cef30944b11d6a48bcbcfc1c3a26d618aae77044774c529ba36cb771ad5b0f"
속도 확인해 보고 싶어서 테스트 한거였는데 
`npm run build:storybook` 명령어를 치면 해당 코드가 자동으로 들어가는 것 같네요;;... 

불필요한 코드 제거하였습니다!

2024-12-03 22:20 UTC, novice0840 commented on frontend/package.json
> +    "@tanstack/react-query-devtools": "^5.62.1",
아 이 내용은 못봤네요!  devtools는 당연히 devDependencies 에 들어가야한다고 생각했습니다. 
이러면 어느쪽에 들어가도 빌드용량에는 차이가 없겠군요. 어느 쪽이던 차이가 없다면 `공식 문서` 기준을 따르는 것이 좋을 것 같네요.

2024-12-03 22:41 UTC, novice0840 commented
피드백 확인했고 답글 남겼습니다. 기존에 `babel` 설정 파일에 있던 타겟 브라우저 목록과 폴리필 설정을 `SWC` 설정에서 똑같이 추가하였습니다. 

SWC 의 단점으로 가장 언급되는 것이 Babel이 비해 안정성이 떨어진다는 부분인데 이미 `Next.js`에서는 내부적으로 `SWC`를 사용하고 있는 것으로 보아 안정성 문제는 걱정할 정도는 아니라고 생각합니다. 
https://nextjs.org/docs/architecture/nextjs-compiler

2024-12-04 16:23 UTC, rbgksqkr commented on frontend/webpack.config.prod.js
> +        use: ['swc-loader'],
앗 제가 말한건 저희가 처음에 설정한 babelrc 에 설정된 폴리필 설정 말한거였어요! 한국에서 1% 이상 점유하는 브라우저에 대해 폴리필을 제공하고 있었는데, swcrc에는 보이지 않아서 여쭤봤습니다. 기존에 빌드한 결과물과 일치하는지 (코드 줄수)를 확인하면 될 것 같습니당

참고로 jest.polyfill.js 는 최신 버전의 jest와 msw가 연동되지 않아 필요한 파일이였습니다!!

2024-12-04 16:25 UTC, rbgksqkr commented on frontend/webpack.config.prod.js
> +        use: ['swc-loader'],
앗 코멘트에 남겨주셨군요 확인했습니다!

2024-12-04 16:27 UTC, rbgksqkr approved these changes
반영 확인했습니다! 폴리필 설정과 swc-loader, 그리고 next 내부에서 swc를 사용하고 있다는 점에서 저희 서비스에 도입해도 좋겠네용 고생하셨습니다:)

2024-12-06 16:14 UTC, useon approved these changes
항상 효율을 고민해 주는 포메 감사합니다 👍 마루와 주고 받은 코멘트를 통해 도입 이유를 더 이해할 수 있었습니다 ! 🍀

2024-12-12 04:36 UTC, novice0840 commented on frontend/.storybook/main.ts
> +          loader: require.resolve('swc-loader'),
네! 문제 없이 빌드가 되는 것으로 보아 괜찮을 거라 생각합니다

2024-12-12 04:37 UTC, merged