[FEAT] eslint을 커스텀해서 팀 코드 컨벤션 적용
woowacourse-teams/2024-ddangkong pull request #441
Opened 2024-12-20 11:30 UTC by novice0840

## Issue Number

#429 

## As-Is

팀 컨벤션으로 지켜왔던 코드 규칙들 중 eslint로는 검사가 되지 않는 부분들이 존재

## To-Be
### 추가된 eslint 커스텀 규칙
- [x] `is` keyword로 시작하는 경우에는 타입이 `boolean` 이여야 한다. 함수의 경우는 `boolean`을 반환
- [x] 변수명 규칙
1. 변수에 언더바(_)를 사용하는 경우 "대문자 + 언더바(_)"로 작성해야 합니다
2. 변수명이 소문자로 시작하는 경우 특수문자를 사용하지 않고 camelCase를 사용해야 합니다
- [x] `pages` 폴더 안에는 `Page`로 끝나는 폴더와 해당 폴더명과 일치하는 `tsx` 파일이 있어야 한다. 
- [x] `components` 폴더 안에는 컴포넌트 폴더와 해당 폴더명과 일치하는 `tsx` 파일이 있어야 한다. 
- [x] 컴포넌트의 props 타입은 `interface`로 나타내며 이름은 `컴포넌트 명 + props`이다. 
- [x] 함수를 선언할 때는 `화살표 함수`을 "권장"한다. `화살표 함수`는 `선언형 함수`와 기능이 다소 다르게 동작하기 때문에 `선언형 함수`를 사용하는 경우도 생길 수 있다고 판단하여 `에러`가 아닌 `권장`으로 설정하였다. 

### 추가된 내용
- process를 TS에서 인지하지 못해 @types/node 패키지 추가

### Provider 파일 Context와 Component 분리 
한 파일에서 Context와 Component를 동시에 내보내면 `fast refresh`가 동작하지 않아 
eslint 규칙에서 `react-refresh/only-export-components` 에러가 발생한다. 
![image](https://github.com/user-attachments/assets/e6a7934b-b4f4-4e5d-b0b7-44e8c85085a3)

그래서 둘을 각각의 파일로 분리하였음

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description

### Reference 🔎
공식문서에 있는 eslint 커스텀 설정 예제가 `flat configuation` 를 기준으로 되어 있어 이에 맞게 설정을 변경
eslint 8.21부터는 `flat configuation`이라는 방식이 도입되었고 eslint 9부터는 설정 파일의 이름은 기본적으로 `eslint.config.js`를 사용한다. 

eslint-react-hook rule 넣는 방법
https://github.com/facebook/react/issues/28313

https://typescript-eslint.io/packages/typescript-eslint#config
https://eslint.org/docs/latest/use/migrate-to-9.0.0

### 추가로 현재 우리가 사용중인 버전은 더이상 지원되지 않는 버전임 
![image](https://github.com/user-attachments/assets/64617ee3-3103-4cb3-8743-61d18a0b77ab)

### eslint-config-prettier
eslint-plugin-prettier만으로도 설정이 가능하다. `eslint-config-prettier`가 없어도 됨
![image](https://github.com/user-attachments/assets/795336c3-208c-47af-82fe-3a021529471d)
https://github.com/prettier/eslint-plugin-prettier

### AST란 무엇일까?
https://gyujincho.github.io/2018-06-19/AST-for-JS-devlopers

### typescript-eslint에서 rule을 custom하는 방법
https://medium.com/@uriser/how-to-write-a-custom-typescript-eslint-rule-4cc3489f9815

2024-12-20 18:42 UTC, rbgksqkr requested changes
와우,,,,꼼꼼한 커스텀 lint rule 설정 덕분에, 저희가 직접 정한 컨벤션을 놓치지 않고 반영할 수 있겠는데요??? 감사합니다 ㅎㅎㅎ 엄청 고생했어요 포메!!!!! 코드 리뷰할 때도 불필요한 리뷰가 많이 줄어들 것 같아서 좋네요~!
커스텀 린트룰은 이론적으로만 보고 실제 도입해보지 못했던 부분인데, 저희가 정한 팀 컨벤션 기반으로 코드를 보니 좀더 이해가 잘 되는 것 같아용
약간 생소한 부분이고, 패키지 수정이 많아서 질문을 좀 남겼는데 확인 부탁드려용

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/tsconfig.json
> +    "types": ["jest", "@emotion/react/types/css-prop", "node"],
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
node를 추가하면 어떤 다른 기능을 하나요??

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/eslint.config.mjs
> +        ...globals.browser,
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
globals가 여기서만 사용되는데, 이걸 추가하지 않으면 어떻게 동작하나요?? 라이브러리가 추가돼서 궁금했습니다!

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/jest.polyfills.js
> +if (!globalThis.TextDecoder) {
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
오호 이렇게 분기처리를 안하면 어떤 문제가 생기나요?? 어떤 점이 다른걸까요?

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/package.json
> +    "eslint-plugin-prettier": "^5.2.1",
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
eslint-config-prettier 대신 eslint-plugin-prettier로 바꾼 이유가 있나요??
제가 예전에 eslint 설정으로 애를 좀 먹어서 블로그를 썼었는데, 해당 eslint가 동작하려면 vscode 포맷팅 설정을 eslint로 수정해야 하는건가요?

<img width="500" src="https://github.com/user-attachments/assets/ba4146ab-128e-4027-8d26-c1c2ce8f2e22" />

https://velog.io/@ghenmaru/react-typescript-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-eslint-prettier-%EC%84%A4%EC%A0%95

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/src/providers/ModalProvider/ModalContext.ts
> +import { createContext, RefObject } from 'react';
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
오호 같이 두면 fast refresh 경고가 뜨는군요! ModalContext랑 ToastContext는 providers와 형제 폴더로 contexts 폴더에 분리하는 건 어떤가요?

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/src/components/common/Modal/Modal.tsx
> -  extends React.PropsWithChildren<{
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
해당 타입을 제거한 이유가 궁금합니다! 저는 Props에 children이 포함되어있는 걸 명시적으로 나타내는 게 좋아서 자주 사용하는데, 제거한 이유도 궁금합니다~!

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/public/mockServiceWorker.js
> +    }
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
이 코드는 어떤 역할인가요?? 기존 코드를 제거한 이유도 궁금합니다.

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/public/mockServiceWorker.js
> +    }
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
아 뭔가 전체적으로 mockServiceWorker가 변경된 것 같은데 직접 변경한 게 아니라 버전을 올리면서 변경된 코드 같아요!
근데 package.json은 그대로인걸 보니 올렸다가 다시 내리는 과정에서 이 코드만 변경된 것 같아요!!!
맞다면 해당 파일 변경점을 제거해주시고, 그게 아니라 의도적인 변경이라면 전체적인 설명 부탁드립니다!

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/package.json
> +    "@eslint/eslintrc": "^3.2.0",
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
compat과 eslintrc는 import되서 사용되고 있지는 않은데, 내부 동작에 필요한 라이브러리 인건가요??

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/eslint.config.mjs
> +      ...pluginQuery.configs['flat/recommended'],
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
기존의 `@typescript-eslint` 설정은 없어졌는데 typescript-eslint 내부적으로 동작하는 건가요??

<img width="400" alt="image" src="https://github.com/user-attachments/assets/5f6d7a60-08e9-4f4d-b54f-4cc0843bccbc" />

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/eslint-ddangkong/eslint-plugin-ddangkong.js
> +const enforceIsBoolean = require('./enforce-is-boolean');
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
와우 이렇게 디테일하게 eslint rule을 지정할 수 있군요 대박,,,,너무 좋네요,,,,,

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/eslint-ddangkong/eslint-plugin-ddangkong.js
> +const enforceIsBoolean = require('./enforce-is-boolean');
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
이건 간단한 제안인데 해당 파일이 대표 파일 느낌인 것 같아서 파일명을 index.js 로 설정해도 괜찮을 것 같네용

2024-12-20 18:42 UTC, rbgksqkr commented on frontend/eslint-ddangkong/component-folder-match.js
> +const path = require('path');
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
오옹 이런 방식으로 eslint rule 들이 만들어지는군요,,,한번 공부해봐야겠네용
머지되면 콘솔 찍어보면서 입력으로 들어오는 값들을 이해해보겠숨돠

2024-12-23 15:17 UTC, novice0840 commented on frontend/tsconfig.json
> +    "types": ["jest", "@emotion/react/types/css-prop", "node"],
process와 같은 전역객체를 인식하기 위해 @types/node를 추가했고 이걸 ts에 적용하려면 node를 ts 설정 파일에 추가해줘야하더라고요!

2024-12-23 15:32 UTC, novice0840 commented on frontend/eslint.config.mjs
> +        ...globals.browser,
전역 객체를 정의할 때 사용되는 라이브러리입니다! 위 설정을 브라우저에서 사용되는 전역 객체들이 추가되어 eslint에서 인식 시켜줍니다

2024-12-23 15:33 UTC, novice0840 commented on frontend/jest.polyfills.js
> +if (!globalThis.TextDecoder) {
저게 없으면 테스트 코드에서 에러가 발생하더라고요!

2024-12-23 15:54 UTC, novice0840 commented on frontend/package.json
> +    "eslint-plugin-prettier": "^5.2.1",
![image](https://github.com/user-attachments/assets/be9ef94d-4746-40dd-9465-d53dfae4ebd2)

eslint-plugin-prettier/recommend를 사용하면 eslint-plugin-prettier와 eslint-config-prettier를 둘 다 설정해준다고 합니다. 다만 패키지 설치는 필요한 것 같네요!

2024-12-23 16:07 UTC, novice0840 commented on frontend/src/providers/ModalProvider/ModalContext.ts
> +import { createContext, RefObject } from 'react';
분리했습니다!

2024-12-23 16:13 UTC, novice0840 commented on frontend/src/components/common/Modal/Modal.tsx
> -  extends React.PropsWithChildren<{
![image](https://github.com/user-attachments/assets/d7766a6b-5e74-439b-abd1-fa98f318f82b)

이게 기존에 있었던 타입인데 저희 사용중인 규칙에서 extends를 하고 {} 이런 식으로 타입이 추가되지 않은 경우에는 에러가 발생하더라고요. 그래서 `PropsWithChildren`에서 직접 children 타입을 넣는 방식으로 바꾸었습니다.

2024-12-23 16:19 UTC, novice0840 commented on frontend/public/mockServiceWorker.js
> +    }
어 MSW 설정을 딱히 건든적이 없는데 바뀌었네요. 의도한 변경이 아니라서 다시 원래의 파일로 되돌리겠습니다!

2024-12-23 16:40 UTC, novice0840 commented on frontend/package.json
> +    "@eslint/eslintrc": "^3.2.0",
레거시 설정 파일과의 호환을 위해 필요한 패키지들인 것 같은데 저희 프로젝트 설정에는 필요 없는 것들이네요. 

불필요한 패키지들 제거하였습니다!

2024-12-23 16:41 UTC, novice0840 commented on frontend/eslint.config.mjs
> +      ...pluginQuery.configs['flat/recommended'],
tseslint.config 함수를 통해 동작합니다! 

typescript-eslint 패키지가 기본적으로 위 방식을 권장하더라고요

2024-12-23 16:49 UTC, novice0840 commented on frontend/eslint-ddangkong/eslint-plugin-ddangkong.js
> +const enforceIsBoolean = require('./enforce-is-boolean');
폴더명과 파일명이 일치하니까 그게 좋을 것 같네요 수정했습니다!

2024-12-24 08:57 UTC, rbgksqkr commented on frontend/package.json
> +    "eslint-plugin-prettier": "^5.2.1",
둘 다 설정해준다는 게 혹시 어떤 의미일까요???

질문은 기존에 eslint-config-prettier 만으로 lint가 잘 동작한다고 생각했는데, 수정한 이유가 궁금했습니다!!

2024-12-24 08:58 UTC, rbgksqkr commented on frontend/package.json
> +    "eslint-plugin-prettier": "^5.2.1",
추가로 컨트롤 + s 로 저장했을 때 자동으로 포맷팅되는지 궁금하고, 그때의 vscode default formatter 설정이 궁금합니다!

2024-12-24 09:06 UTC, rbgksqkr approved these changes
코멘트 반영 감사합니다 포메~! PropsWithChildren 관련해서만 코멘트 하나 남겼는데 확인해주시면 좋을 것 같고, approve 할게용

2024-12-26 08:55 UTC, novice0840 commented on frontend/src/components/common/Modal/Modal.tsx
> -  extends React.PropsWithChildren<{
오 그럼 extends을 하지 않아도 되겠군요. 수정했습니다!

2024-12-26 09:01 UTC, merged