[FEAT] google analytics 고도화하여 "땅콩" 서비스에 필요한 데이터 수집
woowacourse-teams/2024-ddangkong pull request #449
Opened 2024-12-27 13:58 UTC by novice0840

## Issue Number

#430 

## As-Is
기존에는 google analytics가 기본 설정만 되어 있어 구체적인 사용자 데이터를 얻기 어려웠다

## To-Be
 google analytics를 고도화하여 우리 서비스에 필요한 구체적인 데이터를 수집하도록 변경

### 추가로 수집된 데이터
- [x] 페이지 별 체류시간 - GA에서 페이지 별 체류시간을 기본적으로 수집하고 있지만 방 번호에 따라 각각 수집되기 때문에 한 번에 보기가 어려운 상황 
- [x] 투표 옵션 왼쪽 vs 오른쪽 뭐가 더 많이 눌리는지
- [x] 투표 시 확인 버튼 누르는 비율
![image](https://github.com/user-attachments/assets/ff504e0b-24aa-49e3-8e1b-6524b1bc1b07)
- [x] 게임 당 평균 참여 인원 수 
왼쪽: 게임 참여 인원 수
오른쪽: 게임 시작 횟수 
![image](https://github.com/user-attachments/assets/268d4942-3ead-4d3b-9b23-04a9e2cf89a7)

### 그 외
- [x] development 모드에서는 GA 비활성화 
- [x] 비즈니스 로직과 google analytics 로직을 쉽게 구분하기 위해 함수의 끝에 `GA` 표시를 추가하였음

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description

### 폴더 분리

google Analytics는 기능을 구현하는 코드가 아니기 때문에 별도의 폴더에 파일들을 모으는 것이 좋다고 판단하여
`src/lib/googleAnalytics` 폴더에 관련 코드들을 모아둠

2024-12-30 06:24 UTC, rbgksqkr approved these changes
고생하셨습니다 포메~! 체류시간이랑 버튼 클릭 여부를 GA로 추적하면 유용한 지표가 될 것 같네용
특히 게임할 때 "선택" 버튼을 누르는 횟수는 중요한 지표가 될 것 같고, 아래처럼 계산이 된다면 더 유의미한 지표가 될 것 같아요!

- 해당 라운드에서 선택 버튼을 누르는 비율
- 메인 페이지에 들어온 사람 중 방을 만드는 비율
- 게임을 하는 사람 중 최종 결과까지 보는 비율

2024-12-30 06:24 UTC, rbgksqkr commented on frontend/public/index.html
> +    if (process.env.NODE_ENV == 'production') {
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
오호 개발도메인에선 안잡히는줄 알았는데 잡히는군요 prod 빌드해서 그런가?? prod 환경만 찍히는걸 위한 코드라면 fe-cd-dev 스크립트에서 dev로 빌드해야될 것 같아요!

index.html에서 process.env.NODE_ENV가 잘 찍히나요?? dev빌드해서 콘솔로 확인해보면 좋을 것 같아요!

2024-12-30 06:24 UTC, rbgksqkr commented on frontend/src/hooks/useGetUserInfo.ts
> +  }, []);
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
useGetUserInfo가 여러번 호출되면 useEffect도 여러번 실행될 것 같은데 어떻게 생각하시나요??
처음 접속했을 때 확인하는 거라면 페이지 당 한번만 실행되어야 할 것 같아요!

2024-12-30 06:24 UTC, rbgksqkr commented on frontend/src/lib/googleAnalytics/hooks/usePageTimeSpentGA.ts
> +            value: timeSpent / 1000,
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
오호 이렇게 value를 넣으면 값이 누적되는 건가요?? 해당 이벤트는 이 value를 가져서 보내면 GA에서 이벤트값을 누적해주는 방식인가요?

2024-12-30 06:24 UTC, rbgksqkr commented on frontend/src/pages/GameResultPage/GameResultPage.tsx
> +  useGAPageTimeSpentGA('게임 결과 페이지');
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
매칭 결과 페이지가 좋을 것 같아요!

2024-12-30 08:30 UTC, novice0840 commented on frontend/public/index.html
> +    if (process.env.NODE_ENV == 'production') {
public 폴더에서는 환경 변수가 인식되지 않더라고요.... 그래서 분기를 어떻게 처리할까 고민하다가 
리액트에서 GA 초기화하는 hook을 추가로 넣어주었습니다. 

만약 대면 프로젝트였다면 구글 애널리틱스 설정에서 캠퍼스 IP는 데이터 수집을 되지 않도록 만드는 게 가장 좋은 방법이라 생각해요. 다만 지금은 비대면으로 진행되고 작업 장소도 제각각이니  위 방법을 사용하였습니다.

2024-12-30 09:11 UTC, novice0840 commented on frontend/src/pages/GameResultPage/GameResultPage.tsx
> +  useGAPageTimeSpentGA('게임 결과 페이지');
수정했습니다!

2024-12-30 09:16 UTC, novice0840 commented on frontend/src/lib/googleAnalytics/hooks/usePageTimeSpentGA.ts
> +            value: timeSpent / 1000,
네, 위처럼 action을 만들고 Google Analytics에서 action 이름에 맞게 커스텀 데이터를 추가해주면 데이터가 수집이 되더라고요

2024-12-30 09:31 UTC, novice0840 commented on frontend/src/hooks/useGetUserInfo.ts
> +  }, []);
음, 그렇겠군요. 그리고 지금 생각해보니 함수의 "단일 책임 원칙"에도 맞지 않는 것 같네요. 
URL과 유저 정보를 비교하는 부분을 별도의 함수로 분리하였습니다!

2025-01-02 10:51 UTC, useon requested changes
포메 덕분에 더 유용하게 사용자 데이터를 수집할 수 있겠네요 초기 설정이랑 중요 데이터들을 선정해 주었네요 감사합니다 ! 몇 가지 코멘트 남겼습니다 ~ ! 수고 많으셨어요 🍀

2025-01-02 10:51 UTC, useon commented on frontend/src/hooks/useGetUserInfo.ts
> -  }
# 💭 질문 💭
이제 이 코드가 삭제되어도 괜찮은건가요 ?

2025-01-02 10:51 UTC, useon commented on frontend/src/lib/googleAnalytics/hooks/useInitializeGA.ts
> +    ReactGA.initialize('G-3BFVVPQT0Z');
# 🙏 제안 🙏
해당 넘버도 환경 변수로 만들어서 사용하는 것은 어떨까요? 민감 정보는 아니지만 외부에서 가짜 트래픽을 전송하여 분석 데이터를 왜곡할 수도 있다고 하네요 ?!

2025-01-02 10:51 UTC, useon commented on frontend/src/lib/googleAnalytics/vote.ts
> +    label: '오른쪽 버튼 클릭',
# 🙏 제안 🙏
왼쪽 버튼보다 첫번째 선택지 또는 왼쪽 선택지 이런 식이 더 명확하지 않을까요 ?!

2025-01-14 01:20 UTC, novice0840 commented on frontend/src/hooks/useGetUserInfo.ts
> -  }
다른 곳으로 옮겨졌습니다! 하나의 hook이 2개의 기능을 한다고 판단되어 리팩토링하여 해당 코드를 이동 시킨 상황입니다.

2025-01-14 01:24 UTC, novice0840 commented on frontend/src/lib/googleAnalytics/hooks/useInitializeGA.ts
> +    ReactGA.initialize('G-3BFVVPQT0Z');
환경변수로 만들까 생각하긴 했었는데
public에 있는 index.html에서 이미 해당 값을 사용하고 있어서 useInitialize에서 환경변수로 바꿔도 값이 숨겨지지 않을 것 같아요. public 폴더에서는 환경변수를 사용하지 못하더라고요.

2025-01-14 01:29 UTC, novice0840 commented on frontend/src/lib/googleAnalytics/vote.ts
> +    label: '오른쪽 버튼 클릭',
음 괜찮을 것 같군요. 네 변경했습니다!

2025-01-14 01:34 UTC, merged