[FEAT] admin UI 퍼블리싱 및 기능 구현
woowacourse-teams/2024-ddangkong pull request #452
Opened 2024-12-30 05:40 UTC by rbgksqkr

## Issue Number
#448 

## As-Is

- 어드민 퍼블리싱 및 기능 구현 X (피그마로만 디자인한 상태)

## To-Be

- 어드민 로그인 화면 퍼블리싱
- 어드민 컨텐츠 조회 화면 퍼블리싱
  - 컨텐츠 카테고리별 조회 기능 구현
  - 컨텐츠 추가, 삭제, 수정 기능 구현
  - IntersectionObserver를 활용하여 페이지 하단 그라데이션 추가하여 컨텐츠가 더 있다는 것을 UI로 표현

현재는 API 명세를 보고 msw로 완성한 상태이며 실제 서버와 연동해봐야 합니다.

구현되지 않은 기능은 다음과 같습니다.

- 로그인
- 로그아웃

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot

|어드민 시연 영상|
|:-:|
|<video src="https://github.com/user-attachments/assets/28870d55-5a19-4859-94ce-2bba30efb7b4" />|

## (Optional) Additional Description

## 생각보다 PR 볼륨이 많이 커진...

근데 사실 퍼블리싱이 대부분이고 로직은 복잡하진 않습니다. 
리뷰를 한다면 `기존에 Modal의 onConfirm으로 항상 실행 함수를 넘기던 형식에서 모달의 데이터로 함수를 실행하는 부분` 만 집중적으로 보시면 될 것 같습니당

파일 체인지가 비정상적으로 많은데 4200줄 중 2270줄이 packge-lock이고, 모달 350줄, 드랍다운 200줄, 토스트 100줄, msw 150줄 목데이터 100줄 ...

>빼도 1100줄이네요 하하

### 컴포넌트 구조

컴포넌트 구조는 다음과 같습니다.

컨텐츠 페이지가 복잡해서 컨텐츠 페이지만 그림으로 표현해봤습니다. 전체적인 구조는 다음과 같고, 질문 추가를 누르면 질문 추가 모달(ContentAppendModal)이, 삭제 버튼을 누르면 삭제 모달(DeleteModal)이 뜨게 됩니다.

<img width="700" alt="image" src="https://github.com/user-attachments/assets/16dcc349-8edc-4d16-9129-1a4dd2973eb5" />

## 서비스 로직에서 가져온 코드

전혀 겹치지 않는다고 생각했지만 기존 서비스에서 사용한 코드가 꽤 생겼습니다. 중복되는 게 많을수록 모노레포 도입 이유가 된다고 생각하는데, 중복해서 사용하고 있다고 느낀 것을 작성해보면 다음과 같습니다.

- 같은 라이브러리를 똑같이 설치함
- eslint, prettier, tsconfig, vite.config 설정를 또 해줘야함
- Dropdown
- Modal UI, Toast UI
- ModalProvider, ToastProvider

2025-01-02 17:47 UTC, useon requested changes
어드민의 제왕 어드민의 신 조마루 !! 커밋 수를 봐 .. 너무 열심히 하잖아 . 무서워 겁먹었지만 중복 코드나 설정 코드들이 많고 집중할 부분에 대해 작성을 해주어서 중점적으로 봐야할 부분을 알 수 있었어요 상세 PR 감사합니다 ^^! ~~(하지만 너무 PR이 크긴 했어)~~ 질문 위주의 코멘트를 달았으니 답장 기다리겠읍니다 ^ .^ 아싸 우리도 이제 어드민 있다 ..

2025-01-02 17:47 UTC, useon commented on frontend-admin/src/pages/ContentPage/hooks/useLogoutMutation.ts
> +      .replace(/=.*/, '=;expires=' + new Date(0).toUTCString() + ';path=/');
# 💭 질문 💭
해당 로직은 로그아웃시에만 쓰이나요? util로 분리해도 좋지 않을까 생각하긴 했는데, 이 곳에서만 쓰인다면 함께 놔둬도 괜찮을 것 같네요!

2025-01-02 17:47 UTC, useon commented on frontend-admin/src/pages/LoginPage/hooks/UseLoginMutation.ts
> +const UseLoginMutation = () => {
# 💭 질문 💭
해당 mutation hook만 대문자로 시작하는 이유가 있나요? !

2025-01-02 17:47 UTC, useon commented on frontend-admin/src/pages/LoginPage/components/LoginInputContainer/LoginInputContainer.tsx
> +        placeholder="비밀번호를 입력해주세요"
# 💭 질문 💭
닉네임과 비밀번호는 이미 만들어 놓고 개인마다 부여된 닉네임과 비밀번호를 사용하는 방식인 건가요?

2025-01-02 17:47 UTC, useon commented on frontend-admin/src/pages/ContentPage/components/ContentContainer/ContentList/DeleteModal/DeleteModal.tsx
> +const DeleteModal = ({ isOpen, onClose, onConfirm, message, title }: DeleteModalProps) => {
# 💭 질문 💭
ContentAppendModal과 달리 해당 모달에는 ModalState 타입을 쓰지 않고 Props를 정의하여 사용하는 방식으로 작성되었나요 ? 한 가지 방식으로 통일하는 것도 좋다고 느낍니 !

2025-01-02 17:47 UTC, useon commented on frontend-admin/src/types/modal.ts
> +  onConfirm?: (arg?: any) => void;
# 🙏 제안 🙏
any 타입 대신에 제네릭으로 만들어서 사용하는 방법은 어떤가용 ?!!

2025-01-03 16:08 UTC, rbgksqkr reviewed
코멘트 확인했습니다:)

2025-01-03 16:08 UTC, rbgksqkr commented on frontend-admin/src/pages/LoginPage/components/LoginInputContainer/LoginInputContainer.tsx
> +        placeholder="비밀번호를 입력해주세요"
닉네임은 누가 admin에 접속했는지 로그를 찍기 위함이고, 비밀번호는 공유된 관리자 비밀번호를 사용하시면 됩니다!

2025-01-03 16:08 UTC, rbgksqkr commented on frontend-admin/src/types/modal.ts
> +  onConfirm?: (arg?: any) => void;
으음 시도를 해봤었는데 Modal이 컴포넌트의 JSX문에 있는 게 아니라 showModal에 제네릭을 넘겨줘야하는 형식인데 잘 안되더라구요 혹시 떠오르는 방법이 있나요 ?!

2025-01-05 06:13 UTC, useon approved these changes
코멘트와 리뷰 반영 확인했습니다 고생 많으셨어요 ! 🤗

2025-01-05 06:13 UTC, useon commented on frontend-admin/src/pages/ContentPage/components/ContentContainer/ContentList/ContentAppendModal/ContentAppendModal.tsx
> +    };
newErrors 변수를 말했던 거였습니당 !

2025-01-05 06:13 UTC, useon commented on frontend-admin/src/types/modal.ts
> +  onConfirm?: (arg?: any) => void;
ModalProvider 내부 코드부터 다 제네릭 타입을 정의해야 할 것 같아요 .. 🤔 코드의 수정이 너무 많아질 수 있으니 현재 방식으로 놔두는 것도 괜찮겠네요 !

2025-01-05 13:37 UTC, rbgksqkr commented on frontend-admin/src/pages/ContentPage/components/ContentContainer/ContentList/ContentAppendModal/ContentAppendModal.tsx
> +    };
아하 함수로 분리하면 좋긴 하겠네용
다만 해당 부분은 리팩토링 부분이라고 생각해서 추후에 적용해보도록 하겠습니다!

2025-01-05 13:39 UTC, merged