[FEAT] 진행 상황 알림 Discord 봇 구현
woowacourse-teams/2024-ddangkong pull request #454
Opened 2024-12-30 12:20 UTC by novice0840

## Issue Number

#443 

## As-Is

## To-Be

## Check List
- [ ] 테스트가 전부 통과되었나요?
- [ ] 모든 commit이 push 되었나요?
- [ ] merge할 branch를 확인했나요?
- [ ] Assignee를 지정했나요?
- [ ] Label을 지정했나요?

## Test Screenshot

## (Optional) Additional Description

2025-01-01 10:38 UTC, rbgksqkr requested changes
고생하셨습니다 포메~! 진행 상황 알려주는 봇으로 직접 알려주지 않아도 자동화하는 게 좋네용
다만 열려있는 PR에 대해 오늘 날짜의 커밋 개수를 보여주는 게 작업 현황 공유에 큰 효용이 있을지는 살짝 모르겠어서 자세히 설명해주시면 좋을 것 같아요!

2025-01-01 10:38 UTC, rbgksqkr commented on .github/workflows/progress-alarm.yml
> +                const now = new Date();
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
한국 기준으로 계산되는 건가요?

2025-01-01 10:38 UTC, rbgksqkr commented on .github/workflows/progress-alarm.yml
> +                  since: startOfYesterday.toISOString(),
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
toISOString는 utc 기준이여서 한국 기준으로 계산되어야 할 것 같아요!

2025-01-01 10:38 UTC, rbgksqkr commented on .github/workflows/progress-alarm.yml
> +                const commits = await getCommits(owner, repo, branch);
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
하루동안 한 작업량을 알림준다고 생각했는데 이러면 열려있는 PR의 커밋 중 오늘 날짜의 커밋만 가져오는 건가요?

2025-01-01 16:10 UTC, novice0840 commented on .github/workflows/progress-alarm.yml
> +                  since: startOfYesterday.toISOString(),
자정 시간을 잘못 계산했네요 ㅠ 

한국 기준에 맞게 수정하였습니다!

2025-01-01 16:11 UTC, novice0840 commented on .github/workflows/progress-alarm.yml
> +                const commits = await getCommits(owner, repo, branch);
오전 7시에 전날 24시간 동안 작업된 commit들을 가져오는 방식입니다!

2025-01-01 16:30 UTC, novice0840 commented
네, 피드백 확인하고 수정사항 반영하였습니다! 

commit 수는 처음에는 commit 메세지를 정리해서 보여주면 어떤 작업을 했는지 구체적으로 알 수 있을거라 생각했습니다. 
근데 commit 메세지까지 하나하나 다 보여주게되면 텍스트의 양이 너무 많아질 거라 생각해서 commit의 갯수를 보여줘 
각 PR의 작업량을 보여주는 게 나을 것 같다고 생각해 `Issue 이름: commit 갯수`의 형태로 메세지가 구성되었습니다.

2025-01-01 16:31 UTC, novice0840 commented on .github/workflows/progress-alarm.yml
> +                const now = new Date();
시간대 한국 기준으로 수정하였습니다. !

2025-01-05 06:34 UTC, useon approved these changes
좋네요 포메 ! 비대면으로 있어서 지금 누가 작업 중인지 어떤 작업 중인지 프론트 같은 경우에는 PR이 올라와서 리뷰 요청을 해야 알 수 있는데 (백엔드는 그 알림도 없기도 하고) 이제는 PR 올리기 전 작업 중에도 알 수 있겠네요 ~ !

꼭 반영하지 않아도 되지만 이슈 제목에다 해당 이슈의 바로가기 링크를 넣는 방법도 좋을 것 같아요! 아무래도 어떤 의도로 이 작업을 하고 있는지 자세하게 컨공이 안 된 경우가 있을 수 있으니 !!

필요한 부분이 무엇인지 고민하고 척척 만들어 낸 포메 칭찬해 ~~~ 수고했어요 🤗🤗

2025-01-14 02:48 UTC, merged