[FEAT] 방 생성 및 참여 기능 구현
woowacourse-teams/2024-ddangkong pull request #64
Opened 2024-07-24 06:46 UTC by jhon3242

## Issue Number
#56 

## As-Is

Sprint 2 P2에 맞추어 주제, 방 생성 및 참여 API 구현

## To-Be

- 방 생성 API 추가
- 방 참여 API 추가

## Check List
- [X] 테스트가 전부 통과되었나요?
- [X] 모든 commit이 push 되었나요?
- [X] merge할 branch를 확인했나요?
- [X] Assignee를 지정했나요?
- [X] Label을 지정했나요?

## Test Screenshot
<img width="711" alt="image" src="https://github.com/user-attachments/assets/4ce48bcd-7b62-4cb9-a860-7acc575858b3">

## (Optional) Additional Description

2024-07-24 07:20 UTC, leegwichan reviewed
타콩! 빠르게 구현하느라 고생 많았어!
일단 내 눈에 보이는 부분 위주로 봤어 한 번 확인해 줘!

2024-07-24 07:20 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    }
의견) 여기도 Validation 들어가야하지 않나요? 

```suggestion
    public RoomJoinResponse joinRoom(@PathVariable @Positive Long roomId, @RequestBody @NotNull String nickname) {
        return roomService.joinRoom(nickname, roomId);
    }
```

2024-07-24 07:20 UTC, leegwichan commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +        }
의견) 사용하지 않는 변수들을 제거해 보았습니다~

```suggestion
        @Test
        void 존재하지_않는_방에_참여시_예외를_던진다() {
            // given
            String nickname = "나는참가자";
            Long nonExistId = 99999999999L;

            // when & then
            assertThatThrownBy(() -> roomService.joinRoom(nickname, nonExistId))
                    .isInstanceOf(BadRequestException.class);
        }
```

2024-07-24 07:20 UTC, leegwichan commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +        Member member = memberRepository.save(new Member(nickname, room, true));
사소한 의견)  Member에 정적 팩토리 메서드를 도입해서 `createMaster(nickname, room)`, `createCommon(nickname, room)`을 만드는 건 어떨까요?

2024-07-24 07:35 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +        Member member = memberRepository.save(new Member(nickname, room, true));
그게 의미가 더 잘 전달 될 것 같네요! 바로 반영해볼게요~

2024-07-24 08:33 UTC, GIVEN53 requested changes
고생했어요 딱칸~~ 컨트롤러 테스트도 추가해주시면 감사하겠습니다 🙃

2024-07-24 08:40 UTC, PgmJun reviewed
고생하셨습니다 타칸! 리뷰 확인 부탁드려요 :)

2024-07-24 08:40 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/member/dto/MemberResponse.java
> +    public MemberResponse(Member member) {
사소한 의견) 한칸 띄워야하지 않나용?

2024-07-24 08:40 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    public RoomJoinResponse joinRoom(@PathVariable @Positive Long roomId, @RequestBody String nickname) {
의견) PostMapping("/balances/rooms/{roomId}/members") 만 써주어도 되지 않을까요? 두 개를 다 써주신 이유가 있는 지 궁금합니다~

2024-07-24 08:40 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/room/RoomController.java
> +    public RoomJoinResponse joinRoom(@PathVariable @Positive Long roomId, @RequestBody String nickname) {
의견) ResponseEntity로 감싸주지 않고 있는데 created, ok 등 설정하려면 필요하지 않을까 싶습니다~
아니라면 ResponseStatus 애노테이션 사용을 하는 방법도 있습니다

2024-07-24 08:40 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/member/Member.java
> +    }
의견) 아까 보여주셨던 정팩메 사용해서 처리해주셔도 좋을거 같아요! createRoomMaster? 네이밍으로 말씀해주셨던 부분이요!

2024-07-24 08:40 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    public RoomJoinResponse createRoom(String nickname) {
동의합니다~

2024-07-24 08:40 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +            RoomJoinResponse roomServiceRoom = roomService.createRoom(nickname);
사소한 의견) 커찬이 검증할 매개변수명을 actual로 스타트 끊어주셔서 이어가도 좋을 것 같아요:)

2024-07-24 08:40 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +            assertThatThrownBy(() -> roomService.joinRoom(nickname, nonExistId))
의견) given, when&then 이 맞지 않을까요??

2024-07-24 10:22 UTC, jhon3242 commented on backend/src/main/java/ddangkong/domain/balance/content/Room.java
> -@NoArgsConstructor(access = AccessLevel.PROTECTED)
RoomService 에 createRoom 메서드에서 Room 객체를 생성해야하는데, Default 값을 통해 생성자를 생성하려면 기본생성자가 호출해야하더라고요~ 그래서 지워주었습니다!

2024-07-24 10:24 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/balance/member/dto/MemberResponse.java
> +    public MemberResponse(Member member) {
클레스는 띄어주는게 맞는데 레코드도 띄어줘야할까요?? 이 부분에 대해선 컨벤션으로 정하지 않았던 것 같아요~ 내일 다 같이 말해보죠!

2024-07-24 10:28 UTC, jhon3242 reviewed
리뷰 반영했습니다!😊 다시 한번 확인 부탁드립니다~~

2024-07-24 10:55 UTC, leegwichan approved these changes
오! 타칸 빠른 반영~~ 고생했어!! 리뷰한 내용들은 전부 문제없는 것 같아!
(Merge의 일감은 이든에게로 넘어가나요? ㅋㅋ)

2024-07-25 01:48 UTC, PgmJun approved these changes

2024-07-25 01:48 UTC, PgmJun approved these changes
LGTM!

2024-07-25 02:11 UTC, merged