[FEAT] 방 전체 멤버 조회
woowacourse-teams/2024-ddangkong pull request #65
Opened 2024-07-24 07:21 UTC by PgmJun

## Issue Number
#62 

## As-Is

## To-Be

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
<img width="343" alt="image" src="https://github.com/user-attachments/assets/2a9bd9cd-105b-42a1-bc44-9a2cb3b5614a">
<img width="816" alt="스크린샷 2024-07-24 16 17 20" src="https://github.com/user-attachments/assets/b309e827-6610-4305-821c-6e6faf9d0ae4">

## (Optional) Additional Description

2024-07-24 08:23 UTC, leegwichan approved these changes
비즈니스 로직적으로 문제는 없어보여요~ 파일 위치만 한 곳 꼭 옮겨주세요!

2024-07-24 08:43 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    public RoomMembersResponse findAllRoomMember(Long roomId) {
질문) 트랜잭션 readOnly 설정 안하신 이유가 있나요??

2024-07-24 08:43 UTC, GIVEN53 reviewed
고생했어요 든든~~ 질문 하나 남겨뒀습니다 확인 부탁드려요!

2024-07-24 08:49 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    public RoomMembersResponse findAllRoomMember(Long roomId) {
조회를 단 한 번만 수행하기 때문에 트랜잭션 설정을 통해 영속성 컨텍스트의 이점을 얻을 이유가 없다고 생각해서 굳이 설정해주진 않았습니다!

2024-07-24 08:51 UTC, jhon3242 requested changes

2024-07-24 08:51 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    private final MemberRepository memberRepository;
의견) 개행을 주는게 컨벤션이니까 통일해주면 좋을 것 같아요~
```suggestion
    private final RoomRepository roomRepository;
    
    private final MemberRepository memberRepository;
```

2024-07-24 08:51 UTC, jhon3242 commented on backend/src/main/java/ddangkong/controller/balance/room/dto/RoomMemberResponse.java
> +    }
의견) 저도 이 부분은 생정자로 할 것 같아요~ from을 통해 추가적인 의미 전달이 없는 것 같아요~

2024-07-24 08:59 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    private final MemberRepository memberRepository;
꼼꼼한 컨벤션 체크 감사합니다!

2024-07-24 09:05 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    }
전 상관없습니다~!
그러면 ErrorResponse 객체도 위와 같이 되어있는데, 통일성을 위해서 같이 변경해서 커밋올릴게요~

2024-07-24 09:12 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    public RoomMembersResponse findAllRoomMember(Long roomId) {
roomRepository.getById()
memberRepository.findByRoom(room)
두 번 조회가 이루어지는 것 같아요 지금은 각각의 트랜잭션에서 수행되어도 문제없지만 어떤 이유가 있었는지 궁금했습니다 😁

2024-07-24 12:54 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
> +    public RoomMembersResponse findAllRoomMember(Long roomId) {
한번 조회된다는 것은 동일한 데이터가 한 번 조회된다는 것을 말씀드린건데 제가 이해하기 어렵게 말씀드렸네요..! 죄송합니닷!
OSIV 부분은 한 번 학습해보겠습니다 확인해보고 고려대상이라면 변경해두겠습니다~!

2024-07-24 14:18 UTC, GIVEN53 approved these changes
LGTM 🥰🥰🥰

2024-07-25 02:25 UTC, jhon3242 approved these changes
LGTM

2024-07-25 07:01 UTC, closed without merging