[TEST]: Room API 문서 테스트 추가
woowacourse-teams/2024-ddangkong pull request #86
Opened 2024-07-28 13:06 UTC by jhon3242

## Issue Number
#85 

## As-Is

방에 대한 API 문서가 노션으로만 존재

## To-Be

- Spring rest docs 를 활용한 Room API Test 추가
- room.adoc 추가
- index.adoc 에 room.adoc 경로 추가

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/87820cb5-fea8-450e-8bb0-ea6414bc7ac9)

## (Optional) Additional Description

2024-07-29 05:49 UTC, PgmJun reviewed
제 담당 API까지 처리해주셨네요~!
감사합닏 타칸! 리뷰 남겨두었으니 확인 부탁드려요~!

2024-07-29 05:49 UTC, PgmJun commented on backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
> +                            ),
의견) 추가로 members 배열에 대한 설명도 적어줘서 더 구체적인 문서로 만들면 어떨까 싶어요!

```java
fieldWithPath("members").type(JsonFieldType.ARRAY).description("방에 참여중 인원 목록")
```

2024-07-29 05:49 UTC, PgmJun commented on backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
> +                            ),
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/14c3434b-b436-40db-86cb-7a4397c38e65">

2024-07-29 09:28 UTC, leegwichan approved these changes
LGTM!
타칸 고생했어! 이든이 말해 준 내용만 수정하면 좋을 것 같아! 주말에 고생 많았어!!!

2024-07-29 09:29 UTC, GIVEN53 requested changes
헷갈리는 부분이 많았을 것 같은데 잘 적용해주셔서 감사합니다 👍🏻

2024-07-29 09:29 UTC, GIVEN53 commented on backend/src/docs/asciidoc/room.adoc
> +requestFields
사소한 의견) 띄어쓰기가 불편,, 크흠 🙃

2024-07-29 09:29 UTC, GIVEN53 commented on backend/src/docs/asciidoc/room.adoc
> +
의견)

⭐️ 스니펫 포함 순서

1. curl-request
2. http-request
3. request 스펙 관련
    3.1. path variables
    3.2. query parameters
    3.3. request fields
4. http-response
5. response 스펙 관련

https://github.com/woowacourse-teams/2024-ddangkong/pull/71 에서 설명 드린 스니펫 포함 순서를 적용해주시면 감사하겠습니다!

2024-07-31 07:21 UTC, jhon3242 commented on backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
> +            when(roomService.createRoom(anyString())).thenReturn(response);
저 같은 경우 given 에는 변수를 선언하는 부분을, when 절에는 테스트 전에 동작되어야 하는 작업들을 정의하는 편이에요 이런 기준에서는 response 도 변수로 정의되는 부분이여서 given 절에 주로 놔두는 것 같아요~ 

이든은 어떤 기준으로 given 과 when 절을 나누는지 궁금해요!

2024-07-31 08:33 UTC, PgmJun commented on backend/src/test/java/ddangkong/documentation/balance/room/RoomDocumentationTest.java
> +            when(roomService.createRoom(anyString())).thenReturn(response);
좋은 질문이네요!
저도 타칸과 비슷한 의견입니다~

- given은 테스트에 필요한 준비 데이터를 정의해놓는 용도
- when은 동작 실행
- then은 검증부로 사용합니다.

이때 저는 타칸이 해당 코드에 작성해주신 Mockito 의 when() 메서드와 같은 모킹 로직 또한 given에 두는 편입니다.
when은 동작 실행부분이며 모킹도 테스트를 위한 세팅이니까요!

그런데 타칸은 모킹을 when의 영역으로 보고 계신 것 같아서 그렇게 되면 모킹에 사용되는 데이터도 when 영역에 넣어주는게 맞지 않을까 해서 사소한 리뷰를 남겨보았습니다!

2024-07-31 09:04 UTC, merged