[REFACTOR] 중복 로직 및 객체 제거, 매핑 로직 분리
woowacourse-teams/2024-ddangkong pull request #87
Opened 2024-07-29 02:08 UTC by leegwichan

## Issue Number
Closed #83 

## As-Is & To-Be

아래의 내용은 제가 **제안**하는 리팩터링 내용입니다~
일부만 반영해도 혹은 전부 반영하지 않아도 됩니다. 다양한 의견 부탁드립니다~~

## 리뷰는 커밋 단위로 하시는 것을 추천 드립니다~

### `BalanceOption` 검증 로직

- 문제
  - `BalanceOption`이 2개를 확인하는 로직이 모든 서비스 계층에서 사용
  - 앞으로도 중복될 가능성 높음
- 해결 방법
  - 조회된 옵션이 2개인지 확인하는 도메인 객체 `BalanceOptions` 도입
  - `BalanceOptionRepositoy`에서 default method `findBalanceOptionsByBalanceContent()`를 통해 `BalanceOptions`으로 조회하도록 변경
- [해당 코드](https://github.com/woowacourse-teams/2024-ddangkong/commit/316237dc2b2dda42e84944fbe8f9e5f47b7c7ed9)

### DTO 재사용 실시
- 문제 
  - RoomMemberResponse와 MemberResponse가 같은 형식으로 다른 곳에서 사용됨
- 해결 방법
  - RoomMemberResponse을 제거하고, MemberResponse로 사용
- [해당 코드](https://github.com/woowacourse-teams/2024-ddangkong/commit/14bc9194e200d902a620628d7313ad0279e204b1)

### DTO Mapping 로직

- 문제
  - 비즈니스 계층에 DTO 매핑 로직이 일부 있음
  - 서비스 계층은 비즈니스 플로우의 책임을 가지므로, 매핑 로직까지 있다면 플로우를 보기 힘들어짐
- 해결 방법
  - 일부 서비스 계층의 매필 로직을 DTO의 정적 팩토리 메서드를 통해 내부로 옮김
- 해당 코드
  - [MembersResponse의 매핑 로직 이동](https://github.com/woowacourse-teams/2024-ddangkong/commit/7a8f1d1a8de3a7744f09cd91b7138ab582922181)
  - [BalanceContentGroupResponse, BalanceContentTotalResponse의 매핑 로직 이동](https://github.com/woowacourse-teams/2024-ddangkong/commit/20dc52cf75d199967a64895a08078d92e81326cc)

### SQL 횟수 최적화

- 문제 
  - `BalanceVoteService`의 투표 생성 로직 중
    - optionId, contentId를 통해 BalanceOption을 조회하는데, DB에 2번 요청함
    - memberId, roomId를 통해 Member를 조회하는데, DB에 2번 요청함
- 해결 방법
  - `BalanceOptionRepository.findByIdAndContentId()`를 통해 SQL 한 번만으로 조회함
  - `MemberRepository.findByIdAndRoomId()`를 통해 SQL 한 번만으로 조회함

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/51c01c73-11de-4aca-bbdb-e86f27340fa2)

## (Optional) Additional Description

### 추가 논의 사항
- Member 는 domain.`member`.Member에 존재하는데, MemberResponse는 controller.`balance.member`.dto 에 존재한다. 이를 어느쪽으로 통일할까?

### Facade를 도입하지 않은 이유

- Facade에서는 비즈니스 플로우, 일반 Service에서는 기본적인 CRUD를 관리하려 했었다
  - 하지만 Facade와 Service가 명확성있게 구분되기 힘들다고 생각했다.
- 일반 Service의 기본 로직만 넣어서 분리한다 하더라도, 서비스에서 사용되는 중복 로직이 유의미하게 줄어들지 않는다고 생각했다.
  - 예를 들어, `BalanceContentResponse`로 조회하는 로직은 2군데에서 사용하고 있지만, 이를 하위 계층의 서비스를 도입한다고 해서 `roomContent 조회`, `balanceOptions 조회` 2가지는 중복된다.

2024-07-29 15:37 UTC, GIVEN53 requested changes
중복 로직이 많이 제거되었네요 고생했어요 꺽찬 👍🏻

2024-07-29 15:37 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
> +        return new BalanceOptions(findAllByBalanceContent(balanceContent));
의견) List는 empty로 비어있음을 나타낼 수 있어서 findXX의 컨벤션을 따르는게 맞지만, `BalanceOptions`는 일급컬렉션이기 때문에 항상 객체가 존재, 따라서 getXX가 좀 더 의도에 맞지 않을까 의견드립니다!

2024-07-30 03:57 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentTotalResponse.java
> +                                                 Long secondOptionCount) {
`BalanceContentGroupResponse`는 "팀원들의 결과" 정보가 필요해서 List<BalanceVote>의 형태로 받고, `BalanceContentTotalResponse `는 "유저 전체 결과" 정보가 필요해서 Long의 형태를 받습니다. 만약 List<BalanceVote>의 형태로 받게 된다면 너무 많은 List<BalanceVote>가 될 것 같아 Long의 형태로 받았습니다~

2024-07-30 03:57 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/option/BalanceOptionRepository.java
> +        return new BalanceOptions(findAllByBalanceContent(balanceContent));
리뷰 반영했습니다~

2024-07-30 05:10 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/controller/balance/content/dto/BalanceContentTotalResponse.java
> +                                                 Long secondOptionCount) {
조회 쿼리가 다르군요 이해했습니다!

2024-07-30 05:11 UTC, GIVEN53 approved these changes
LGTM!

2024-07-30 12:31 UTC, jhon3242 approved these changes
전반적으로 코드 길이도 많이 줄어졌네요! 커찬이 있기에 행복합니다~😁
수고했어 커찬~

2024-07-30 12:31 UTC, jhon3242 commented on backend/src/main/java/ddangkong/service/balance/room/RoomService.java
>      }
👍 하나로 통일해준 커찬 칭찬해~

2024-07-30 15:32 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/member/dto/MembersResponse.java
> +public record MembersResponse(
질문) DTO 재사용 실시 부분을 보면 MembersResponse가 같은 형식으로 다른 곳에서 사용되는 걸 리팩토링 해주셨다고 해주셨는데
develop 브랜치를 살펴보니 MembersResponse라는 객체는 원래 없고
첨부해주신 부분을 흝어봐도 RoomMembersResposne를 제거 후 MembersResponse를 새로 구현해서 똑같은 동작을 하는 이름만 다른 객체로 갈아끼운 것으로 보이는데 맞을까요??

아래는 develop 브랜치에서 MembersResponse 클래스를 조회한 결과입니다!
<img width="554" alt="image" src="https://github.com/user-attachments/assets/3d9eab57-76ca-4d6b-ad70-ac14b0757355">

2024-07-30 15:36 UTC, PgmJun commented on backend/src/main/java/ddangkong/service/balance/vote/BalanceVoteService.java
> +                .orElseThrow(() -> new BadRequestException("해당 방의 멤버가 존재하지 않습니다."));
깔꼼하네요 굿굿!!

2024-07-30 15:38 UTC, PgmJun approved these changes
고생하셨숩니다 커찬~! 꼼꼼히 체크해주셔서 코드가 예뻐졌군요 ㅎㅎㅎ
감사하게도 보기 편하게 커밋 단위로 남겨놔주셔서 더 눈에 잘 들어왔네요!
의견 남겨놨는데 커밋단위로 보느라구 리뷰를 싱글코멘트로 달았습니다ㅠ
사소한 의견들이기 때문에 바로 승인해둘게요! 보시고 괜찮으면 반영부탁드려요~!

2024-07-30 15:40 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/member/dto/MembersResponse.java
> +public record MembersResponse(
추가로 RoomMembersResponse는 스프린트3에서 방의 정보와 회원의 정보를 함께 조회하게 될 DTO라서 MembersResponse 대신 RoomMembersResponse로 네이밍을 가져가는게 어떨까 싶습니다~!

2024-07-31 01:00 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/member/dto/MembersResponse.java
> +public record MembersResponse(
의도 확인했습니다! 의도 반영해서 수정했습니다!

2024-07-31 01:00 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/member/dto/MembersResponse.java
> +    public static MembersResponse from(List<Member> members) {
추후 논의해보도록 하겠습니다!

2024-07-31 01:01 UTC, merged