[FEAT] 공통 모달 컴포넌트 구현
woowacourse-teams/2024-ddangkong pull request #91
Opened 2024-07-29 19:02 UTC by useon

## Issue Number
#60 

## As-Is

여러 곳에서 사용되는 모달을 공통 컴포넌트 생성을 통해 효율적을오 재사용하고자 했다.

## To-Be

- [x] 모달 컴포넌트 구현
- [x] 모달 밖 영역 클릭시 모달 닫기 기능
- [x] 모달에서 esc 키를 눌렀을 때 모달 닫기 기능
- [x] 모달 뒤 영역 스크롤 방지 기능

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
![image](https://github.com/user-attachments/assets/349965ed-191e-4168-84eb-608c50b1ab9e)
![image](https://github.com/user-attachments/assets/e841ce10-f96e-4698-8cd0-f380e088065a)
![image](https://github.com/user-attachments/assets/c76921fb-46fd-4b6b-9ad8-b8b21e56dc5c)
![image](https://github.com/user-attachments/assets/8fbdd0f9-971b-464d-ba55-f43d1b2556bc)

## (Optional) Additional Description
합성 컴포넌트로 모달 컴포넌트를 구현하였습니다. 

# 공통 모달 컴포넌트 사용법

# **프로퍼티**

> ### 필수 프로퍼티
> - isOpen: 모달이 열려있는지의 여부를 결정합니다. (boolean)
> - onClose: 모달을 닫을 때 호출되는 함수입니다.
> - position: 모달의 위치를 결정합니다. ('top' | 'bottom' | 'center')
> 
> ### 선택 프로퍼티
> - style: 모달의 스타일을 직접 지정할 수 있습니다. (CSSProperties)
> - onConfirm: 모달에서 입력된 값을 확인할 때 호출되는 함수입니다.

# 서브 컴포넌트

## **Modal.Header**
모달의 헤더 부분입니다.

> ### Modal.Title
> 모달 헤더의 제목입니다.
> 
> - fontSize?: 제목의 폰트 크기를 조절할 수 있습니다. (기본값: 2rem)
> - fontWeight?: 제목의 폰트 굵기를 조절할 수 있습니다. (기본값: bold)
> ### Modal.IconButton
> 이미지 아이콘 버튼입니다.
> - src: 이미지 버튼에 들어가는 이미지를 설정할 수 있습니다. (기본값: 닫기 이미지)
> - imgSize?: 버튼에 들어가는 이미지의 크기를 조절할 수 있습니다. (기본값: 1.6rem)
> ### Modal.TextButton
> 텍스트 버튼입니다. 버튼 크기와 폰트 크기를 받을 수 있으며, 모달을 닫는 등의 동작에 사용할 수 있습니다.
> - buttonWidth?: 버튼의 너비를 조절할 수 있습니다. (기본값: 100%)
> - buttonHeight?: 버튼의 높이를 조절할 수 있습니다. (기본값: 100%)
> - fontSize?: 버튼 폰트 크기를 조절할 수 있습니다. (기본값: 1.6rem)
> - backgroundColor?: 버튼 배경색을 조절할 수 있습니다. (기본값: Theme.color.peanut400)
> - fontColor?: 버튼 폰트 색상을 조절할 수 있습니다. (기본값: #000000)

## **Modal.Content**
모달의 내용 부분입니다.

> ### Modal.Input
> 모달 내부에 사용될 입력 필드입니다.

## **Modal.Footer**
모달의 푸터 부분입니다.

> - buttonPosition?: 버튼의 정렬 위치를 설정할 수 있습니다. (기본값: center)
> - buttonGap?: 버튼 간의 간격을 설정할 수 있습니다. (기본값: 1.2rem)

## **스타일 커스터마이징**
- 기본 스타일 외에도 style 프로퍼티를 사용하여 직접 스타일을 지정할 수 있습니다.

## **모달 기능**
- ESC 키로 모달 닫기: 사용자가 ESC 키를 누를 때 모달을 닫을 수 있습니다.
- 배경 클릭으로 모달 닫기: 모달 외부(배경)을 클릭할 때 모달을 닫을 수 있습니다.
- 배경 스크롤 방지: 모달이 열려 있을 때 배경의 스크롤을 방지합니다.

### 전체 코드 예시
```jsx
import React, { useState } from 'react';
import Modal from './Modal';
import CloseIcon from '@/assets/images/closeIcon.png';

function App() {
  const [isOpen, setIsOpen] = useState(false);

  const openModal = () => setIsOpen(true);
  const closeModal = () => setIsOpen(false);

  return (
    <div>
      <button onClick={openModal}>Open Modal</button>
      <Modal isOpen={isOpen} onClose={closeModal} position="center">
        <Modal.Header>
          <Modal.Title>모달 제목</Modal.Title>
          <Modal.IconButton src={CloseIcon} imgSize="20px" onClick={closeModal} />
        </Modal.Header>
        <Modal.Content>
          모달 내용
        </Modal.Content>
        <Modal.Footer>
          <Modal.TextButton onClick={closeModal}>확인</Modal.TextButton>
        </Modal.Footer>
      </Modal>
    </div>
  );
}

export default App;
```

2024-07-29 23:05 UTC, novice0840 approved these changes
모달 만드느라 수고 많았어요~~~

2024-07-29 23:05 UTC, novice0840 commented on frontend/src/components/common/Modal/hooks/useDisableBackgroundScroll.ts
> +        document.body.style.overflow = originalOverflow;
L5 - 참고 의견
----------------------------------------------------------------------
originalOverflow 를 별도의 변수로 두는 만드는 것과 
 document.body.style.overflow에 그냥 auto를 넣는게 다른가요?

2024-07-29 23:05 UTC, novice0840 commented on frontend/src/components/common/Modal/hooks/useModalEscClose.ts
> +};
L5 - 참고 의견
----------------------------------------------------------------------
esc를 누르면 modal을 닫을 수 있군요!

2024-07-30 11:19 UTC, rbgksqkr requested changes
모달 만드느라 고생하셨습니다 천재만재 썬데이~!~!~! 수정해야될 부분이 있을 것 같아 RC 드리겠습니다아 코멘트 확인해주시고 다시한번 리뷰 요청 부탁드려용

2024-07-30 11:19 UTC, rbgksqkr commented on frontend/src/components/common/Modal/Modal.tsx
> +  position: 'top' | 'bottom' | 'center';
# L5 - 참고 의견
<!-- 더 좋은지는 모르겠으나 다른 방법 제시 혹은 참고할만한 내용인 경우 -->
Modal 하면 중앙에 떠있는걸 예측할텐데 position을 옵셔널로 받고 파라미터에 기본값으로 center를 넣는 건 어떤가요??
```tsx
export interface ModalProps {
  isOpen: boolean;
  position: 'top' | 'bottom' | 'center';
  onClose: () => void;
  onConfirm?: () => void;
  style?: React.CSSProperties;
}

const Modal = ({ children, isOpen, onClose, position = 'center', ...restProps }: ModalProps) => {


```

2024-07-30 11:19 UTC, rbgksqkr commented on frontend/src/components/common/Modal/Modal.tsx
> +const Modal = ({ children, isOpen, onClose, position, ...restProps }: ModalProps) => {
# L3 - 중요 질문
<!-- 궁금증이 해소되어야 정확한 리뷰/피드백이 가능한 경우 -->
Modal의 z-index가 존재하지 않아서 다른 요소와 레이어 문제가 생기는 것 같아요! z-index를 상수로 관리하거나 createPortal를 사용해야할 것 같아요!

<img width="400" alt="image" src="https://github.com/user-attachments/assets/964f48c0-6c14-4790-9129-82726a6dccb6">

2024-07-30 11:19 UTC, rbgksqkr commented on frontend/src/components/common/Modal/Modal.styled.ts
> +export const modalTitle = ({ fontSize, fontWeight }: ModalTitleProps) => css`
# L4 - 변경 제안
<!-- 제시한 방안이 더 좋다고 생각하지만 작성자 판단에 맡겨도 무관한 경우 -->
ModalTitle이 한 곳에서만 쓰이는 것으로 확인했는데 `|| 연산자` 를 사용한 이유가 궁금해요! 확장성을 고려한 걸까요?? 현재는 ModalTitle 컴포넌트에서 넣어주고 있어서 해당 로직이 안쓰일 것 같고, css props 를 사용해도 덮어씌워지는거라 아니면 컴포넌트에서는 아예 빼는게 좋을 것 같아요!!

2024-07-30 11:19 UTC, rbgksqkr commented on frontend/src/components/common/Modal/hooks/useDisableBackgroundScroll.ts
> +        document.body.style.overflow = originalOverflow;
# L5 - 참고 의견
<!-- 더 좋은지는 모르겠으나 다른 방법 제시 혹은 참고할만한 내용인 경우 -->
저도 그냥 auto 넣었던 것 같은데 사용되는 역할이 궁금합니다!!

2024-07-30 11:19 UTC, rbgksqkr commented on frontend/src/components/common/Modal/hooks/useModalBackdropClickClose.ts
> +      document.addEventListener('mousedown', handleBackdropClick);
# L5 - 참고 의견
<!-- 더 좋은지는 모르겠으나 다른 방법 제시 혹은 참고할만한 내용인 경우 -->
클릭 이벤트가 아닌 mousedown을 사용하신 이유가 궁금해요!

2024-07-30 11:19 UTC, rbgksqkr commented on frontend/src/components/common/Modal/hooks/useModalEscClose.ts
> +const useModalEscClose = (isOpen: boolean, onModalClose: () => void) => {
# L5 - 참고 의견
<!-- 더 좋은지는 모르겠으나 다른 방법 제시 혹은 참고할만한 내용인 경우 -->
PC 사용자까지 고려한 멋쟁이 👍👍

2024-07-30 11:19 UTC, rbgksqkr commented on frontend/src/components/common/Modal/Modal.tsx
> +  useDisableBackgroundScroll(isOpen);
# L5 - 참고 의견
<!-- 더 좋은지는 모르겠으나 다른 방법 제시 혹은 참고할만한 내용인 경우 -->
훅 폼 미쳐따 분리 나이스하네용

2024-07-31 05:31 UTC, useon commented on frontend/src/components/common/Modal/hooks/useDisableBackgroundScroll.ts
> +        document.body.style.overflow = originalOverflow;
처음 originalOverflow를 콘솔에 찍어보면 visable이라는 속성이 찍힙니다. 현재 상태 그대로 복원을 원해서 auto 속성을 할당하는 것이 아니라 초기 설정 값을 변수로 만들어 다시 할당하도록 했습니다. 하지만 다시 생각해보니 모달 내 컨텐츠가 영역을 넘어갈 경우 visable 속성으로 설정되어 있다면 모달 밖으로 컨텐츠가 나올 염려가 있네요 .. !!! auto로 바꿔야겠다는 생각을 했습니다 🫠

2024-07-31 05:47 UTC, useon commented on frontend/src/components/common/Modal/Modal.tsx
```ts
interface ModalHeaderProps extends HTMLAttributes<HTMLElement> {
  children: React.ReactNode;
}

const ModalHeader = ({ children, ...restProps }: ModalHeaderProps) => {
  return (
    <header css={modalHeaderLayout} {...restProps}>
      {children}
    </header>
  );
};
```
이런 식의 짧은 코드들이고, 전부 별도의 파일로 분리하게 되면 파생된 파일이 7개가 생기게 되어 더 보기 불편할 수 있을 것 같은데 어떻게 생각하시나요 폼에 !?!!? 😆

2024-07-31 05:59 UTC, useon commented on frontend/src/components/common/Modal/Modal.stories.tsx
> +  },
global parameters에 적용하면 이를 기반으로 한 스토리들에도 동일한 parameters를 적용할 수 있는데요. 해당 코드는 말씀해 주신 대로 불필요한 것 같아 삭제하겠습니다 😆

2024-07-31 15:20 UTC, useon commented on frontend/src/components/common/Modal/Modal.tsx
> +export interface ModalProps {
좋아요 말우 ~!! 반영하여 수정하였습니다 >, <

2024-07-31 15:21 UTC, useon commented on frontend/src/components/common/Modal/Modal.tsx
> +  position: 'top' | 'bottom' | 'center';
그렇네요 저희가 지금까지 사용할 모달들을 생각했을 때 전부 position이 center 이니까 수정하였습니다 ^ __^

2024-07-31 15:23 UTC, useon commented on frontend/src/components/common/Modal/Modal.tsx
> +const Modal = ({ children, isOpen, onClose, position, ...restProps }: ModalProps) => {
마루에게 z-index로 수정할지 createPotal로 할지 조언을 구했는데 마루의 createPotal 사랑에 설득을 당해서 createPotal로 수정하였습니다 !!!!!!!!!!!!!!!!!

2024-07-31 15:32 UTC, useon commented on frontend/src/components/common/Modal/Modal.styled.ts
> +export const modalTitle = ({ fontSize, fontWeight }: ModalTitleProps) => css`
저는 modal 로직에 최대한 style 코드를 안 쓰고 싶었습니다 😂 따라서 modal style 파일에서 사용처에서 인자를 넣어주지 않아(옵션 인자) style에 전달되는 prop가 undefined일 때 default 값이 들어가고자 하는 의도로 해당 코드를 작성하였습니다 🙌

2024-07-31 15:34 UTC, useon commented on frontend/src/components/common/Modal/hooks/useModalBackdropClickClose.ts
> +      document.addEventListener('mousedown', handleBackdropClick);
처음에 click을 사용하여 구현해 보려 했지만 의도대로 동작이 되지 않고 자꾸 모달이 열리자마자 자동으로 꺼지더라고요. 따라서 mousedown을 통해서 구현을 했어요. 오늘 마루와 함께 디버깅하는 시간을 통해 아주 톡톡히 알게 되었습니다 ^. ^ click event가 두 번이 달려 모달이 열리자마자 꺼졌던 슬픈 story .. 마루의 집념 덕분에 잘 알고 갑니다 고마버요 .. 반영하여 코드 수정해 놓았습니다 🙌

2024-07-31 16:48 UTC, rbgksqkr approved these changes
적극적인 의견 반영 감사합니다!!! 토론 끝에 결국 해냈읍니다,,,내일 블로그도 작성해볼게요,,,코멘트 하나 남겼는데 참고용으로 봐주세욥 고생하셨습니당

2024-07-31 16:48 UTC, rbgksqkr commented on frontend/src/components/common/Modal/Modal.styled.ts
> +export const modalTitle = ({ fontSize, fontWeight }: ModalTitleProps) => css`
엇 저도 그부분은 동의하고 코드도 좋아요!! 그런데 제가 리뷰드린 부분은 다른 부분인 것 같은데 라인을 잘못 선택한 것 같네요 ㅎㅎ

ModalTitle 컴포넌트를 예시로 보시면 사용처에서 Modal.Title 의 props로 들어오는 style 코드는 restProps 로 rest parameter로 들어갈텐데, css 함수인 modalTitle의 인자는 현재 고정적으로 받고 있습니다! 

> modal 로직에 최대한 style 코드를 안 쓰고 싶었습니다

위 의견에 저도 동의하는데요!  그냥 고정값으로 두고 style 태그를 열어두는 것과 지금처럼 css props를 함수 인자로 받는 것과 차이가 없다고 생각합니다. 썬데이가 의도한대로 되려면 fontSize와 fontWeight가 props로 뚫려있는 게 좋을 것 같아요 실제 Title에는 글자 크기와 굵기는 자주 바뀌기도 하구요! 로직에는 영향이 없지만 같은 로직을 더 간결하게 표현할 수 있을 것 같습니당 제가 잘못 이해했다면 말씀해주세요:)
```tsx
// ❌ before
const ModalTitle = ({ children, ...restProps }: ModalTitleProps) => {
  return (
    <span css={modalTitle({ fontSize: '2rem', fontWeight: 'bold' })} {...restProps}>
      {children}
    </span>
  );
};

// ✅ after
const ModalTitle = ({ fontSize,  fontWeight, ...restProps }: ModalTitleProps) => {
  return (
    <span css={modalTitle({ fontSize, fontWeight })} {...restProps}>
      {children}
    </span>
  )
}

interface ModalTitleProps {
  fontSize?: string;
  fontWeight?: string;
}

export const modalTitle = ({ fontSize, fontWeight }: ModalTitleProps) => css`
  font-weight: ${fontWeight || 'bold'};
  font-size: ${fontSize || '2rem'};
`;
  );
};

```

2024-08-01 06:46 UTC, useon commented on frontend/src/components/common/Modal/Modal.tsx
> +interface ModalTitleProps extends HTMLAttributes<HTMLSpanElement> {
제안 고마버요 마루✨ 해당 페이지 (모달이 뜨는 것도 어떠한 페이지 안 이니까)의 h1 제목은 아닌 것 같아서 모달을 하나의 section으로 본다면 h2 제목 정도가 되지 않을까 해서 태그도 span에서 h2 태그로 수정했는데 어때보이나요 ? ?  ?  [3bb49ef](https://github.com/woowacourse-teams/2024-ddangkong/pull/91/commits/3bb49ef6353fb30b937f33ed9d675852f723eaff)

2024-08-01 06:48 UTC, useon commented on frontend/src/components/common/Modal/Modal.styled.ts
> +export const modalTitle = ({ fontSize, fontWeight }: ModalTitleProps) => css`
아 !!!! 드디어 이해했어요. 제가 기존 코드를 리팩토링 하는 과정에서 넣어뒀던 prop이 빠졌던 것 같아요. 마루 입장에서는 엥 ?!!? 의도는 이해했는데 왜 코드가 이어지지 않지 ? 했을 것 같아요 쏘리링 😂 바로 스타일 파일에 존재하지만 모달 파일에 빠진 옵션 prop을 호라락 다시 넣어주었습니다 😆 [e1b5302](https://github.com/woowacourse-teams/2024-ddangkong/pull/91/commits/e1b53026f41f204f85b3cf6e1a726ce6204e9bf3)

2024-08-01 06:51 UTC, rbgksqkr commented on frontend/src/components/common/Modal/Modal.tsx
> +interface ModalTitleProps extends HTMLAttributes<HTMLSpanElement> {
굿굿굿 너무 좋아요!@!!!

2024-08-01 08:30 UTC, merged