[FEAT] 대기방 정보 조회 기능 구현
woowacourse-teams/2024-ddangkong pull request #95
Opened 2024-07-31 07:21 UTC by PgmJun

## Issue Number
#94 

## As-Is

대기방 멤버 정보 조회 API를 대기방의 정보를 조회하는 API로 변경한다.

### Reference 🔎
[API 문서](https://www.notion.so/ghenmaru/API-8113194c91fd4d62a0808a01b156628f?pvs=4)

## To-Be

- Room 엔티티에 방의 상태 Field를 추가한다. (READY, PROGESS, END)
- Room 엔티티에 방의 시간 제한 Field를 추가한다. (Default 10000msec)
- 대기방 멤버 조회 DTO에 방의 게임 시작 여부 데이터를 추가한다.
- 대기방 멤버 조회 DTO에 방의 세팅정보 데이터를 추가한다.

## Check List
- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## Test Screenshot
<img width="709" alt="스크린샷 2024-07-31 16 20 21" src="https://github.com/user-attachments/assets/f7179ea5-a2c7-4243-aa29-6d184b661e57">

## (Optional) Additional Description

2024-07-31 07:28 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/room/dto/RoomInfoResponse.java
> +        RoomSettingResponse roomSettingResponse = new RoomSettingResponse(room.getTotalRound(), room.getTimeLimit());
일단 커찬이 코드상에서 from으로 작성해줘서 이어서 of로 작성해두었습니다.

커찬이 DTO 매핑 로직을 Service 클래스의 비즈니스 로직이 아니라 DTO 내부에 두어야 깔끔할 것 같다는 의견 하에
이렇게 리팩토링 된 것으로 알고 있는데요!

정팩메를 사용하는 이유가 딱히 느껴지지 않는 메서드라는 생각에 일단 생성자로 구현해보고자 했으나
Record에서 필드값과 다른 값을 생성자의 매개변수로 받는 것은 불가능해서 우선은 그대로 이어가게 되었습니다.
이 부분에 대해서 기준을 정해야할 것 같네요.

제가 이 코드를 통해 제시하고자 하는 기준은
from, of는 의미없는 네이밍이기 때문에 사용을 자제하되
record에서 발생하는 지금과 같은 상황이라면 생성자를 대체하는 표준으로 사용하자는 것입니다.
이 부분에 대해서 의견 남겨주시면 감사하겠습니다

2024-07-31 07:58 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/room/dto/RoomInfoResponse.java
> +        boolean isGameStart,
대기방에서 게임 시작 여부를 뭍는거라 isGameStart로 했는데,

Room 도메인에서는 RoomStatus가 `FINISH`까지 있기 때문에
Room 도메인의 게임 상태 체크 메서드명을 isGameStart로 하기에는 어색하다고 느껴져 isGameProgress라고 정의하였습니다.

2024-07-31 08:00 UTC, PgmJun commented on backend/src/test/java/ddangkong/service/balance/room/RoomServiceTest.java
> +        void 방_생성_시_방장_멤버를_생성하고_방을_생성한다() {
요기는 관련 부분은 아닌데 메서드명이 애매해서 같이 변경하였습니다.

2024-07-31 08:15 UTC, GIVEN53 requested changes
rest docs 테스트는 추후 반영되는 걸까요??

2024-07-31 08:15 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +    private static final int DEFAULT_TIME_LIMIT = 10000;
```suggestion
    private static final int DEFAULT_TIME_LIMIT_MS = 10000;
```
사소한 의견) 시간 단위가 변수명에 나타나면 좋겠으나, 방 설정 정보를 받는 것은 추후 구현되기 때문에 곧 사라질 상수라는 생각이 드네요 편하게 채택해주세요!

2024-07-31 08:15 UTC, GIVEN53 commented on backend/src/main/java/ddangkong/domain/balance/room/RoomStatus.java
> +        return isGameProgress;
```suggestion
        return this == PROGESS;
```

의견) boolean 변수가 의미있게 사용되지 않는 것 같아요 변수 제거 및 위와 같이 제안드립니다

2024-07-31 08:15 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/controller/balance/room/RoomControllerTest.java
> +            assertAll(
굳 👍🏻

2024-07-31 08:15 UTC, GIVEN53 commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +            final int TIME_LIMIT = 10000;
의견) 초기 정했던 코드 컨벤션에 따라 final 제거 및 카멜케이스로 수정되면 좋겠습니당

2024-07-31 08:20 UTC, leegwichan requested changes
이든 변경된 ERD 반영 아주 칭찬해!

사소한 의견들 달았으니, 코멘트 남겨주세요~~
추가적으로 RestDocs 작성해주세요~ (RestDocs 작성되면 Approve 하겠습니다~)

2024-07-31 08:20 UTC, leegwichan commented on backend/src/main/java/ddangkong/controller/balance/room/dto/RoomInfoResponse.java
> +        RoomSettingResponse roomSettingResponse = new RoomSettingResponse(room.getTotalRound(), room.getTimeLimit());
저도 동의합니다.
정팩매가 있어야 매핑 로직을 안으로 넣을 수 있겠다라구요;;

추가적으로 `fromMember(Member member)`보다는 `from(Member member)`형식이 더 좋다고 생각합니다. 전자는 인자로 알 수 있는 부분을 중복해서 쓰는 느낌이 강하다고 생각이 들어서요. 다들 의견 부탁드립니다~

2024-07-31 08:20 UTC, leegwichan commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +    private static final int DEFAULT_TIME_LIMIT = 10000;
사소한 의견) 조금 더 보기 편하지 않나요? (반영 안하셔도 됩니다~)
```suggestion
    private static final int DEFAULT_TIME_LIMIT = 10_000;
```

2024-07-31 08:20 UTC, leegwichan commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +            Room room = new Room(TOTAL_ROUND, CURRENT_ROUND, TIME_LIMIT, RoomStatus.PROGRESS);
사소한 의견) 메서드 안에 넣을 것이면 camelCase, 내부 클래스의 상수로 놔둘 것이면 SNAKE_CASE가 좋을 것 같아요!

2024-07-31 08:20 UTC, leegwichan commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +            assertThatThrownBy(room::moveToNextRound)
👍

2024-07-31 08:34 UTC, PgmJun commented on backend/src/main/java/ddangkong/controller/balance/room/dto/RoomInfoResponse.java
> +        RoomSettingResponse roomSettingResponse = new RoomSettingResponse(room.getTotalRound(), room.getTimeLimit());
네네 그냥 생성자 대용의 느낌이라 from, of 라는 네이밍으로 쓰면 될 것 같아요

2024-07-31 08:36 UTC, PgmJun commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +    private static final int DEFAULT_TIME_LIMIT = 10000;
해당 값 사용과 연결되는 방 설정값 적용 API 또한 이번 스프린트3에서 제 담당입니다만, 방 생성 시에 기본값은 그대로 가져갈 것 같습니다!
때문에 이해하기 편하도록 프린 의견 바로 변경해두겠습니다:)

2024-07-31 08:41 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +            final int TIME_LIMIT = 10000;
어우 체크 감사합니다!

2024-07-31 08:42 UTC, PgmJun commented on backend/src/test/java/ddangkong/domain/balance/room/RoomTest.java
> +            Room room = new Room(TOTAL_ROUND, CURRENT_ROUND, TIME_LIMIT, RoomStatus.PROGRESS);
동의합니다 체크 감사해요~~

2024-07-31 08:51 UTC, PgmJun commented
@GIVEN53 @leegwichan 지금 타칸의 RestDocs PR에 해당 API의 RestDocs가 물려있어서
해당 PR과 타칸 PR이 머지되면 그 후에 따로 작성하겠습니다.

2024-07-31 13:48 UTC, leegwichan approved these changes
LGTM! 반영하드라 고생했어!
그런데, 이거 CI 터졌는데 확인 좀;;

2024-08-01 00:05 UTC, jhon3242 reviewed
든든 수고했어요~~ CI 터진 부분이랑 라운드 시간 부분만 수정해주면 좋을 것 같아요~ 정팩매 관련해서는 저도 동일한 문제로 고민했었던터라 이든의 의견대로 하면 될 것 같아요~ 수고했어요~~ 💪💪

2024-08-01 00:05 UTC, jhon3242 commented on backend/src/main/java/ddangkong/domain/balance/room/Room.java
> +    private static final int DEFAULT_TIME_LIMIT_MSEC = 10_000;
의견) 저희 라운드 시간이 30초 였던 것 같아요~ 그리고 딜레이 시간(2초)까지 더해서 넣어주면 어떨까요??
<img width="707" alt="image" src="https://github.com/user-attachments/assets/ed03ef6d-b328-4d0e-b4d1-b6c4d82dda0a">

2024-08-01 04:07 UTC, GIVEN53 approved these changes
굿 뽀이~

2024-08-01 04:12 UTC, jhon3242 approved these changes

2024-08-01 04:13 UTC, merged